### ISSUE TITLE
Output CSS files to a single directory instead

### ISSUE THREAD

**Issue by satya164** [callstack/linaria#101]
Right now the generated CSS files pollute the project directory. It'll be nicer to have them in a single directory e.g. `.linaria-cache` or something

**Comment by thymikee** [comment]
There's already an option `outDir` to do so: https://github.com/callstack-io/linaria/blob/master/docs/BABEL_PRESET.md#options

**Comment by satya164** [comment]
Yes, but the default option is not the best possible experience. It should output to single directory by default.
