### ISSUE TITLE
linaria@4.1 breaks jest

### ISSUE THREAD

**Issue by nstepien** [callstack/linaria#1021]
## Environment

- Linaria version: 4.1.0
- Bundler (+ version): webpack@5.72.0, rollup@2.71.1
- Node.js version: 18.6.0
- OS: Win11

## Description

linaria@4 breaks jest, while it was working fine with linaria@3.

```
 FAIL  test/column/cellClass.test.ts
  ● Test suite failed to run

    Using the "css" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly.

      1 | import { css } from '@linaria/core';
      2 |
    > 3 | export const row = css`
        |                        ^
```

## Reproducible Demo

https://github.com/adazzle/react-data-grid/pull/2962

**Comment by Anber** [comment]
Maybe fixed :)

**Comment by nstepien** [comment]
Package update soon? I'd love to try it

**Comment by Anber** [comment]
@nstepien published.

**Comment by nstepien** [comment]
It worked! Thank you very much
