### ISSUE TITLE
Support CRA or at least https://github.com/timarney/react-app-rewired

### ISSUE THREAD

**Issue by jukben** [callstack/linaria#103]

**Comment by AgtLucas** [comment]
+1 for this!

**Comment by thymikee** [comment]
@jukben do you have time to take a look at this? :)

**Comment by jukben** [comment]
@thymikee I'd like to. I'm sure that there is a way how to solve this with React-app-rewired. I could write a plugin with linaria configuration, but someone needs to setup Lerna.

**Comment by dumaron** [comment]
+1 for me too. 
I've tried to do what @jukben suggested in the last comment, but without luck.

**Comment by satya164** [comment]
@dumaron checkout https://github.com/callstack/linaria/pull/126

**Comment by zamotany** [comment]
We cannot suport CRA with altering configuration files. If you want to use it with CRA, the only option is to eject.

**Comment by drownbes** [comment]
@jukben Check this: https://github.com/drownbes/linaria-cra
