### ISSUE TITLE
Conflict between @linaria/shaker and @babel/preset-env

### ISSUE THREAD

**Issue by billykwok** [callstack/linaria#1034]
## Environment

- Linaria version: v4+
- Bundler (+ version): Webpack 5+
- Node.js version: 18+
- OS: macOS 15.6

## Description

There is a new hardcoded [`envName: 'linaria'` option](https://github.com/callstack/linaria/blob/master/packages/shaker/src/index.ts#L25) specified in the babel config of shaker v4, but [not in v3](https://github.com/callstack/linaria/blob/%40linaria/shaker@3.0.0-beta.22/packages/shaker/src/index.ts).

This should be fine in theory as shaker merges user config into the internal one. However, the order of arguments makes the internal option take a [higher precedence](https://github.com/callstack/linaria/blob/master/packages/shaker/src/index.ts#L48) than the user-provided one, preventing the user-provided `envName` from overriding `'linaria'`.

As an example of the issues caused by such conflict, if a user uses the following type import statement via `@babel/preset-typescript` inside an env config, an error would be thrown.

```
import { type HTMLAttributes, useRef } from 'react';
```

```
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/sandbox/public' directory
<i> [webpack-dev-middleware] wait until bundle finished: /
/sandbox/node_modules/@babel/parser/lib/index.js:72
}, descriptor)), Object.assign(new constructor(), properties));
                               ^

SyntaxError: /sandbox/src/App.tsx: Unexpected token, expected "," (1:14)

> 1 | import { type HTMLAttributes } from 'react';
    |               ^
    at instantiate (/sandbox/node_modules/@babel/parser/lib/index.js:72:32)
    at constructor (/sandbox/node_modules/@babel/parser/lib/index.js:359:12)
    at Parser.raise (/sandbox/node_modules/@babel/parser/lib/index.js:3339:19)
    at Parser.unexpected (/sandbox/node_modules/@babel/parser/lib/index.js:3377:16)
    at Parser.expect (/sandbox/node_modules/@babel/parser/lib/index.js:4006:28)
    at Parser.parseNamedImportSpecifiers (/sandbox/node_modules/@babel/parser/lib/index.js:16492:14)
    at Parser.parseImport (/sandbox/node_modules/@babel/parser/lib/index.js:16309:39)
    at Parser.parseStatementContent (/sandbox/node_modules/@babel/parser/lib/index.js:14753:27)
    at Parser.parseStatement (/sandbox/node_modules/@babel/parser/lib/index.js:14643:17)
    at Parser.parseBlockOrModuleBlockBody (/sandbox/node_modules/@babel/parser/lib/index.js:15286:25) {
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'UnexpectedToken',
  loc: Position { line: 1, column: 14, index: 14 },
  pos: [Getter/Setter]
}
```

> `import type { HTMLAttributes } from 'react';` does not have the same issue potentially because shaker understands this version of type import.

## A few possible fixes

- Remove the `envName` option as it doesn't seem to serve any purpose
- Allow user-provided options to take higher precedence in shaker's babel options
- Support the `{ type Type }` variation of type import in shaker (having to support new import syntax everytime it is added to TypeScript doesn't seem like a sustainable solution)

## Reproducible Demo

[https://codesandbox.io/s/linaria-4-typed-import-we43j9
](https://codesandbox.io/s/linaria-4-typed-import-we43j9)

**Comment by kryops** [comment]
I believe this also causes issues with the `react-refreh` babel plugin (which can be worked around though):

```
Error: [BABEL] /home/michael/git/vlight/frontend/src/settings.tsx: React Refresh Babel transform should only be enabled in development environment. Instead, the environment is: "linaria". If you want to override this check, pass {skipEnvCheck: "/home/michael/git/vlight/node_modules/react-refresh/babel.js")
```

**Comment by Anber** [comment]
Hi @billykwok

> Remove the envName option as it doesn't seem to serve any purpose

It allows overriding babel config exclusively for the shaker stage, but yeah, it looks like it causes more harm than provides benefits. Thank you!
