### ISSUE TITLE
Broken styled variables interpolation

### ISSUE THREAD

**Issue by MaxSvargal-imhio** [callstack/linaria#1042]
## Environment
next@12.2.4
next-linaria@0.11.1

- Linaria version: 4.1.2
- Bundler (+ version): webpack@4.3
- Node.js version: 18.2.0
- OS: Mac OS 10.14 + Linux Sandbox

## Description
Variables in tag functions does not render at all
![Screenshot 2022-08-08 at 16 22 47](https://user-images.githubusercontent.com/72729509/183385551-cad80cf6-7de9-41eb-a194-6eaad1ddc867.png)

## Reproducible Demo
https://codesandbox.io/s/next-js-forked-8xwkb7?file=/pages/index.js

**Comment by Anber** [comment]
Hi @MaxSvargal-imhio!
Fixed in #1051.

Btw, you probably don't need to specify `linaria/babel` in `babel.config.js`. It is necessary only if you build libraries or use a monorepo. Otherwise, all transformations will be done in the webpack loader.
