### ISSUE TITLE
Named export 'styled' not found. The requested module '@linaria/react' is a CommonJS module

### ISSUE THREAD

**Issue by RanolP** [callstack/linaria#1043]
## Environment

- Linaria version: 
    "@linaria/react": "4.1.2",
    "@linaria/rollup": "4.1.2"
- Bundler (+ version): vite 3.0.4 with vite-plugin-ssr 0.4.18
- Node.js version: v18.7.0
- OS: Arch Linux

## Description

I'm writing a frontend with an SSR server using ESM and recently wanted to use linaria. But the linaria packages cannot be imported as an ESM module in a Node ESM environment.

## Reproducible Demo

[RanolP/node-esm-linaria-repro](https://github.com/RanolP/node-esm-linaria-repro), It does not use any bundler at all for concentrating to its root problem.

## Related Issue

- #904

**Comment by Anber** [comment]
Hi @RanolP!

Probably, has been fixed in the last release. Could you please confirm it?

**Comment by Anber** [comment]
Looks like we can just update the version of `@emotion/is-prop-valid`. I'll publish a fix in a couple of days.

**Comment by Anber** [comment]
@RanolP released.

**Comment by Anber** [comment]
I don't think it's a big deal to just fork `@emotion/is-prop-valid`. I'll do it this weekend.
