### ISSUE TITLE
Issues with `styled` API on linaria v4.1.2 (on both react / atomic)

### ISSUE THREAD

**Issue by juanferreras** [callstack/linaria#1059]
## Environment

- Linaria version:
```
"@linaria/atomic": "4.1.2",
"@linaria/babel-preset": "4.1.2",
"@linaria/core": "4.1.1", 
"@linaria/react": "4.1.2",
"@linaria/webpack-loader": "4.1.2",
```
- Bundler (+ version): `webpack v5`
- Node.js version: `v16.14.2`
- OS: N/A (linux)

This is using Next.js `v12.2.0` / React `v18.2.0` latest stable major versions.

## Description

There are 3 separated issues reproducible in the `stackblitz`:

1. `@linaria/react styled` dynamic interpolation – the `color: var(--hash-0);` rule is extracted but `style="--hash-0: blue;"` is never defined in the React component
2. `@linaria/react styled` does not work if it is defined after a `@linaria/core css` – seems to be a mismatch between the `.hash{}` extracted vs the className defined in the element.
3. `@linaria/atomic styled` crashes the page yielding the error `Error: Styles are not extracted yet. Please call extractRules first`.

The first issue is related/close to #1048 but it isn't just when interpolating another CSS Custom Property such as 
```color: ${(props) => `var(--${props.color})`};``` – it seems to be all interpolations, including basic ones.

## Reproducible Demo

All three issues can be seen in https://stackblitz.com/edit/linaria-4-1-2.

- `/` page shows issue number 1 (`<Heading/>` should have color blue)
- `/` page shows issue number 2 (`<CTADoesNotWork/>` is extracted as `.c11w1uky` and the DOM node uses class `czg3ah`)
- `/atomic-styled` page shows issue number 3 (page crashes and error overlay displays the error cited above)

There could be a misconfiguration on webpack / a new incompatibility with the setup most folks have with Next.js – but for reference, see the same sandbox using `v3.0.0-beta.22` working as expected on all 3 issues in https://stackblitz.com/edit/linaria-4-1-2-baseline

Happy to submit it as a github repo if the sandbox is problematic! Many thanks 🙏

**Comment by juanferreras** [comment]
#1052 release fixes all 3 of these! great job @Anber! 🎊 

Updating to the latest stable releases, fixes all 3 cited issues.
```
"@linaria/atomic": "4.1.3",
"@linaria/babel-preset": "4.2.0",
"@linaria/core": "4.1.2",
"@linaria/react": "4.1.3",
"@linaria/webpack-loader": "4.1.3"
```

see https://stackblitz.com/edit/linaria-4-1-3

**Comment by Anber** [comment]
Oops 😃

**Comment by juanferreras** [comment]
> @juanferreras, the problem happened because `styled.h1` was processed twice: the first time with babel and the second time with webpack-loader. I've fixed the behaviour in that edge case, but I recommend you remove `@linaria` from your `.babelrc`. It is needed only if you have monorepo and want your styles to be pre-built or if you are making the library. In all other cases, loaders do all the work.

@Anber noted – many thanks, makes a lot of sense now. I wonder if we should make that more explicit in `README.md` and/or `docs/CONFIGURATION.md`. _"You should only use this if X or Y, but you shouldn't use it otherwise as you'll process things twice which can be error-prone on edge cases and ultimately twice as slow."_
