### ISSUE TITLE
Does auto fix work with @linaria-postcss ?

### ISSUE THREAD

**Issue by usmanyunusov** [callstack/linaria#1074]
before
```pcss
const Box = styled.div`
  position: relative;
  height: ${(props) => props.size}px;
`;
```

after
```pcss
const Box = styled.div`
  position: relative;
  height: /* pcss-lin:0 */ px;
`;
```

**Comment by kutnickclose** [comment]
I didn't really test autofix much so I'm not 100% sure. I likely won't have time to make an updates myself in the next few weeks.

There is one test here: 
https://github.com/callstack/linaria/blob/master/packages/postcss-linaria/__tests__/stylelint.test.ts#L34

I would have expected the interim css to be 
```
const Box = styled.div`
  position: relative;
  height: pcss-lin:0px;
`;
```

so there may be a placeholder issue here.  If it is a placeholder issue then the code that might need an update would be here: https://github.com/callstack/linaria/blob/master/packages/postcss-linaria/src/util.ts#L70

**Comment by FatehAK** [comment]
I'm facing the same issue using `@linaria-postcss` with stylelint's autofix 

Before:
```js
export const heroContentSubInfo = css`
  position: relative;
  top: -10px;
  margin-left: 60px;
  padding: 10px;
  font-family: Lato, sans-serif;

  @media (max-width: ${breakpoints.desktop}) {
    font-size: 1.15rem;
  }

  @media (max-width: ${breakpoints.tablet}) {
    font-size: 1rem;
  }
`;
```
After:
```js
export const heroContentSubInfo = css`
  position: relative;
  top: -10px;
  margin-left: 60px;
  padding: 10px;
  font-family: Lato, sans-serif;

  @media (max-width: .pcss-lin0) {
    font-size: 1.15rem;
  }

  @media (max-width: .pcss-lin1) {
    font-size: 1rem;
  }
`;
```

We use stylelint's autofix feature extensively for making autofixes in lint-staged while commiting files but we are unable to do so now because of this issue. Could you please help with this?

**Comment by hjkcai** [comment]
+1

I have another bad case to share.

Before:

```ts
const SomeStyle = css`
  display: flex;
`

const AnotherStyle = css`
  .${SomeStyle} & {
    align-items: center;
  }
`
```

After:

```ts
const SomeStyle = css`
  display: flex;
`

const AnotherStyle = css`
  ${SomeStyle} & {  // <- The dot prefix is gone. This makes the class selector become a tag selector
    align-items: center;
  }
`
```
