### ISSUE TITLE
[Feature] motion one animation library support

### ISSUE THREAD

**Issue by kevinseabourne** [callstack/linaria#1088]
Feature Request

Support for [motion one](https://github.com/motiondivision/motionone) animation library. [Motion one](https://github.com/motiondivision/motionone) is an amazing library similar to framer motion which can provide physics based spring animations. Framer motion is a very similar library built by the same person Matt Perry. It works fine with styled components but It would be great to potentially have a framework agnostic animation library like motion one be supported by a css in js library like linaria.   

`const Button = styled(motion.button)`

**Comment by Anber** [comment]
Hi @kevinseabourne!

I'm unfamiliar with Motion One, but `styled` from `@linaria/react` should work with anything that accepts `className` and `style` properties. `@linaria/solid` is in development and hopefully will be released soon.

**Comment by kevinseabourne** [comment]
motion one is great !  do you know if motion one works with linaria in react ? would it be declared like this
 `const button = styled(motion.button)`

I had a look at the properties motion one takes if this helps
`motion(el: Element, props: Accessor<Options>): void;`

`
export declare type Options = {
    initial?: false | VariantDefinition;
    animate?: VariantDefinition;
    inView?: VariantDefinition;
    hover?: VariantDefinition;
    press?: VariantDefinition;
    exit?: VariantDefinition;
    variants?: Record<string, Variant>;
    inViewOptions?: InViewOptions;
    transition?: AnimationOptionsWithOverrides;
};
`

**Comment by Anber** [comment]
The error says that `motion` itself doesn't have `button` property. It is nothing to do with Linaria.
