### ISSUE TITLE
Babel plugin to Hoist CSS

### ISSUE THREAD

**Issue by satya164** [callstack/linaria#110]
What if we could write a CSS rule inline without having to give it a name? A Babel plugin can automatically hoist this to the program scope and give it a name.

This JavaScript:

```js
function MyComponent() {
  return <article {...styles(css`color: blue;`)} />;
}
```

Gets transpiled into:

```js
function MyComponent() {
  return <article {...styles(_article)} />;
}
var _article = css`color: blue;`;
```

Context: https://twitter.com/ryanflorence/status/907316693084418048

Implementation:

```js
export default function(babel) {
  const { types: t } = babel;

  return {
    visitor: {
      Program: {
        enter(path, state) {
          state.cssRules = {};
        },
        exit(path, state) {
          Object.keys(state.cssRules).forEach(name => {
            path.node.body.push(
              t.variableDeclaration("var", [t.variableDeclarator(t.identifier(name), state.cssRules[name])])
            );
          });
        }
      },
      JSXOpeningElement(path, state) {
        path.node.attributes.forEach(attr => {
          if (t.isJSXSpreadAttribute(attr) && t.isCallExpression(attr.argument) && attr.argument.callee.name === "styles") {
            attr.argument.arguments = attr.argument.arguments.map(arg => {
              if (t.isTaggedTemplateExpression(arg) && arg.tag.name === "css") {
                const className = path.scope.generateUidIdentifier(path.node.name.name);
                state.cssRules[className.name] = arg;
                return className;
              }
              return arg;
            });
          }
        });
      }
    }
  };
}
```

**Comment by hamlim** [comment]
From an initial look at this, it would be even better in my opinion if you also didn't need the `{...styles()}` wrapper around the css call:

```Javascript
const Component = props => <div css={` color: red; `} />;
```
would ideally get compiled into

```Javascript
const Component = props => <div {...styles(_whatever)} />;
const _whatever = css`color: red;`;
```
You would then of course possibly run into issues if some codebase uses both glamor(ous)/emotion and linaria.

But either way i think this could be really beneficial.

**Comment by satya164** [comment]
> @hamlim: it would be even better in my opinion if you also didn't need the {...styles()} wrapper around the css call

It'd certainly be nicer to use. But the reason I avoid a `css` prop is because it's not actually a prop, and won't behave like a prop (e.g. - `this.props.css` in the component won't actually have the string). It can be confusing to change runtime semantics.

Currently if you try to use Linaria without the babel plugin, it still works as expected. The build step is just an additional optimization step to extract the static CSS, but it doesn't affect the runtime semantics.

Maybe we can simplify it to something like:

```js
<div {...styles`color:blue`} />
```

A small issue that we won't get syntax highlighting without the `css` tag with current editors plugins.

**Comment by hamlim** [comment]
Ah yea thats a good point, yea the ```{...styles`color: blue;`}``` idea also seems really good as well.
