### ISSUE TITLE
Incompatibility with vite-plugin-ssr

### ISSUE THREAD

**Issue by RanolP** [callstack/linaria#1105]
## Environment

- Linaria version:
    "@linaria/core": "4.2.2",
    "@linaria/react": "4.3.0",
    "@linaria/rollup": "4.2.2",
- Bundler (+ version):
    "vite": "3.2.0",
    "vite-plugin-ssr": "0.4.43",
- Node.js version: v19.0.0
- OS: Arch Linux

## Description

Using `vite dev`, vite-plugin-ssr tries to load unbundled CSS files over HTTP with [querystring `?direct`](https://github.com/brillout/vite-plugin-ssr/blob/0e5d96215999d68cdcfe0a114712750e4bec9267/vite-plugin-ssr/node/renderPage/getPageAssets.ts#L60)

But the `@linaria/rollup` stores the exact path as seen below,

https://github.com/callstack/linaria/blob/462739a781e31d5a8266957c0a4800292f452441/packages/rollup/src/index.ts#L114-L124

for the match.

https://github.com/callstack/linaria/blob/462739a781e31d5a8266957c0a4800292f452441/packages/rollup/src/index.ts#L57-L63

Due to vite-plugin-ssr, made URL looks like `http://localhost:3000/src/components/MyComponent_1sjkoh1.css?direct`. This will give the rollup plugin `src/components/MyComponent_1sjkoh1.css?direct` as the path. Thus, `@linaria/rollup` matches nothing and returns nothing. But I think there should be an option to match the string without querystring.

**Comment by MrFoxPro** [comment]
@RanolP check this with @linaria/vite plugin please.

**Comment by RanolP** [comment]
I cannot check that the package is working because it is not released to npm yet. But I think the direction you're going is correct.
