### ISSUE TITLE
"watch" tasks doesn't work as expected

### ISSUE THREAD

**Issue by MrFoxPro** [callstack/linaria#1124]
Currently there are "watch" tasks in majority of packages.
E.g. @linaria/preset-babel:
```json
  "scripts": {
    "build": "npm run build:lib && npm run build:esm && npm run build:declarations",
    "build:declarations": "tsc --emitDeclarationOnly --outDir types",
    "build:esm": "babel src --out-dir esm --extensions '.js,.jsx,.ts,.tsx' --source-maps --delete-dir-on-start",
    "build:lib": "cross-env NODE_ENV=legacy babel src --out-dir lib --extensions '.js,.jsx,.ts,.tsx' --source-maps --delete-dir-on-start",
    "test": "jest --config ./jest.config.js --rootDir src",
    "typecheck": "tsc --noEmit --composite false",
    "watch": "npm run build --watch"
  },
```
`npm run build --watch` will run tasks sequentially and append '--watch' only to latest one (if append it all, in my case **npm** didn't prepend, however **pnpm** did).
So it doesn't work as expected.

I don't know how to fix that exactly. Pnpm can run in parallel only same task in different packages.
I didin't find feature for this in **turbo**.
There are:
- https://github.com/open-cli-tools/concurrently
- https://github.com/coderaiser/redrun
- https://github.com/coderaiser/madrun

**Comment by Anber** [comment]
Yep. This `watch` is an artefact from the yarn+lerna time.

**Comment by MrFoxPro** [comment]
https://github.com/callstack/linaria/pull/1125
