### ISSUE TITLE
EvalError: (0 , _solidJs.createContext) is not a function

### ISSUE THREAD

**Issue by usmanyunusov** [callstack/linaria#1134]
I get the bug when I use `linaria` with `solid-js`.

`EvalError: (0 , _solidJs.createContext) is not a function in`

I think we need to to rule it out as at https://github.com/callstack/linaria/blob/master/packages/utils/src/isUnnecessaryReactCall.ts#L53

**Comment by Anber** [comment]
Well… It looks like it's time to decide how we can move those logic from `utils`, to library-specific logic.

**Comment by usmanyunusov** [comment]
@Anber, there is a temporary way around it?

**Comment by Anber** [comment]
@usmanyunusov I don't think so. Could you please make a repo that reproduces this error?

**Comment by layershifter** [comment]
@usmanyunusov this have been fixed in v5, https://stackblitz.com/edit/linaria-bug-uapcv9 🎉
