### ISSUE TITLE
@linaria/esbuild install its own version of esbuild

### ISSUE THREAD

**Issue by blixt** [callstack/linaria#1139]
## Environment

- Linaria version: 4.2.2
- Bundler (+ version): –
- Node.js version: –
- OS: –

## Description

The ESBuild plugin package install its own version of `esbuild` which is a bit strange because in order to be a plugin, `esbuild` must already exist because it's the one calling the plugin. I understand it's included as a dependency because it's being imported by the plugin, but it should be a `peerDependencies` entry so that the outer `esbuild` is used.

In our build environment we are getting the following crash in our CI which stems from inside the plugin (note: the outer `esbuild` works just fine):

```
Error: esbuild: Failed to install correctly

Make sure you don't have "ignore-scripts" set to true. You can check this with
"npm config get ignore-scripts". If that returns true you can reset it back to
false using "npm config set ignore-scripts false" and then reinstall esbuild.

If you're using npm v7, make sure your package-lock.json file contains either
"lockfileVersion": 1 or the code "hasInstallScript": true. If it doesn't have
either of those, then it is likely the case that a known bug in npm v7 has
corrupted your package-lock.json file. Regenerating your package-lock.json file
should fix this issue.

    at Object.<anonymous> (/mnt/ramdisk/node_modules/@linaria/esbuild/node_modules/esbuild/bin/esbuild:2:7)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

## Reproducible Demo

I'm not sure how to create a reproducible demo for this, but I think it's pretty common practice to use `peerDependencies` for dependencies that are known to be provided by the user of the package, and `@linaria/esbuild` cannot (AFAIK) be used unless it's via the `esbuild` package.

**Comment by Anber** [comment]
Good point. I'll move `esbuild` to `peerDependencies` in the following release.
