### ISSUE TITLE
Linaria 4.2.3 css throws a 404 with Vite 3.2.3

### ISSUE THREAD

**Issue by mssngr** [callstack/linaria#1147]
## Environment

- Linaria version: 4.2.3
- Bundler (+ version): Vite 3.2.3
- Node.js version: 
- OS: macOS Monterey Version 12.6.1 (21G217)

## Description

Installing Vite and Linaria fresh and following the instructions in Linaria's repo does not seem to work. When running Vite's "dev" script with the @linaria/rollup plugin, the request for the css generated by Linaria returns with a 404 error, as seen in the network tab.

<img width="403" alt="Screen Shot 2022-12-04 at 6 58 39 AM" src="https://user-images.githubusercontent.com/23464169/205494771-933d275d-7789-4ade-87c4-9070a41d181c.png">

<img width="454" alt="Screen Shot 2022-12-04 at 6 58 22 AM" src="https://user-images.githubusercontent.com/23464169/205494776-efd2b2e1-99a2-48f5-9a62-76396141b4f7.png">

## Reproducible Demo

Code: https://codesandbox.io/p/sandbox/linaria-doesnt-work-with-vite-i3vcrs
Live Preview: https://i3vcrs-5173.preview.csb.app/
Error in Demo: 
<img width="437" alt="Screen Shot 2022-12-04 at 6 42 38 AM" src="https://user-images.githubusercontent.com/23464169/205494375-9b8598fc-82f5-4a77-b674-c9e5ec4706a9.png">

**Comment by MrFoxPro** [comment]
@mssngr please try @linaria/vite instead.

**Comment by mssngr** [comment]
That definitely works, no extra configuration:

```
pnpm add -D @linaria/vite
```

```ts
// vite.config.ts
import { defineConfig } from 'vite'
import tsconfigPaths from 'vite-tsconfig-paths'
import linaria from '@linaria/vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), tsconfigPaths(), linaria()],
})
```

Should, perhaps, the README.md get updated with the new instructions?

**Comment by kozlikov** [comment]
Unfortunately, @linaria/rollup no longer works with the latest version of vite and perhaps the README is currently unreliable. The @linaria/vite plugin, on the other hand, is fine!

**Comment by layershifter** [comment]
> That definitely works, no extra configuration:
> 
> ```
> pnpm add -D @linaria/vite
> ```
> 
> ```ts
> // vite.config.ts
> import { defineConfig } from 'vite'
> import tsconfigPaths from 'vite-tsconfig-paths'
> import linaria from '@linaria/vite'
> import react from '@vitejs/plugin-react'
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [react(), tsconfigPaths(), linaria()],
> })
> ```
> 
> Should, perhaps, the README.md get updated with the new instructions?

This is a proper solution, please use `@linaria/vite` with Vite. Feel free to open a PR that updates documentation, help is much appreciated 🐱
