### ISSUE TITLE
After upgraded to latest version, the infinite loop issue seems still exists.

### ISSUE THREAD

**Issue by towry** [callstack/linaria#1202]
After upgraded to latest version, the infinite loop issue seems still exists.

![截屏2023-02-07 09 11 59](https://user-images.githubusercontent.com/8279858/217122661-e540965e-006a-4e5e-9179-bacee487634c.png)

stuck.

_Originally posted by @towry in https://github.com/callstack/linaria/issues/1193#issuecomment-1420024623_

Added a log in `node_modules/@linaria/babel-preset/lib/transform-stages/1-prepare-for-eval.js`

```
const queue = new _ModuleQueue.ModuleQueue(entrypoint);
  while (!queue.isEmpty()) {
    console.log('------');
    var _queue$dequeue2;
```
The console.log keep logging never stop.

![截屏2023-02-07 09 18 06](https://user-images.githubusercontent.com/8279858/217123402-2580d55a-58c1-4d98-aaa6-80d40e2e4a69.png)

## Reproduce steps

1. git clone --depth=1 https://github.com/layershifter/linaria-circulars-issue
2. update the deps to `@linaria/babel-preset@4.4.0` using below scripts.
3. run `npm run b:webpack:linaria`

npm pkg dep update script (you need jq installed):

```bash
npm update --strict-peer-deps && npm list --json | jq --slurpfile package package.json 'def replaceVersion($replacements): with_entries(if .value | startswith("^") then .value = ("^" + $replacements[.key].version) else . end); .dependencies as $resolved | reduce ["dependencies", "devDependencies"][] as $deps ($package[0]; if .[$deps] | type == "object" then .[$deps] |= replaceVersion($resolved) else . end)' > package.json~ && mv package.json~ package.json && npm install
```

**Comment by towry** [comment]
`npm list --all | grep linaria`:

```
├─┬ @linaria/babel-preset@4.4.0
│ ├── @linaria/core@4.2.6 deduped
│ ├─┬ @linaria/logger@4.0.0
│ ├── @linaria/shaker@4.2.8 deduped
│ ├─┬ @linaria/tags@4.3.1
│ │ ├── @linaria/logger@4.0.0 deduped
│ │ └── @linaria/utils@4.3.1 deduped
│ ├─┬ @linaria/utils@4.3.1
│ │ ├── @linaria/logger@4.0.0 deduped
├─┬ @linaria/core@4.2.6
│ ├── @linaria/logger@4.0.0 deduped
│ ├── @linaria/tags@4.3.1 deduped
│ └── @linaria/utils@4.3.1 deduped
├─┬ @linaria/react@4.3.4
│ ├── @linaria/core@4.2.6 deduped
│ ├── @linaria/tags@4.3.1 deduped
│ ├── @linaria/utils@4.3.1 deduped
├─┬ @linaria/shaker@4.2.8
│ ├── @linaria/logger@4.0.0 deduped
│ ├── @linaria/utils@4.3.1 deduped
├─┬ @linaria/webpack5-loader@4.1.12
│ ├── @linaria/babel-preset@4.4.0 deduped
│ ├── @linaria/logger@4.0.0 deduped
```

I am using webpack 5.75.0

**Comment by Anber** [comment]
🤦
I hope #1205 will finally fix it :)

**Comment by TchernyavskyDaniil** [comment]
@Anber infinite loop was fixed, but

> EvalError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher') in


![изображение](https://user-images.githubusercontent.com/29048318/217528263-209918f5-b39a-44b6-9c23-c88a2403a364.png)

**Comment by Anber** [comment]
@TchernyavskyDaniil it looks like another bug. Could you please try to create a repo that reproduces the error?

**Comment by towry** [comment]
This bug has really been fixed.

Thanks.

**Comment by TchernyavskyDaniil** [comment]
Solved, thanks
