### ISSUE TITLE
Linaria crashes trying to evaluate ESM

### ISSUE THREAD

**Issue by nstepien** [callstack/linaria#1207]
## Environment

- Linaria version: `@linaria/webpack5-loader@4.1.13`
- Bundler (+ version): `webpack@5.75.0`
- Node.js version: 19.6.0
- OS: win11

## Description

Linaria tries to evaluate modules and fails when it encounters ESM.
(Why does linaria do this? 🤔 Does it extract data that way? Can it leverage babel's parser instead?)
https://github.com/callstack/linaria/blob/master/packages/babel/src/module.ts#L492-L518

In our case it tries to evaluate an npm dependency.
(Again, why? We don't transpile our `node_modules`.)

This does not happen on linaria v3.

```
ERROR in ./main.js
Module build failed (from ./node_modules/@linaria/webpack5-loader/lib/index.js):
D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\module.js:362
      throw new EvalError(`${e.message} in${callstack.join('\n| ')}\n`);
      ^

EvalError: Cannot use import statement outside a module in
| D:\repos\vite-bug\node_modules\react-data-grid\lib\bundle.js
| D:\repos\vite-bug\main.js

    at Module.evaluate (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\module.js:362:13)
    at require.Object.assign.ensure (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\module.js:302:13)   
    at D:\repos\vite-bug\main.js:3:45
    at D:\repos\vite-bug\main.js:7:3
    at Script.runInContext (node:vm:140:12)
    at Module.evaluate (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\module.js:349:14)
    at evaluate (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\evaluators\index.js:20:5)
    at evalStage (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\transform-stages\2-eval.js:26:45)      
    at syncStages (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\transform.js:47:45)
    at transform (D:\repos\vite-bug\node_modules\@linaria\babel-preset\lib\transform.js:146:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

webpack 5.75.0 compiled with 1 error in 493 ms
```

## Reproducible Demo

https://github.com/nstepien/vite-bug/tree/webpack

1. Clone the repo above
2. checkout the `webpack` branch
3. `npm ci`
4. `npm run build`

If you remove `import DataGrid from 'react-data-grid'` in `main.js` then the build works fine.

**Comment by TchernyavskyDaniil** [comment]
This problem is very relevant when you want to use some libraries

**Comment by Vadimchesh** [comment]
I did't dive dipper, but it works for me
```js
const nodeExternals = require('webpack-node-externals');
{
   loader: require.resolve('@linaria/webpack5-loader'),
   options: { sourceMap: true, ignore: [nodeExternals()] },
},
```

**Comment by WJCHumble** [comment]
@nstepien I think this issue is the same as https://github.com/callstack/linaria/issues/1022, where you can learn the specific reason for this design. By default, linaria will convert the ESM to CJS via `@linaria/shaker`, but if you are using Windows, you need to set the `linaria.config.js` yourself, which will look like this:
```javascript
const nodeModulesRegExp = /[\\/]node_modules[\\/]/;

module.exports = {
    rules: [
        {
            action: require.resolve('@linaria/shaker'),
        },
        {
            test: nodeModulesRegExp,
            action: 'ignore',
        },
        {
            test: (filename, code) => {
                if (!nodeModulesRegExp.test(filename)) {
                    return false;
                }

                return /(?:^|\n|;)\s*(?:export|import)\s+/.test(code);
            },
            action: require.resolve('@linaria/shaker'),
        }
    ]
};
```

**Comment by nstepien** [comment]
I can't reproduce this exact error anymore with the latest version of linaria, so I'm closing it.
I do however get a different EvalError, so I opened #1242.
