### ISSUE TITLE
Tags parsing is too aggressive

### ISSUE THREAD

**Issue by layershifter** [callstack/linaria#1214]
## Environment

- Linaria version: `@linaria/babel-preset@4.4.2`
- Bundler (+ version): N/A
- Node.js version: 16
- OS: N/A

## Description

There are cases when a tag parser (or traversal) is too aggressive and causes unexpected failures. There are two cases that I currently found.

### CJS re-export produced by TS

```ts
// TS code
export { styled } from '@linaria/react'
```

⬇️⬇️⬇️

```js
// CJS code
var react_1 = /*#__PURE__*/ require('@linaria/react');

Object.defineProperty(exports, 'styled', {
  enumerable: true,
  get: function () {
    return react_1.styled;
  },
});
```

Results in:

```
SyntaxError: /home/projects/node-hyqpx9/code/exampleB.js: /home/projects/node-hyqpx9/code/exampleB.js: Invalid usage of `styled` tag
  4 |   enumerable: true,
  5 |   get: function () {
> 6 |     return react_1.styled;
    |            ^^^^^^^
  7 |   },
  8 | });
  9 |
```

- Source in `./code/exampleB.js`
- To run `node ./testB.js`

### Usage of identifier in TS types

```ts
import { styled } from '@linaria/react';

export type StyledReturn = ReturnType<typeof styled>;
```

Results in:

```
SyntaxError: /home/projects/node-hyqpx9/code/exampleA.ts: /home/projects/node-hyqpx9/code/exampleA.ts: Invalid usage of `styled` tag
  1 | import { styled } from '@linaria/react';
  2 |
> 3 | export type StyledReturn = ReturnType<typeof styled>;
    |     
```

- Source in `./code/exampleA.ts`
- To run `node ./testA.js`

## Reproducible Demo

https://stackblitz.com/edit/node-hyqpx9

**Comment by therealgilles** [comment]
@Anber I think you fixed the cases you added test cases for but you did not fix this particular bug. This issue should be re-opened.

**Comment by therealgilles** [comment]
More specifically this case is still failing:
```TSX
import { styled } from '@linaria/react';

export type StyledReturn = ReturnType<typeof styled>;
```

**Comment by layershifter** [comment]
@Anber I bumped reproduction to latest and indeed, it still reproes: https://stackblitz.com/edit/node-hyqpx9?file=package.json,testB.js

This happens because `validateParams(params, ['tag', '...'], TaggedTemplateProcessor.SKIP);` does not throw: `isValidParams` returns `true` as `...` satisfies any constraints.
