### ISSUE TITLE
Styled API: When using a function in styled component is not rendered unless predifined

### ISSUE THREAD

**Issue by afridley** [callstack/linaria#1221]
## Environment

Linaria version: Linaria react 4.3.3
Bundler (+ version): Gatsby 5.4.0
Node.js version: 18.14.1
OS: OS X

## Description
When rendering components in linaria version 4 with styled components are not rendered when we pass props via a function. However this worked correctly in linaria v2.3.1.

```tsx
// Does not render to the page. Yet was working in linaria v2
const Pass = styled((props) => <DemoComp {...props} />)`
  color: red;
`;

// Shows up when predefined
const Predif = (props) => <DemoComp {...props} />;

const PassPredif = styled(Predif)`
  color: blue;
`;

```

## Reproducible Demo
https://codesandbox.io/s/linaria-v5-disapear-forked-x1dtvx?file=/src/App.tsx

**Comment by Anber** [comment]
The same reason https://github.com/callstack/linaria/issues/1222#issuecomment-1521437833
