### ISSUE TITLE
Styled API: Props are not correctly passed to react component.

### ISSUE THREAD

**Issue by afridley** [callstack/linaria#1222]
## Environment

Linaria version: Linaria react 4.3.3
Bundler (+ version): Gatsby 5.4.0
Node.js version: 18.14.1
OS: OS X

## Description
When applying styles to a react component the styles are no longer applied. This was working correctly in Linaria v2.3.1.

This may just be a regression or breaking change, though I cant seem to find a list of breaking changes in v4 or v3 that would cause this.

## Reproducible Demo
https://codesandbox.io/s/linaria-v5-color-forked-snkhtu

**Comment by glassdimlygr** [comment]
I can confirm this. I also saw this in Linaria 3, which prompted me to upgrade to Linaria 4, where the babel parser was broken. One of the guys on our team patched this.

Is it just me or does this basically defeat one of the main purposes of this library?

I would think that this kind of issue would prompt linaria maintainers to consider setting up some tests. We might be up for helping out, but it'd be nice to know that there was some sort of support from core maintainers before we put further resources out there. cc @kcover .

![image](https://user-images.githubusercontent.com/64170940/224163178-09287f73-e0ee-46a3-8c6e-f2987aff1117.png)

**Comment by glassdimlygr** [comment]
To be clear, this bug is when props are passed and interpolated in linaria styles. The props come through as `undefined` no matter if they're destructured or passed directly.

**Comment by Anber** [comment]
Hi @afridley!

There is a problem with your `DemoComp`. Linaria can wrap custom components but it should accept a `className` prop. If you use TypeScript, it even checks compatibility.
<img width="710" alt="The target component should have a className prop" src="https://user-images.githubusercontent.com/148258/234227719-a79bfef0-0024-475d-a1fe-8b996a025238.png">

In your case, Linaria passes generated class to `DemoComp`, but then you don't pass it to the div. The next code should work well:
```
interface Props {
  className?: string; // or LinariaClassName if you want to forbid using non-generated class names
  test: string;
}

const DemoComp: React.FC<Props> = ({ className , test }) => <div className={className}>{test}</div>;
```

**Comment by afridley** [comment]
@Anber This seems to be a regression from version 2. Shouldn't Linaria be adding classname for the user. 

This does seem to work Though I still get that typescript error with a generic. Is their anyway to make that go away while still not explicitly passing classname

https://codesandbox.io/s/linaria-v5-color-forked-rt2r9k?file=/src/App.tsx

**Comment by Anber** [comment]
The specific example does not function in version 2.0 either. If a component is stylable, it must include the `className` prop and, if you wish to use props-based interpolation, the `style` prop. Can you style your DemoComp component by manually adding classes or styles? No, you cannot do so without informing React how to pass those classes and styles to the div.

To pass all potential props through your custom component, you may rewrite it as follows: 
```
const DemoComp: React.FC<Props & JSX.IntrinsicElements["div"]> = ({
  test,
  ...rest
}) => <div {...rest}>{test}</div>;
```
