### ISSUE TITLE
Broken build when using react-redux

### ISSUE THREAD

**Issue by PierreGUI** [callstack/linaria#1226]
## Environment
```json
"@linaria/react": "^4.3.6",
"@linaria/core": "^4.2.8",
"@linaria/webpack-loader": "^4.1.15",
"webpack": "^5.76.1",
```

## Description
Using react-redux and Linaria breaks build: `EvalError: (0 , _batch.setBatch) is not a function in ...`

## Reproducible Demo
https://stackblitz.com/edit/linaria-bug-ekrflt?file=src/index.jsx

**Comment by PierreGUI** [comment]
I tried a whole new setup with Vite, but the build also fails when dealing with react-redux wrapped components:
```
EvalError: (0 , _useSelector.initializeUseSelector) is not a function in
| /node_modules/react-redux/es/index.js
    at Module.evaluate (/node_modules/@linaria/babel-preset/lib/module.js:355:13)
    at require.Object.assign.ensure (/node_modules/@linaria/babel-preset/lib/module.js:295:13)
 ```

**Comment by PierreGUI** [comment]
I've tried to find earlier versions of Linaria or Babel that would compile the reproduction repo.
- I went back all the way to my current configuration: Linaria 2 (supports babel/core 7.13 max) ✅  
- Also, Linaria 3 (airbnb) builds successfully (latest babel) ✅ ([sample repo](https://stackblitz.com/edit/linaria-bug-qpalwz?file=src/index.jsx))
- Starting from Linaria 4, I run into the issue documented above (I tried different babel versions) :x:

**Comment by Anber** [comment]
Hi @PierreGUI!

This https://github.com/callstack/linaria/pull/1237 should fix it.

**Comment by PierreGUI** [comment]
I built Linaria locally and I confirm it fixes my issue. Thank you so much!

**Comment by PierreGUI** [comment]
```json
    "@babel/preset-react": "7.12.13",
    "@linaria/babel-preset": "4.4.5",
    "@linaria/core": "4.2.10",
    "@linaria/shaker": "^4.2.11",
    "@linaria/webpack-loader": "4.1.17",
```

After the latest update, this error came back:
```
ERROR in ./Parent.view.tsx
Module build failed (from ./node_modules/@linaria/webpack5-loader/lib/index.js):

EvalError: (0 , _batch.setBatch) is not a function in
| ./node_modules/react-redux/es/index.js
| ./Component.redux.ts
| ./Parent.view.tsx
    at Module.evaluate (./node_modules/@linaria/babel-preset/lib/module.js:355:13)
    at require.Object.assign.ensure (./node_modules/@linaria/babel-preset/lib/module.js:295:13)
    at Script.runInContext (node:vm:139:12)
    at Module.evaluate (./node_modules/@linaria/babel-preset/lib/module.js:342:14)
```

Unfortunately I'm unable to reproduce it in isolation.

**Comment by PierreGUI** [comment]
@Anber sorry to both you, I can't reopen this issue I but I have a reproduction case now.
It happens only with these version of npm packages, I tried the latest`react-redux` v8 but then new errors appear. I didn't get v8 to work on my codebase yet so that's based on latest v7: https://stackblitz.com/edit/linaria-bug-qyfnwu?file=src%2Findex.jsx

Would really appreciate if you could have a look, thanks 🙏

**Comment by Anber** [comment]
Hi @PierreGUI!

I've found the reason why it doesn't work with v7. I made a fix here https://github.com/callstack/linaria/pull/1274 and will merge it as soon as I fix all tests.

**Comment by PierreGUI** [comment]
Thanks @Anber!
Using the shaker from your branch, my entire codebase builds 🎉
