### ISSUE TITLE
[vite-plugin]: adding new embedded expressions causes errors 

### ISSUE THREAD

**Issue by dlehmhus** [callstack/linaria#1229]
## Environment

- Linaria versions:
    @linaria/core: 4.2.8
    @linaria/react: 4.3.6
    @linaria/vite: 4.2.9
- Bundler (+ version): Vite 4.2.1
- Node.js version: 18.15.0
- OS: macOS Ventura 13.2.1

## Description

When running vite in dev mode, adding a embedded expressions into a linaria component causes an error like the following: 
```sh

[plugin:linaria] /home/projects/vitejs-vite-b813qg/src/App.tsx: The expression evaluated to 'undefined', which is probably a mistake. If you want it to be inserted into CSS, explicitly cast or transform the value to a string, e.g. - 'String(colors.blue)'.
  21 | };
  22 | const Heading = styled.h1`
> 23 | color: ${colors.blue};
     |          ^^^^^^^^^^^
  24 | `;
  25 | _c = Heading;
  26 | function App() { 
```
Restarting the server solves that issue and the embedded expressions will be evaluated correctly.

https://user-images.githubusercontent.com/27899554/227156356-f09ec340-5c34-4ff5-b2d1-dc3c62e52551.mov

## Reproducible Demo

[Stackblitz Example](https://stackblitz.com/edit/vitejs-vite-b813qg?file=src%2FApp.tsx&terminal=dev)

**Comment by dlehmhus** [comment]
A workaround for that issue is to patch the `@linaria/vite` package and remove the transform cache [here](https://github.com/callstack/linaria/blob/2d6dc0b643259a16b53f55e0ff8f547fe5f75cf0/packages/vite/src/index.ts#L151). I noticed that the [webpack plugin](https://github.com/callstack/linaria/blob/2d6dc0b643259a16b53f55e0ff8f547fe5f75cf0/packages/webpack5-loader/src/index.ts#L91) also is not using a cache, maybe for the same reason? Not sure.

**Comment by yudenichaa** [comment]
Same error if class created via css function is re-exported.

```
The expression evaluated to 'undefined', which is probably a mistake. If you want it to be inserted into CSS, explicitly cast or transform the value to a string, e.g. - 'String(iconContainer)'.
  11 |
> 12 |   .${iconContainer} {
     |      ^^^^^^^^^^^^^
```

**Comment by dlehmhus** [comment]
Cannot reproduce the issue anymore. I think #1306 fixed it.
