### ISSUE TITLE
Linaria doesn't work with Vite 4.3 in dev mode

### ISSUE THREAD

**Issue by nstepien** [callstack/linaria#1236]
## Environment

- Linaria version: @linaria/vite@4.2.9
- Bundler (+ version): vite@4.3.1
- Node.js version: 20.0.0
- OS: Win11

## Description

Linaria stopped working after Vite 4.3 in dev mode (the `vite` command).
It works fine with `vite build` + `vite preview`.
vite@~4.2.0 works fine too in either dev or prod builds.
Not sure if this is an issue with linaria or with vite.

This is the error I get:
```
  VITE v4.3.1  ready in 476 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Failed to load url /main_1nkbhq3.css (resolved id: D:/repos/vite-bug/main_1nkbhq3.css) in D:/repos/vite-bug/main.js. Does the file exist?
```

## Reproducible Demo

https://github.com/nstepien/vite-bug/tree/vite43
Clone the repo, checkout the `vite43` branch, `npm ci`
`npm run dev` -> white page
`npm run build` + `npm run preview` -> green page

**Comment by Anber** [comment]
Looks like I need Windows for experiments…

**Comment by houlang** [comment]
I have had the same problem and have now switched to vite@^4.2.0

**Comment by nstepien** [comment]
@Anber let me know if you want me to try something on my windows machine.

**Comment by sorenhoyer** [comment]
I have the same problem. Reverting to 4.2 for now.

**Comment by wenyuanw** [comment]
May be this [PR](https://github.com/callstack/linaria/pull/1263) can fix it. #1263

**Comment by nstepien** [comment]
Looks like this is fixed in the latest version of `@linaria/vite` 👍
