### ISSUE TITLE
Regression: "Using styled tag in runtime is not supported" on valid code

### ISSUE THREAD

**Issue by PierreGUI** [callstack/linaria#1241]
## Environment
```json
"@linaria/react": "^4.3.6",
"@linaria/core": "^4.2.9",
"@linaria/webpack-loader": "^4.1.16",
"@linaria/shaker": "^4.2.10",
"babel-loader": "^9.1.2",
"webpack": "^5.76.1",
```

## Description
This error popped with v4, while it used to work fine with Linaria v2 (I'm migrating from).
Note I have experienced this error both during build and runtime (after fixing build by commenting out code):  
`Uncaught Error: Using the "styled" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly.`

## Reproducible Demo
Still trying to make one. It happens in my huge codebase but isn't easy to reproduce at a small scale.

**Comment by WJCHumble** [comment]
@PierreGUI Have you configured @linaria/babel-preset? If not, you can configure it, refer to here https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md#linariababel-preset

**Comment by PierreGUI** [comment]
Yes. I'm migrating from Linaria 2, and the setup is the same (except for the plugin's name).  
For reference I use these presets:
```json
["@babel/preset-env", {...}],
"@babel/preset-typescript",
["@babel/preset-react", { "runtime": "automatic" }],
"@linaria"
```

**Comment by WJCHumble** [comment]
@PierreGUI Are you using a Windows computer? If yes, please create a new `linaria.config.js` file and add the following configuration:
```javascript
const nodeModulesRegExp = /[\\/]node_modules[\\/]/;

module.exports = {
    rules: [
        {
            action: require.resolve('@linaria/shaker'),
        },
        {
            test: nodeModulesRegExp,
            action: 'ignore',
        },
        {
            test: (filename, code) => {
                if (!nodeModulesRegExp.test(filename)) {
                    return false;
                }

                return /(?:^|\n|;)\s*(?:export|import)\s+/.test(code);
            },
            action: require.resolve('@linaria/shaker'),
        }
    ]
};
```

**Comment by PierreGUI** [comment]
I'm not using a window computer. I tried your rules but it didn't solve the problem.

Worth mentioning the error appears to originate from my own modules, not third parties. In these files I use Linaria, but it looks like the `styled` function and corresponding style is not processed into a CSS file.  
See backtrace:\
```
caught Error: Using the "styled" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly. See https://github.com/callstack/linaria#setup
    at Proxy.<anonymous> (index.mjs:41:1)
    at ./src/components/shared/Icons.tsx (Icons.tsx:8:43)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/components/shared/Toasts.tsx (Texts.tsx:199:2)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/components/abstract/ErrorBoundary.tsx (Content.tsx:71:23)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/components/clients/pages/Header.tsx (UserMenu.view.tsx:181:32)
```

**Comment by WJCHumble** [comment]
@PierreGUI It looks like your Babel Transform is not applied, can you provide your `webpack.config.js` configuration? Or give a minimal Webpack configuration related repo.

**Comment by Anber** [comment]
@PierreGUI, have you managed to reproduce it?

**Comment by PierreGUI** [comment]
@Anber not this one, tbh I forgot about it because I'm blocked by other issues at build time (namely, https://github.com/callstack/linaria/issues/1226#issuecomment-1599111723 and https://github.com/callstack/linaria/issues/1262#issue-1769909932)  
With those fixed, hopefully I'll get a successful build and be able to try again.

**Comment by Clasen00** [comment]
Guys, any updates about this problem? Im facing the same problem when trying render my component react 18 component through jest .

**Comment by Anber** [comment]
Hi @Clasen00,

This error occurs only when `NODE_ENV` is neither `'test'` nor `'production'`. For the `test` environment, it should generate mocked class names. Which version of Linaria do you use?

**Comment by Clasen00** [comment]
@Anber currently Im using a  3.0.0-beta.13 version. 
Could you please suggest to me how I may fix this problem?

**Comment by Anber** [comment]
@Clasen00, you can either add `@linaria` preset to your jest babel config or upgrade Linaria to 5.0

**Comment by lixingjuan** [comment]
Hi, I encountered the same problem, I dropped the linaria related package to 5, and the problem solved
<img width="954" alt="image" src="https://github.com/callstack/linaria/assets/42627664/f8961c0a-bfd4-4b86-99c7-580e58343c0a">

**Comment by Anber** [comment]
Hi @lixingjuan! If you want to use Linaria 6+, you need to replace `@linaria/webpack-loader` with `@wyw-in-js/webpack-loader`. https://github.com/callstack/linaria/blob/master/docs/MIGRATION_GUIDE.md#for-users
