### ISSUE TITLE
`ENOENT` error with Vite in dev mode

### ISSUE THREAD

**Issue by nstepien** [callstack/linaria#1246]
## Environment

- Linaria version: `@linaria/vite@4.2.11`
- Bundler (+ version): `vite@4.3.5`
- Node.js version: 20.1.0
- OS: win11

## Description

When running the Vite dev server, linaria can crash trying to open a file that does not exist yet.
In this case, as I understand it, Vite replaces core-js imports with an optimized file, but linaria tries to open that optimized file before it has been created.
If reload the page, then the optimized file will have been created and linaria won't crash anymore.

## Reproducible Demo

https://github.com/nstepien/vite-bug/tree/vite-linaria-corejs
Clone the repo, checkout the `vite-linaria-corejs` branch, `npm ci`
`npm run dev` -> crash -> reload page in browser -> works

You can reproduce the bug again by deleting `node_modules/.vite/`

**Comment by silviogutierrez** [comment]
I'm having the same issue, seems to be some sort of race condition. But even moving the plugins around did not help.

**Comment by nstepien** [comment]
Still happening, I've updated the branch with the latest version of linaria/vite.

**Comment by layershifter** [comment]
Still happens with v5, needs to be fixed.

**Comment by layershifter** [comment]
Created an issue in Vite to find a proper solution, https://github.com/vitejs/vite/issues/14493.
