### ISSUE TITLE
linaria using SWC to work with next13.4+ and server components

### ISSUE THREAD

**Issue by marianzburlea** [callstack/linaria#1248]
### Describe the Feature
The feature aims to provide support for Linaria's Server Value Cache (SWC) with Next.js 13.4+ and Server Components. This would allow for more efficient rendering of styled components on the server-side, resulting in faster page load times.

### Motivation
Next.js 13.4 introduced Server Components, which is a new way to write server-side code in Next.js. However, using Linaria's CSS-in-JS solution with Server Components can result in duplicate CSS generated on the server, leading to slower server rendering times. By using SWC, Linaria can cache the CSS generated on the server, reducing the amount of CSS generated and improving server rendering performance.

### Possible Implementations
To implement this feature, we can modify Linaria's babel plugin to add support for Server Components and generate the necessary code to use SWC. We can also update the Linaria documentation to include information on how to use SWC with Next.js 13.4+ and Server Components.

### Related Issues
- none

**Comment by cjambrosi** [comment]
@marianzburlea, do you know why this issue was closed? The described problem seems to be important.

**Comment by cjambrosi** [comment]
@marianzburlea, do you know why this issue was closed? The described problem seems to be important
