### ISSUE TITLE
EvalError: Unexpected token 'export' in

### ISSUE THREAD

**Issue by FuncWei** [callstack/linaria#1258]
## Environment
@linaria/core: "4.2.10"
@linaria/react: "4.3.8"
@linaria/babel-preset: "^4.4.5"
@linaria/webpack-loader: "^4.1.17"
nodejs: v16.20.0

- Linaria version: 4
- Bundler (+ version):
- Node.js version: v16.20.0
- OS: mac

## Description
ModuleBuildError: Module build failed (from ./node_modules/@linaria/webpack-loader/lib/index.js):
/node_modules/@linaria/babel-preset/lib/module.js:355
      throw new EvalError(`${e.message} in${callstack.join('\n| ')}\n`);
      ^

EvalError: Unexpected token 'export' in
| /node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js
| /node_modules/@stencil/core/internal/client/index.js
|/node_modules/@tarojs/components/dist/components/taro-view-core.js
| /node_modules/@tarojs/components/dist/components/index.js
| /node_modules/@tarojs/components/lib/react/components.js
| /node_modules/@tarojs/components/lib/react/index.js
| /src/pages/linariaDemo/index.jsx
    at runMicrotasks (<anonymous>)
    at runMicrotasks (<anonymous>)

config:

// linaria 配置详见 https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md#options
module.exports = {
  classNameSlug: (hash, title, { dir }) => (
    process.env.NODE_ENV === 'production'
      ? `${hash}` // .abcdef
      : `${dir}_${title}_${hash}` // .linariaDemo_Title_abcdef
  ),

  variableNameSlug:
    process.env.NODE_ENV === 'production'
      ? 'default' // -abcdef-0
      : '[componentName]-[source]-[valueSlug]-[index]', // --Title-_props_____props_color-abcdef-0

  rules: [
    {
      action: require.resolve('@linaria/shaker'),
    },
    {
      test: /[\\/]node_modules[\\/](?!@tarojs)/,
      action: 'ignore',
    },
    {
      test: (filename, code) => {
        if (!/[\\/]node_modules[\\/]/.test(filename)) {
          return false;
        }

        return /\b(?:export|import)\b/.test(code);
      },
      action: require.resolve('@linaria/shaker'),
    },
  ],
};

**Comment by chentsulin** [comment]
Linaria seems currently not support ESM in module evaluation.

**Comment by chentsulin** [comment]
@Anber Do you have any idea how to implement or workaround this issue?

**Comment by chentsulin** [comment]
Just found a workaround which don't exist in v4: https://github.com/callstack/linaria/commit/d6491625ba0f92e3db7819f91990e57bd065031b

However, this workaround only handle `@babel/runtime/helpers/esm/` but leave other ESM packages.

**Comment by layershifter** [comment]
Hey, please check latest versions i.e. v5. I was able to use `@linaria/core` & `@tarojs/components` without any issue, https://stackblitz.com/edit/stackblitz-starters-tdzt5d.

If the problem still happens, please open a new issue and provide a reproduction case.
