### ISSUE TITLE
Cannot read properties of null (reading 'declarations')

### ISSUE THREAD

**Issue by PierreGUI** [callstack/linaria#1262]
## Environment
- Linaria version:
    - @linaria/core 4.2.10
    - @linaria/shaker 4.2.11
    - @linaria/react 4.3.8
- Bundler: webpack 5.75
- Node.js version: v16.14.2
- OS: MacOS 13.3.1

## Description
When migrating my codebase to the latest Linaria, I encounter this error:
```
Cannot read properties of null (reading 'declarations')
    at NodePath._getKey (@babel+traverse@7.22.5/node_modules/@babel/traverse/lib/path/family.js)
```

I was able to narrow it down to one function, which I've included in my repro below. I hope it makes sense to you and that you'll be able to fix it.

## Reproducible Demo
https://stackblitz.com/edit/linaria-bug-4yqklk?file=src%2Futils%2Findex.ts

**Comment by Anber** [comment]
I am ashamed that it took so long :)

**Comment by PierreGUI** [comment]
@Anber thanks a lot! Latest build indeed seems to fix the problem 👍
