### ISSUE TITLE
Need pointers to support css prop in React elements

### ISSUE THREAD

**Issue by brijeshb42** [callstack/linaria#1275]
## Describe the feature

This feature will add support for inline css and props passed to components. For ex,

```tsx
<Box marginTop={2} color="red" css={{backgroundColor: "blue",...}} />
```

I would like to be able to get access to the `Box` AST node along with it's props (with evaluated values) in an external processor (similar to the `styled` processor) so that I can construct the css class similarly and also modify the element to something like

```tsx
<Box css={"class-1 class-2"} />
```

## Motivation

Most of the runtime css-in-js libraries like Emotion/Stitches support css written in this way and I would like the same.

## Possible implementations

Right now, `linaria`'s babel plugin only traverses identifiers which makes supporting this impossible. I figure we could introduce a JSXOpeningElement/JSXSelfClosingElement visitor [here](https://github.com/callstack/linaria/blob/master/packages/babel/src/plugins/preeval.ts#L86) and do the same thing as identifier where the processor is passed information about the Element and it's props. 

I would be happy to contribute this feature back to Linaria. Just need pointers on where in code to get started.

**Comment by Anber** [comment]
Hi @brijeshb42 
I'm afraid this is not possible because to pass props to a processor, you have to figure out which processor should be used. It can be done for functions and template tags by analyzing the package that provides those functions and template tags. However, I don't know how we can link a random JSX attribute with any processor

**Comment by brijeshb42** [comment]
How about if we ignore the direct props but if there is a `css` or `sx` prop? We can identify the tag from the prop name.

**Comment by Anber** [comment]
Any component can have a `css` or `cx` prop, or any other similar prop. Therefore, we cannot simply search for any identifier with such a name and perform transformations, as it would disrupt existing code. Additionally, an explicit import is required to specify the location of the associated processor, which is the first issue.

Another challenge arises when trying to make it compatible with TypeScript, as it entails patching react-types.
