### ISSUE TITLE
Readable CSS class names

### ISSUE THREAD

**Issue by MazeChaZer** [callstack/linaria#1291]
## Describe the feature

I would like to allow developers to specify the CSS class names themselves, if they want to, instead of the generated hashes.

### Generated class names

```jsx
<p className={css`font-size: 16px;`}>foo</p>
```

would produce

```html
<p class="c1e86q5z">foo</p>
```
```css
.c1e86q5z {
  font-size: 16px;
}
```

### Explicitely specified class names

```jsx
<p className={cssClass("content")`font-size: 16px;`}>foo</p>
```

would produce

```html
<p class="content">foo</p>
```
```css
.content {
  font-size: 16px;
}
```

This would preserve all the cool features of Linaria but make the class names readable. And Linaria could still assure unique class names across the project by allowing each class to be defined only once:

```jsx
<>
  <p className={cssClass("content")`font-size: 16px;`}>foo</p> {/* Okay */}
  {/* … */}
  <p className={cssClass("content")`font-size: 24px;`}>foo</p> {/* Compilation error! */}
</>
```

## Motivation

I want to build a static website and Linaria is perfect for that, because it gives all the ergonomics of CSS-in-JS without actually requiring JavaScript at runtime :) But I would prefer to have proper readable CSS class names, so that visitors of my site can easily customize their viewing experience with userstyles, content blockers or any other addon/script. Furthermore, this could ease debugging by making it easier to see which elements in the devtools inspector match which elements in the source code (there are already CSS sourcemaps, but it can still improve orientation).

## Possible implementations

In addition to the `css` templates, I would introduce an new tag function `cssClass : (className: string) => (strings, ...exprs) => LinariaClassName` that accepts the CSS class name as a parameter. This parameter is evaluated at compile time and used instead of the generated hash.

## Related Issues

No related issues.

**Comment by Anber** [comment]
This is a highly specific use case, and I doubt it will be included in the core library. However, you can easily create your custom tag function to achieve this functionality. Here's a step-by-step guide:

1. Define a new function called `cssClass`.

2. Create a new processor by extending `CssProcessor` from `@linaria/core`. In the constructor of the processor, extract the `cssClass` argument from `params`, and assign its value to `this.className` and `this.slug`.

3. Link the `cssClass` function with the newly created processor by adding the following code to your `package.json` file:

```json
"linaria": {
  "tags": {
    "css": "./dist/processors/css.js"
  }
}
```

Feel free to ask questions!

**Comment by Anber** [comment]
Or, if you want to use evaluated class names, you can save the first CallParam from `param` to some field and override the `extractRules` method, where you will have access to the evaluated value of that param. Atomic does something similar with generated class names https://github.com/callstack/linaria/blob/master/packages/atomic/src/processors/css.ts#L24

**Comment by MazeChaZer** [comment]
@Anber yeah that's understandable. Thank you for the detailed guidance in how to implement this! And cool to see how customizable Lineria is :)
