### ISSUE TITLE
`The expression evaluated to 'undefined'.` occurs recently.

### ISSUE THREAD

**Issue by tsukuisan** [callstack/linaria#1300]
## Environment

- Linaria version: 4.2.6
- Next.js version: 13.1.6 
- Node.js version: 16.15.1
- Yarn version: 1.22.19
- OS: macOS Ventura 13.2.1

## Description

When I compile my project, this error message occurs. 
`SyntaxError: ***.tsx: The expression evaluated to 'undefined', which is probably a mistake.`
This project was going well until the recent update, but it doesn't go well after then.

## Reproducible Demo

1. Clone this project.
https://github.com/tsukuisan/Linaria_error
2. Run `yarn install`.
3. Run `yarn run build`.

**Comment by Anber** [comment]
Hi @tsukuisan!

Thank you for the repo! Fixed.
