### ISSUE TITLE
The expression evaluated to 'undefined'

### ISSUE THREAD

**Issue by GabbeV** [callstack/linaria#1304]
## Environment

Windows 10 and and WSL on windows 10
node 18.12.1
npm 9.6.0

## Description

Linaria fails with error "The expression evaluated to 'undefined', which is probably a mistake."

## Reproducible Demo

There seem to be some race condition as it randomly works some times and sometimes not.
Small seemingly irrelevant changes can also cause it to error more often or less often.
If you can't reproduce I might be able to find a more reliable example.

[linaria-bug.zip](https://github.com/callstack/linaria/files/12176918/linaria-bug.zip)

```
npm i
npm run build
```

## My own investigation

Adding a couple of console.log statements into the linaria code i saw that the values Map will be { "_exp" => undefined } if Foo is evaluated before Bar.

**Comment by Anber** [comment]
Thank you @GabbeV!
Your demo was extremely helpful! I hope now I've nailed that bug.
