### ISSUE TITLE
Add to CSS in JS playground

### ISSUE THREAD

**Issue by satya164** [callstack/linaria#133]
https://github.com/dschau/css-in-js-playground

**Comment by Tushkiz** [comment]
Someone working on this? I would like to experiment 👨‍🔬

**Comment by satya164** [comment]
AFAIK no one is doing it right now. Feel free :)

**Comment by Tushkiz** [comment]
Preview: https://deploy-preview-74--css-in-js-playground.netlify.com
PR: [css-in-js-playground/pull/74](https://github.com/DSchau/css-in-js-playground/pull/74)

@satya164 does that look good?

**Comment by satya164** [comment]
Looks great. Thank you so much for doing this ❤️

**Comment by zamotany** [comment]
@Tushkiz can you update the readme to include the link to css-in-js-playground w/ linaria and **add yourself to contributors list**?

**Comment by Tushkiz** [comment]
Yup, doing it.

**Comment by Tushkiz** [comment]
@zamotany also adding `all-contributors-cli` to npm scripts, is that fine?

**Comment by thymikee** [comment]
If it makes contributing easier, sure :)

**Comment by Tushkiz** [comment]
Done #141

**Comment by zamotany** [comment]
Merged #141.
Thanks @Tushkiz for contribution 👍 .
