### ISSUE TITLE
Invalid CSS: Space inserted after function interpolation

### ISSUE THREAD

**Issue by PierreGUI** [callstack/linaria#1368]
## Environment
- Linaria version: 5.0.2/5.0.3
- Bundler (+ version): Webpack 5

## Description
1. Use a function interpolation
2. Write CSS unit after the function
3. Use variable interpolation on the next line
:x: There's a space between value and unit (invalid CSS)

Example:
```jsx
export const FS = 12;
const getWidth = () => 10;

const H1 = styled.h1`
  width: ${getWidth}px;
  font-size: ${FS}px;
`;
```

Produces ->
<img width="228" alt="image" src="https://github.com/callstack/linaria/assets/1013904/8db729af-1a66-464d-b41b-1a6dd03bde78">

## Reproducible Demo
https://stackblitz.com/edit/linaria-bug-o9hmgr?file=src%2FTitle.tsx

**Comment by layershifter** [comment]
@PierreGUI the repro is partially broken:

<img width="367" alt="image" src="https://github.com/callstack/linaria/assets/14183168/7166c8b2-c0ce-4bb4-8e92-25bf4d8b8032">

However, usage of the proper version does not fix the bug :) It's present.

---

The `transform()` returns in result following:

```
result.rules {
  '.hhnsy8v': {
    cssText: '\n  width: var(--hhnsy8v-0);\n  font-size: 12\n                  px;\n',
    className: 'hhnsy8v',
    displayName: 'H1',
    start: { line: 10, column: 11, index: 220 }
  }
}
```

I traced it to the following:

https://github.com/callstack/linaria/blob/e25e91ffb1187708680b97b06888adde7291b4d9/packages/tags/src/utils/templateProcessor.ts#L129-L130

- `toCSS()` returns `12` (`string`)
- `stripLines()` adds a newline that is considered as " "

This happens because:

https://github.com/callstack/linaria/blob/e25e91ffb1187708680b97b06888adde7291b4d9/packages/tags/src/utils/stripLines.ts#L14-L20

As `stripLisnes()` gets `{ start: { line: 11, column: 10 }, end: { line: 12, column: 18 } }` as `loc` input.

**Comment by agriffis** [comment]
@layershifter I have not dug into this personally, just curious if you continued down this debugging journey to figure out why `stripLines` receives those different start/end lines. It seems like they should be the same, given the input?

**Comment by agriffis** [comment]
Oh, here it is:

https://github.com/callstack/linaria/blob/e25e91ffb1187708680b97b06888adde7291b4d9/packages/tags/src/utils/templateProcessor.ts#L46

`lastTemplateElementLocation` is only set for template elements. It isn't updated for expressions. As a result, it's still reflecting `px;\n  font-size:` which started on the previous line.

Something like this should do the trick, I think:

```diff
diff --git a/packages/tags/src/utils/templateProcessor.ts b/packages/tags/src/utils/templateProcessor.ts
index 6de8f317..a4dab8cc 100644
--- a/packages/tags/src/utils/templateProcessor.ts
+++ b/packages/tags/src/utils/templateProcessor.ts
@@ -66,6 +66,8 @@ export default function templateProcessor(
         : { line: end.line, column: end.column + 1 },
     };

+    lastTemplateElementLocation = ex.loc!;
+
     const value = 'value' in item ? item.value : valueCache.get(item.ex.name);

     // Is it props based interpolation?
```

**Comment by agriffis** [comment]
Actually, I'm not sure what the point of `lastTemplateElementLocation` is at all. This change is working for me:

```diff
diff --git a/packages/tags/src/utils/templateProcessor.ts b/packages/tags/src/utils/templateProcessor.ts
index 6de8f317..a1aed9ac 100644
--- a/packages/tags/src/utils/templateProcessor.ts
+++ b/packages/tags/src/utils/templateProcessor.ts
@@ -37,30 +37,24 @@ export default function templateProcessor(
   let cssText = '';
 
   let item: TemplateElement | ExpressionValue | undefined;
-  let lastTemplateElementLocation: SourceLocation | null | undefined;
   // eslint-disable-next-line no-cond-assign
   while ((item = template.shift())) {
     if ('type' in item) {
       // It's a template element
       cssText += item.value.cooked;
-      lastTemplateElementLocation = item.loc;
       continue;
     }
 
     // It's an expression
     const { ex } = item;
 
-    const { end } = ex.loc!;
+    const { start, end } = ex.loc!;
     const beforeLength = cssText.length;
 
     // The location will be end of the current string to start of next string
     const next = template[0] as TemplateElement; // template[0] is the next template element
     const loc = {
-      // +1 because an expression location always shows 1 column before
-      start: {
-        line: lastTemplateElementLocation!.end.line,
-        column: lastTemplateElementLocation!.end.column + 1,
-      },
+      start,
       end: next
         ? { line: next.loc!.start.line, column: next.loc!.start.column }
         : { line: end.line, column: end.column + 1 },
```

and it also fixes the broken atomic css test (which is the same effective bug)

**Comment by agriffis** [comment]
This might actually be the same as https://github.com/callstack/linaria/issues/1141

**Comment by agriffis** [comment]
I just added a PR for this, see #1374
