### ISSUE TITLE
[Linaria 6.2] Cannot create property 'message' on symbol 'Symbol(skip)'

### ISSUE THREAD

**Issue by PierreGUI** [callstack/linaria#1407]
## Environment
I updated Linaria & wyw-in-js from previous latest to new latest:  
- "webpack": "^5.89.0",
- "@babel/core": "^7.24.4",
- "@linaria/react": "^6.2.0",
- "@wyw-in-js/babel-preset": "^0.5.3",
- "@wyw-in-js/webpack-loader": "^0.5.3",

## Description
The only change to my code is the update of both packages, breaks the build with the following error:  
```
 ERROR in ./src/components/shared/InfiniteList.view.tsx
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  TypeError: /Users/pierre/Chordify/chordify-front/client/src/components/shared/InfiniteList.view.tsx: Cannot create property 'message' on symbol 'Symbol(skip)'
      at run (/Users/pierre/Chordify/chordify-front/client/node_modules/@babel/core/lib/transformation/index.js:27:15)
```

**Comment by Anber** [comment]
It happens when `@wyw-in-js/webpack-loader` and `@linaria/react` use different versions of `@wyw-in-js/processor-utils`. Could you please check the version of `@wyw-in-js/processor-utils`?

**Comment by PierreGUI** [comment]
yes you're right:
```
├─┬ @linaria/core@6.1.0
│ └── @wyw-in-js/processor-utils@0.4.1
├─┬ @linaria/react@6.2.0
│ └── @wyw-in-js/processor-utils@0.5.3
└─┬ @wyw-in-js/babel-preset@0.5.3
  └─┬ @wyw-in-js/transform@0.5.3
    └── @wyw-in-js/processor-utils@0.5.3
```

**Comment by Anber** [comment]
I messed up with the release yesterday. It should be good now.

**Comment by PierreGUI** [comment]
thanks, it builds again!

**Comment by glassdimlygr** [comment]
Here's what you need to do to fix this:
Run `yarn info @linaria/core` or equivalent. 

I see:
```
@linaria/core@npm:6.2.0
   ├─ Version: 6.2.0
   │
   └─ Dependencies
      └─ @wyw-in-js/processor-utils@npm:0.5.3 → npm:0.5.3
```

Now, install all of wyw deps from `0.5.3`.

I had previously made the mistake of upgrading wyw directly.

If you have nested workspace dependencies, then if using yarn berry you can specify them in `resolutions` as well as specifying them normally in your `package.json`.
```
  "resolutions": {
    "@wyw-in-js/babel-preset": "0.5.3",
    "@wyw-in-js/transform": "0.5.3",
    "@wyw-in-js/webpack-loader": "0.5.3",
    "@linaria/babel-preset": "5.0.3",
    "@wyw-in-js/rollup": "0.5.3",
    "@linaria/core": "6.2.0",
    "@linaria/react": "6.2.1",
    "@linaria/shaker": "5.0.3",
    "@linaria/stylelint": "6.2.0",
   "@wyw-in-js/processor-utils": "5.0.3",
    "linaria": "6.2.0"
  },
```
