### ISSUE TITLE
PostCSS support

### ISSUE THREAD

**Issue by FezVrasta** [callstack/linaria#142]
**Do you want to request a *feature* or report a *bug*?**
feature

**Description**

It would be cool to be able to use PostCSS (included PostCSS syntaxes like SugarSS), is this in the roadmap?

**Comment by thymikee** [comment]
Yup, we have that in mind. Ideally we would like to provide any css preprocessor, with Stylis as a default.

**Comment by hedgepigdaniel** [comment]
Is there any benefit of including this in linaria when one could just as easily use a webpack loader applied to css files, e.g. `postcss-loader`?
