### ISSUE TITLE
Test and upgrade to Babel 7

### ISSUE THREAD

**Issue by zamotany** [callstack/linaria#168]

**Comment by kylpo** [comment]
Babel 7 has been officially released (woohoo!). Curious if there are plans to get linaria on Babel 7 soon.

**Comment by zamotany** [comment]
Before any decision is made, we need to make sure that the changes to plugin API still allows us to achieve what we want. When investigating rewrite to Babel 7 beta, we've come to the point when we couldn't proceed further, because the API we used was removed and there was no clear workaround. We're also thinking about rewriting Linaria as a standalone tool, without Babel, so we have more control.

**Comment by kylpo** [comment]
Thanks for your reply, @zamotany. Linaria is too important for me to lose, so I'll just be sticking with Babel 6. 

A standalone tool would be great, but boy does that sound like a lot of work on your end. Thanks for your work on this!

**Comment by satya164** [comment]
Babel 7 is used in https://github.com/callstack/linaria/tree/next
