### ISSUE TITLE
Minify class names in production

### ISSUE THREAD

**Issue by steadicat** [callstack/linaria#175]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
In production, generated class names are of the form `_{variableName}__{hash}`, same as in development mode.

**What is the expected behavior?**
They should just be `_{hash}`. This will save some bytes and look cleaner, by not leaking internal variable names into the generated markup and CSS. At least make this an option.

**Comment by zamotany** [comment]
For assignee:
This should be configurable as a babel preset options like `minifyClassnames` and should generate short hash (6 chars should be fine) from `_{variableName}__{hash}` to `ln{hash}` where `ln` is our prefix.

The code should probably be done here https://github.com/callstack/linaria/blob/master/src/babel/preval-extract/prevalStyles.js#L63
