### ISSUE TITLE
Properly resolve `url(...)` in style strings

### ISSUE THREAD

**Issue by satya164** [callstack/linaria#182]
## What's broken

Say you have the following file structure:

```sh
├── .linaria-cache
├── src
│   ├── components
│   │   └── App.js
│   └── assets
│       └── bat.png
└── .babelrc
```

Now you write following in `App.js`:

```js
const logo = css`
  background: url(../assets/bat.png);
`;
```

This won't work, because the generated CSS file will be at `.linaria-cache/src/components/App.css`, and when resolving `../assets/bat.png`, webpack will look relative to the the generated file.

## How to fix

We can write a `stylis` plugin which replaces relative paths in `url` with the correct path relative to the generated file.

**Comment by zamotany** [comment]
I think we can calculate the correct path without stylis

**Comment by satya164** [comment]
@zamotany how? the `url` statements will be resolved by webpack and `style-loader`. we don't have any control over how it's resolved.

**Comment by zamotany** [comment]
But with this:
```js
const logo = css`
  background: url(${require(../assets/bat.png)});
`;
```
we can calculate the correct path.

Tho you're right, the solution with stylis will work for both cases

**Comment by morajabi** [comment]
It's interesting! Do you want me to give this a hand? 🙌
