### ISSUE TITLE
Include example of stylelint doesn't work

### ISSUE THREAD

**Issue by croszatycki** [callstack/linaria#184]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In version 0.4.1 you didn't attached `stylelint-config.js`
```
> stylelint "src/**/*.jsx" "src/**/*.scss"

Error: Could not find "linaria/stylelint-config". Do you need a `configBasedir`?
    at module.exports (./node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at module.exports (./node_modules/stylelint/lib/utils/getModulePath.js:18:11)
    at loadExtendedConfig (./node_modules/stylelint/lib/augmentConfig.js:186:22)
    at resultPromise.then.resultConfig (./node_modules/stylelint/lib/augmentConfig.js:161:16)
    at <anonymous>
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
`yarn add linaria --dev`
prepare .stylelintrc file
```json
{
  "extends": [
    "linaria/stylelint-config"
  ]
}
```
exec `stylelint` 

**What is the expected behavior?**
Missing lint files in release version

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**

**Temporary fix:**
```json
{
  "processors": ["stylelint-processor-styled-components"],
  "syntax": "scss",
  "extends": ["stylelint-config-recommended"],
  "rules": {
    "at-rule-name-case": "lower",
    "unit-case": "lower",
    "no-empty-source": null,
    "no-extra-semicolons": null
  }
}

```

**Comment by zamotany** [comment]
Fixed in `0.4.2`
