### ISSUE TITLE
`inject` not working on Windows

### ISSUE THREAD

**Issue by Trancever** [callstack/linaria#194]
**Do you want to request a *feature* or report a *bug*?**
- report a bug

**What is the current behavior?**
- Error while running website dev-server on Windows 10

![error-linaria](https://user-images.githubusercontent.com/18584155/34949056-40936f38-fa0f-11e7-9b65-5cbe93185e71.PNG)

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
- It happens on master branch of linaria v0.5.0

Steps to reproduce:
- clone the repo
- cd website
- yarn && yarn run start

**What is the expected behavior?**
- There should be no error while running website dev-server on Windows

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**
- yarn v1.3.2
- npm v5.6.0
- linaria v0.5.0
- node v8.9.3

**Comment by zamotany** [comment]
Temporary workaround; use [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

**Comment by zamotany** [comment]
https://github.com/callstack/linaria/blob/763f9a79a30f428ec6bf2da0ca197e1b432bb44f/src/loader.js#L25

**Comment by zamotany** [comment]
@Trancever do you want to contribute??

**Comment by satya164** [comment]
Should be fixed
