### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by zamotany** [callstack/linaria#197]

**Comment by dumaron** [comment]
Hi, any news on this? 
Can you tell me what need to be done in order to help?

**Comment by thymikee** [comment]
To make that happen we'll need to migrate to Babel 7 and make sure all works with `@babel/preset-typescript`

**Comment by dumaron** [comment]
This, however, will not help the ones working on projects bootstrapped with `create-react-app-typescript`, right? This will only support typescript if transpiled from babel?

**Comment by thymikee** [comment]
No, it won't work. Linaria is a Babel preset. AFAIK TypeScript doesn't allow you to transform its AST like Babel does. However, with Babel 7 you should be able to technically pre-compile your app (typescript and linaria presets required) before it goes to `tsc`.

**Comment by MartinJohns** [comment]
> AFAIK TypeScript doesn't allow you to transform its AST like Babel does.

TypeScript has support for transformers: Microsoft/TypeScript#13764

**Comment by resir014** [comment]
> To make that happen we'll need to migrate to Babel 7 and make sure all works with @babel/preset-typescript

Not only that, but a type declaration (`.d.ts`) also needs to be provided.

**Comment by satya164** [comment]
cc @Esemesek, our ts hero

**Comment by satya164** [comment]
@resir014 can you check #263 if it helps?

**Comment by satya164** [comment]
Can this be closed? We now use Babel 7 and also ship TypeScript definitions.

**Comment by zamotany** [comment]
For TS support: you need to use babel 7 with typescript preset.

**Comment by ShanonJackson** [comment]
Fucking around with linaria on weekends in preparation for when we stop supporting IE11 in production and i can swap from styled-components. Making sure the SSR all works etc etc i'm finding the lack of documentation for typescript support basically null, after reading the documentation it's starting to look like i'm literally forced to stop using awesome-typescript-loader (in dev) and ts-loader (in prod build for multi-threading with happypack which comes in slightly faster than ATL), just to use linaria and instead reconfigure my entire application to use babel.

Is there a workaround where i can configure the SSR to work without using babel and not get the "Error using the "styled" tag in runtime is not supported....."

**Comment by zamotany** [comment]
Unfortunately no, TypeScript compiler do not provide public API for writing custom transformers, so we cannot support `tsc`. Currently, there's no way to use linaria without babel.

**Comment by steadicat** [comment]
FWIW, here's the issue that tracks adding support for custom transformers to the TypeScript compiler: https://github.com/Microsoft/TypeScript/issues/14419

**Comment by ShanonJackson** [comment]
@zamotany Anychance in the intermediatory period we could have some cool babel cats out there setup a typescript example setup of both frontend / backend Typescript + Babel + Linaria? Spent about 8 hours now trying to configure something that will work but as someone with little babel experience (and someone who finds the babel documentation and plugin system confusing) it would be great to have an example template which shows the two running together.

(Backend with Linaria/Typescript/Babel for SSR).

**Comment by geakstr** [comment]
Hi and thanks for linaria! In our project we use typescript namespaces, so we can't move to @babel/preset-typescript (it doesn't support namespaces). It would be really cool to have linaria worked with ts-loader. Is there any chance?

**Comment by chrisabrams** [comment]
@geakstr have you tried running babel in front of ts-loader?

**Comment by geakstr** [comment]
@chrisabrams yes, from webpack config:

```
{
  test: /\.(ts|tsx)$/,
  include: paths.appSrc,
  use: [
    {
      loader: require.resolve("babel-loader")
    },
    {
      loader: require.resolve("linaria/loader"),
      options: {
        sourceMap: process.env.NODE_ENV !== "production"
      }
    },
    {
      loader: require.resolve("ts-loader"),
      options: {
        // disable type checker - we will use it in fork plugin
        transpileOnly: true,
        experimentalWatchApi: true
      }
    }
  ]
}
...
{
  test: /\.s(c|a)ss$/,
  use: [
    {
      loader: MiniCssExtractPlugin.loader,
      options: {
        hmr: process.env.NODE_ENV !== "production"
      }
    },
    {
      loader: require.resolve("css-loader"),
      options: {
        importLoaders: 2,
        sourceMap: true,
        modules: {
          mode: "local",
          localIdentName: "[name]_[local]_[hash:base64:5]"
        }
      }
    },
    {
      loader: require.resolve("postcss-loader"),
      options: {
        sourceMap: true,
        // Necessary for external CSS imports to work
        // https://github.com/facebookincubator/create-react-app/issues/2677
        ident: "postcss",
        plugins: () => [
          require("postcss-flexbugs-fixes"),
          autoprefixer({
            flexbox: "no-2009"
          })
        ]
      }
    },
    {
      loader: require.resolve("sass-loader"),
      options: {
        sourceMap: true
      }
    }
  ]
}
```

.babelrc
```
{
  "presets": ["@babel/preset-env", "@babel/preset-react", "linaria/babel"]
}
```

In runtime: `Error: Using the "css" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly.`

**Comment by geakstr** [comment]
Wow, got it work! The problem was `"module": "commonjs"/"target": "es5"` in `tsconfig.json`. With this config `linaria/loader` gets already transpiled imports. Changed to `"module": "esnext"/"target": "esnext"` - all works fine. That's super intuitive and it should be reflected somewhere in the docs. Let me prepare PR when I have a chance.

**Comment by BasixKOR** [comment]
Hi, It seems like `ts-loader` supports custom transformer using their API. Can we use `ts-loader` instead of `babel-loader` with this API?

Related documentation: https://github.com/TypeStrong/ts-loader#getcustomtransformers

**Comment by Jack-Works** [comment]
Hello, this project looks awesome but it requires Babel... I have rich experience in writing TypeScript transformers, for example [react-refresh-typescript](https://github.com/Jack-Works/react-refresh-transformer/tree/main/typescript) to the official `react-refresh/babel` transformer.

I'd like to write a TypeScript version so I (and other people) can use this project with ts-loader. But if I made that, will this project accept the PR?

**Comment by Anber** [comment]
Hi @Jack-Works

We will. But I bet that it wouldn't be simple :)

**Comment by Anber** [comment]
@Jack-Works If you really want to try, you can create an issue and I will help you with planning and implementation, because such a task requires a few new abstractions in our existing code base.

**Comment by Jack-Works** [comment]
I'd like to introduce [jest-file-snapshot](https://www.npmjs.com/package/jest-file-snapshot) and let test cases become a folder on their own (so I can share the test with TypeScript after I start coding).

An example in my project:
[test files in a folder](https://github.com/Jack-Works/react-refresh-transformer/tree/main/tests)
[snapshot for TypeScript transformer](https://github.com/Jack-Works/react-refresh-transformer/tree/main/typescript/__snapshots__)
[test file that read those test files for TypeScript transformers](https://github.com/Jack-Works/react-refresh-transformer/blob/main/typescript/test.ts)

Is this ok? @Anber

**Comment by Anber** [comment]
Sounds good to me.
