### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by zamotany** [callstack/linaria#198]

**Comment by s-panferov** [comment]
I would like to take care of this, but there is something I don't understand in the current codebase: https://github.com/callstack/linaria/blob/master/src/tools/webpack-loader.js#L108-L124

Why do we need to iterate through the parent modules to do something? Isn't it contradicts with the webpack's loader logic?

**Comment by s-panferov** [comment]
@satya164 personally I hate `styled-components` approach, and I really think that just `css` helper is enough for everything. Please please please add it to the new library as-is in the current `linaria`.

**Comment by satya164** [comment]
Yes, I want to support both types of usage, probably 2 packages, but the core can be there same.

**Comment by zamotany** [comment]
Thia is an case when you change something which is used by `css` somewhere else (it's a parent module). Let's say you have:
```js
// Module A.js
import { css } from 'linaria';
import someHelper from './somewhere';

const someStyles = css`
  color: ${someHelper('someValue')};
`;
```
When you make changes to `someHelper` implementation, thd results might change so the loader has to rebuild each module that is using `someHelper`, each module that is using `A.js` (because it might got changed) and so on. This of course has performance downsides, but I'm not aware of any better solution and in most cases performance degradation is unnoticeable.

**Comment by s-panferov** [comment]
@zamotany I believe that `https://webpack.js.org/api/loaders/#this-adddependency` handles this better.

**Comment by zamotany** [comment]
As far as a remember, it didn't handled few cases. But hey, @s-panferov if you want, please give it a shot 😉

**Comment by satya164** [comment]
I just added `this.addDependency` in the loader here and it seems to work: https://github.com/callstack/linaria-styled/blob/873675c52c38c109376859a5c6281209200d61ba/src/loader.js#L71

**Comment by satya164** [comment]
Supported in https://github.com/callstack/linaria/tree/next
