### ISSUE TITLE
Option to not emit css content, keep only class name in js

### ISSUE THREAD

**Issue by namnm** [callstack/linaria#203]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
Not sure if we have this feature already, now css is generated to output dir or in webpack bundles, but I want only class name from the block and ignore the css content.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**
Option to not emit css content, only transpile the css block to a desired class name.

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**

**Comment by zamotany** [comment]
Have you tried `extract: false` option? https://github.com/callstack/linaria/blob/master/docs/BABEL_PRESET.md#options

**Comment by namnm** [comment]
Look like I missed that!
