### ISSUE TITLE
Feature Request: avoid hash clashes

### ISSUE THREAD

**Issue by chrisbateman** [callstack/linaria#208]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Hashes are generated from the filename, which can lead to clashes in the following cases:
- 2 different versions of the same library where the styles changed between versions (this is my primary use case)
- 2 separate libraries that both use Linaria and have the same variable names in files with the same name (e.g. `styles.js`).

**What is the expected behavior?**
Possible solutions:
- Always generate hashes based on the styles (I did see the discussion in #147 so I'm not sure how feasible you think this)
  - FWIW I believe this is what Emotion does
- Provide an option in `linaria/babel` to customize the classname generation, which puts responsibility on the user to ensure uniqueness

p.s. Sorry to keep opening issues – I think this is the last one! Would be happy to help contribute if I can.

**Comment by satya164** [comment]
You might wanna check my RFC regarding publishing libraries to NPM: https://github.com/callstack/linaria/issues/178

**Comment by satya164** [comment]
We could also default to `[name]@[version]~[filename]` for hashes, and allow customizing it.

**Comment by zamotany** [comment]
I'm going to close this one in favour of #299
