### ISSUE TITLE
Wrong css class name output

### ISSUE THREAD

**Issue by namnm** [callstack/linaria#209]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
The class names generated in css file are different with the ones in js file

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
https://github.com/namnm/linaria-test

**What is the expected behavior?**
The class names generated in css file should be the same with the ones in js file

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**

.babelrc
```js
{
  presets: [
    ['linaria/babel', { minifyClassnames: true }],
  ],
}
```
Linaria: `0.5.0`
Node: `8.11.1`
npm: `6.1.0`

**Comment by zamotany** [comment]
With new solution we use for linaria (on `next` branch) is cannot happen again.
