### ISSUE TITLE
[next] Incorrect import paths

### ISSUE THREAD

**Issue by ivan-aksamentov** [callstack/linaria#216]
**Do you want to request a *feature* or report a *bug*?**
🐞 bug

**What is the current behavior?**

On `linaria` `next` branch (current commit `ff47c99cab96c1803ab452018a69b2903a382367`) build fails with:

```
ERROR in ./src/index.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: Cannot find module 'lib/babel'
<stack trace omitted, not relevant>
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

```
git clone https://github.com/ivan-aksamentov/reactlandia-bolerplate-lite.git -b feature/linaria
cd reactlandia-bolerplate-lite
npm install
npm run dev

```

**What is the expected behavior?**
build succeeds

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**

`babel.config.js`:
```
module.exports = {
  'presets': [
    '@babel/preset-env',
    '@babel/preset-react',
    ['linaria/babel', { 'evaluate': true }],
  ],
  'plugins': [
    '@babel/plugin-transform-runtime',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-syntax-dynamic-import',
    'universal-import',
  ],
}

```

versions:
```
node 10.10.0
npm 6.4.1
babel 7.0.0
linaria ff47c99cab96c1803ab452018a69b2903a382367
```

---

**Potential fix**

Replace `require(<path>)` to `require(./<path>)` in all linaria entry points. For example, in `babel.js`:

```diff
- module.exports = require('lib/babel');
+ module.exports = require('./lib/babel');
```

**Workaround:**
```
['linaria/lib/babel', { 'evaluate': true }],
```

**Comment by satya164** [comment]
Thanks for the report! Fixed.
