### ISSUE TITLE
Installing linaria@next results in empty module directory in node_modules

### ISSUE THREAD

**Issue by yakovkhalinsky** [callstack/linaria#220]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
running `npm i linaria@next` results in a node_modules 

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
run `npm i linaria@next`
look at `node_modules/linaria`
you will see only `package.json`

**What is the expected behavior?**
Module directory should have published files

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**
N/A

**Comment by satya164** [comment]
The next branch is not published to NPM yet. You need to install from GitHub for now.

**Comment by ivan-aksamentov** [comment]
@yakovkhalinsky Use:

    npm install callstack/linaria#next

or 

    npm install callstack/linaria#<commit_hash>

or fork+clone + `npm link` if you're up to contributing :)

**Comment by satya164** [comment]
Just published it
