### ISSUE TITLE
Investigate if we can avoid writing the CSS file to disk

### ISSUE THREAD

**Issue by satya164** [callstack/linaria#222]
Currently, we write the file to the disk and add it as a `require` statement in the JS in the webpack loader. We should use memory fs if possible. https://github.com/4Catalyzer/css-literal-loader does it but looks complex. Another approach in https://github.com/callstack/linaria/tree/%40satya164/loader-magic, but it doesn't go through `css-loader` anymore

**Comment by jquense** [comment]
Hey if ya'll are still interested in this, i'd be happy to extract out the underlying webpack plugin into a separate package 👍

**Comment by satya164** [comment]
@jquense That'll be great! It'll also be useful for other use cases I imagine.

**Comment by jayu** [comment]
We can try this https://github.com/sysgears/webpack-virtual-modules

**Comment by Anber** [comment]
Looks like we can. I've released 2.2.0 and 3.0.0-beta.16 with an in-memory cache.
