### ISSUE TITLE
Gatsby and linaria?

### ISSUE THREAD

**Issue by braco** [callstack/linaria#233]
Has anyone done work with the (extremely popular) Gatsby and Linaria? I didn't see a plugin:

https://github.com/gatsbyjs/gatsby/tree/master/packages

**Comment by satya164** [comment]
I was thinking about it, but haven't gotten time. Maybe you can build it :D

**Comment by silvenon** [comment]
I built it, it's was really simple thanks to how Linaria works. I'll publish it soon and post a comment here.

**Comment by silvenon** [comment]
[gatsby-plugin-linaria](https://github.com/silvenon/gatsby-plugin-linaria)
