### ISSUE TITLE
Explicitly pass Babel configuration to evaluate or infer it better

### ISSUE THREAD

**Issue by silvenon** [callstack/linaria#249]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Currently it doesn't seem to be possible to explicitly pass custom Babel configuration to Linaria. If there's a Babel configuration file in the standard place, Linaria's evaluate automatically picks it up, but in cases where Babel configuration is somewhere else, this doesn't seem to be possible.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

[I made a repro](https://github.com/silvenon/repro-linaria-babel), the steps are defined in the readme.

**What is the expected behavior?**

When using tools like Gatsby, which manage their Babel configuration internally, I would like to be able to pass that configuration to Linaria because it's crucial for evaluate feature. E.g. if the imported file has Flow types, evaluate will fail because it won't know that it should use the Flow preset.

I'm not familiar with Linaria's codebase yet, but #247 seems like it might be helpful in fixing this. Or is it possible to somehow infer it?

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**

Babel configuration:

```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-flow",
    "linaria/babel"
  ]
}
```
```
Linaria: 1.0.0-alpha.8
Node: 10.11.0
Yarn: 1.10.0
```

**Comment by satya164** [comment]
How about adding a `.babelrc` to the project root which just extends gatsby's babel config?

```json
{
  extends: "path/to/gatsby/babelrc"
}
```

Other tools such as Jest need a `.babelrc` too, so maybe makes sense to solve it at the project level instead of adding an option specifically for linaria.

**Comment by silvenon** [comment]
That's a really good point, not sure what I was thinking with this issue. 😅
