### ISSUE TITLE
Pattern for excluding props

### ISSUE THREAD

**Issue by bebraw** [callstack/linaria#256]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

```js
const Slide = styled.div`
  page-break-after: always; /* Needed for print to work */
  background-color: ${props => props.backgroundColor};
`;
```

leaks `backgroundColor` into the DOM leading to a React warning.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

See above.

**What is the expected behavior?**

There should be a pattern for excluding props. As above, I use it only for logic. This might be solvable by either documenting the right way or by adding API. Even styled-components doesn't solve this neatly yet.

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**

Linaria 1.0.0-alpha.8.

**Comment by thymikee** [comment]
I'd rather document the behavior instead of adding a pattern/whitelist, which increase the maintenance cost. You can name the prop whatever you like and we shouldn't alter that imho, unless it's a special prop like `css`.

**Comment by satya164** [comment]
Also, to filter props, you could do something like:

```js
import omit from 'lodash/omit';

const filterProps = (Comp, excludeList) =>
  props => <Comp {...omit(props, excludeList)} />;

const Slide = styled(filterProps('div', 'backgroundColor'))`
  ...
`;
```

For React warning, React does

**Comment by bebraw** [comment]
> For React warning, React doesn't warn anymore in 16 I think?

I'm running React 16 and it gives warnings.

It's the same pattern as for SC then. 👍

**Comment by radoslaw-medryk** [comment]
Confirming as well, React 16.6.3 gives the warning when not recognized attributes are added to HTML elements.

I think approach used by `styled-components` works quite well, i.e. filtering and passing through only recognized props to HTML elements. `styled-components` deals with that in quite intuitive way, Handling gracefully most common case when you dont pass custom attributes to DOM.

Example with quite the same components in `styled-components` and in `linaria` to compare behavior:

```typescript
export type BorderedColorBoxProps = {
    borderColor: string;
};

export type ColorBoxProps = {
    backgroundColor: string;
};

export const BorderedColorBox = styled(ColorBox)`
    border: 1px dotted ${(props: BorderedColorBoxProps) => props.borderColor};
`;

export const ColorBox = styled.div`
    background: ${(props: ColorBoxProps) => props.backgroundColor};
    width: 128px;
    height: 128px;
`;
```

### styled-components:
(In branch `bug/props_leak`):
https://github.com/radoslaw-medryk/styled-example

https://imgur.com/L392d8h

### linaria:
(In branch `bug/props_leak`):
https://github.com/radoslaw-medryk/linaria-example

https://imgur.com/ig7ZZLZ

**Comment by satya164** [comment]
They had removed it in styled-components, but added it back. We can consider doing the same, though it'll add around 2kb to the bundle: https://bundlephobia.com/result?p=@emotion/is-prop-valid

cc @zamotany @thymikee

**Comment by thymikee** [comment]
It's dev only so I'm not opposed

**Comment by satya164** [comment]
@thymikee I think doing it only in dev might produce inconsistent results. I'm not really sure. Does `styled-components` only do it in dev?
