### ISSUE TITLE
[Theming] Compile down to the values instead to set custom css properties

### ISSUE THREAD

**Issue by eatsjobs** [callstack/linaria#268]
**Do you want to request a *feature* or report a *bug*?**
A Feature

**What is the current behavior?**
Theming props fallback to custom css properties

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
N/A

**What is the expected behavior?**
Compile down to the value instead to set custom properties
For example:
in the compiled css instead of having 
- background: color(--my-color); 
- background: '#fff';

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**
N/A

**Comment by satya164** [comment]
We use CSS variables only for the values we don't know at compile time. If you're passing your theme via props, your app needs to be rendered first to get the initial value, and props can change when your app is running, so we can't use just the initial value. CSS variables are the most performant way to use these dynamic values.

If you don't want to use CSS variables, you can use the class name approach we have mentioned [here](https://github.com/callstack/linaria/blob/master/docs/THEMING.md#class-names).
