### ISSUE TITLE
Allow to configure babel

### ISSUE THREAD

**Issue by s-panferov** [callstack/linaria#274]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Linaria uses [a .babelrc file inside a project](https://github.com/callstack/linaria/blob/c949f19d76cb5027f980c3de864dae0b6f98ea2e/src/transform.js#L67). I believe it works most of the time for small projects. The problem is that in our company babel configuration is centralized, so we don't have a dedicated babel configuration file in every project we have, because it's hard to maintain them independently (we have for about 80 UI applications). We manage babel's configuration inside a shared webpack config file.

**What is the expected behavior?**
Could you please provide a way to just pass a babel configuration inside linaria loader?

P.S. I worked in early alpha versions, I think https://github.com/callstack/linaria/pull/261 changed it.

**Comment by silvenon** [comment]
> I worked in early alpha versions

Yep, I built [gatsby-plugin-linaria](https://github.com/silvenon/gatsby-plugin-linaria) during alpha, but the plugin doesn't work anymore because it doesn't detect Babel configuration. I would also appreciate if we could pass it to the webpack loader.

**Comment by satya164** [comment]
Usually, something like this should do:

```js
// .babelrc.js
{
  extends: require.resolve('path/to/your/babelrc')
}
```

Is there a reason not to use it in your case? Thinking whether we should document it or add an option to specify `babelrc`. (PR welcome btw)

**Comment by s-panferov** [comment]
This might work, but I just don't want my projects to require .babelrc at all. We have more than 100 UI projects and I prefer to manage all the configuration in one place.

**Comment by s-panferov** [comment]
Every project has a `webpack.config.js` file, which contains a require from our build system package:

```
const configBuilder = require('our-build-system')

module.exports = configBuilder({
  /* .. a bunch of project-specific flags */
})
```

This `configBuilder` returns a complete set of Webpack configuration: loaders, plugins, settings. Babel is configured as a part of `babel-loader`, which supports passing babel settings directly. There is no place in the system where I need a .babelrc file, because all the projects share the same webpack configuration.

I understand that this case looks odd for you. I understand if you don't want to fix it. We can make a linaria fork with this stuff and live with it in case you decide to close the issue.

**Comment by satya164** [comment]
@s-panferov I'm open to add a `babelOptions` option and PR welcome.
