### ISSUE TITLE
linaria/babel plugin with CRA

### ISSUE THREAD

**Issue by marsimx** [callstack/linaria#276]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Linaria uses a babel plugin (linaria/babel) to be included in babelrc

**What is the expected behavior?**
How could I use Linaria babel plugin with CRA without having to eject? Maybe something like a babel-plugin-macros?

**Comment by satya164** [comment]
It's not ideal with a macro. We need to generate CSS files and a bundler plugin is the best tool for this. We could technically do this from a Babel plugin, but CRA disables caching for macros, so perf will be bad, and there'll be many other issues without proper integration with the bundler.

**Comment by zamotany** [comment]
Generally, we do not support CRA without ejecting.
