### ISSUE TITLE
Cant resolve .linariacache

### ISSUE THREAD

**Issue by vladmelnikov** [callstack/linaria#278]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
webpack throws error
Can't resolve 'C:my-project.linaria-cachesrcApp.linaria.css' in 'C:\my-project\src'
configuration
.babelrc
`{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript",
    "@babel/preset-react",
    "linaria/babel"
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
    "react-hot-loader/babel"
  ]
}`
rules for webpack 
`   {
      test: /\.css$/,
      use: [
        { loader: 'style-loader' },
        {
          loader: 'css-loader',
          options: {
            sourceMap: !isProd,
          },
        },
      ],
    },
    {
      test: /\.(j|t)sx?$/,
      exclude: /node_modules/,
      use: [
        { loader: 'babel-loader' },
        {
          loader: 'linaria/loader',
          options: {
            sourceMap: !isProd
          },
        }
      ]`

"linaria": "^1.0.0-beta.0"
 "webpack": "^4.23.1",

OS - windows 10

**Comment by satya164** [comment]
I don't have a windows machine to test unfortunately :(
Do you use WSL?

**Comment by zamotany** [comment]
@satya164 I don't WSL is used here, if you look at the paths: ` 'C:my-project.linaria-cachesrcApp.linaria.css' in 'C:\my-project\src'`, with WSL they would look much different. My bet is that the original error is
```
Can't resolve 'C:\my-project\.linaria-cache\src\App.linaria.css' in 'C:\my-project\src'
```

**Comment by mfarhadpur** [comment]
Having the same issue. Is it maybe the `:` in Windows paths resulting in invalid module names [here](https://github.com/callstack/linaria/blob/8ace1f310384cb6809ec654dac0c016893f83586/src/loader.js#L15)?

**Comment by satya164** [comment]
Maybe it's how Webpack handles absolute paths on Windows? From this issue, looks like we need to escape the slashes: https://github.com/webpack/webpack/issues/66

So we need to insert: `C:\\my-project\\.linaria-cache\\src\\App.linaria.css` instead of `C:\my-project\.linaria-cache\src\App.linaria.css`.

Can you try this branch and tell me if it works @mfarhadpur? https://github.com/callstack/linaria/tree/%40satya164/win-path
