### ISSUE TITLE
linaria/loader issue with TypeScript

### ISSUE THREAD

**Issue by radoslaw-medryk** [callstack/linaria#279]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`linaria/loader` skips files that uses `styled` or `css` only with generic type parameter (TypeScript).

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
Create new component file, inside create styled React component providing generic parameter for props type, e.g.:
```typescript
// imports, etc. (...)

export type TitleProps = {
  backgroundColor: string;
}

export const Title = styled.h1<TitleProps>`
  background: ${props.backgroundColor};
`;
```

Reproducing repo:
https://github.com/radoslaw-medryk/linaria-example
```
npm install
npm run start
```

**What is the expected behavior?**
Component would be processed by `linaria/loader`.

**What is the actual behavior?**
Instead, `linaria/loader` ignores this component file when building, because it doesn't pass this regex test:
`linaria/src/transform.js:54`
```javascript
if (
    !/\b(styled[\s\n]*(\([\s\S]+\)|\.[\s\n]*[a-z0-9]+)|css)[\s\n]*`/.test(
      content
    )
  ) {
    return {
      code: content,
      sourceMap: inputSourceMap,
    };
  }
```
This regex doesn't expect generic type parameters, and thinks this file doesn't use linaria.

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**
`"linaria": "^1.0.0-beta.0"`

`.babelrc`
```json
{
    "presets": [
        "@babel/react",
        "@babel/typescript",
        ["linaria/babel", {
            "displayName": true
        }]
    ],
    "plugins": []
}
```

**Comment by satya164** [comment]
Oops. Sorry, will fix asap.

**Comment by radoslaw-medryk** [comment]
I can do PR to fix this. Would be a good intro into contributing to project with great potential :)

**Comment by satya164** [comment]
Will be awesome. Thank you.

**Comment by radoslaw-medryk** [comment]
I see some possible solutions:
- Adapt regex to detect TypeScript generic parameters
This is more of a quick-fix than a real solution. This way of checking if file uses linaria is not perfect, and can fail in some quite common scenarios, like for example:
```javascript
// Valid scenario, when somebody aliases styles to have shorter version
import { styles as s } from "linaria";

export const Title = s.h1`
  color: tomato;
`;
```

- Change regex to something harder to accidentally bypass, .e.g. check lines that contains `import`/`require` and `linaria`.
Still possible to overcome, but much less likely (at least by accident).

- Remove regex check completely and process every file. I understand that regex was added as a performance-related check, to skip expensive babel parsing and transforming, but maybe the performance penalty is not that bad? I doing some benchmarks would make sense here.

- Hybrid solution: By default parse every file, add config value to loader to allow overriding strategy to e.g. regex for import/require or something else.

**Comment by satya164** [comment]
Maybe we can just check for `styled` and `css`. They should be guaranteed to be in the file. It'll result in more false positives, but should be more reliable.
