### ISSUE TITLE
How to use Linaria in create react app 2

### ISSUE THREAD

**Issue by sysleaf** [callstack/linaria#285]
**Do you want to request a *feature* or report a *bug*?**
Its not a bug or feature but it would be great if it mentioned somewhere on how to use it with create react app.

what configuration need to be changed in order to make it work with create-react-app.
I tried whatever babel preset config was mentioned with craco but I was getting error like below.

```
Error: Using the "css" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly.
```

Currently, I am using create-react-app2(with inbuilt typescript support) with craco to provide customised config if create-react-app does not support any thing by default.

**Comment by satya164** [comment]
Linaria requires a webpack loader, so it won't work without ejecting from CRA as CRA doesn't allow you to customize the webpack config.

**Comment by Hotell** [comment]
what about providing babel macro to prevent ejecting ?

**Comment by satya164** [comment]
A babel macro will provide very bad UX. See my comments [here](https://github.com/callstack/linaria/issues/308#issuecomment-462164541).

Maybe it'll be nice if someone publishes `react-scripts-linaria` which we can link to in our docs.

**Comment by Hotell** [comment]
thanks for the link to former issue!

> Maybe it'll be nice if someone publishes `react-scripts-linaria` which we can link to in our docs.
Yeah that makes

**Comment by drownbes** [comment]
@sysleaf Check this: https://github.com/drownbes/linaria-cra . I've set up cra with linaria using [craco](https://github.com/sharegate/craco)
