### ISSUE TITLE
CLI insert-css-requires path

### ISSUE THREAD

**Issue by chrisbateman** [callstack/linaria#292]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
CSS require paths don't include a leading `./`, so it looks for the files in `node_modules`.

Though I'm not completely sure if I'm using the CLI in an unexpected way.

Example project files:
- src
  - component.js
  - componentStyles.js

Command:
```
linaria -o dist -r src -i dist src/**/*.js
```
Output dist files:
- dist
  - component.js
  - componentStyles.js
  - src
    - componentStyles.css

Output require: 
```js
require('src/styles.css');
```

**What is the expected behavior?**
Output code: 
```js
require('./src/styles.css');
```

**Comment by satya164** [comment]
cc @zamotany

**Comment by zamotany** [comment]
@chrisbateman Please provide us with reproducible project, I'm having a difficulty to reproduce it.

**Comment by chrisbateman** [comment]
Awesome, thanks so much!
