### ISSUE TITLE
Feature Request: remove linaria import when using the Babel plugin

### ISSUE THREAD

**Issue by chrisbateman** [callstack/linaria#293]
**Do you want to request a *feature* or report a *bug*?**
Feature

This is not a big problem, since we can usually rely on Webpack/Rollup to remove the unused import. But this would allow reusable libraries to make Linaria a devDependency rather than a regular dependency.

**What is the current behavior?**
Example output JS:
```js
import {css} from 'linaria';
export var red = "rslh4hm";
export var green = "g1xf75vt";
```

**What is the expected behavior?**
```js
export var red = "rslh4hm";
export var green = "g1xf75vt";
```

**Comment by satya164** [comment]
Makes sense. Though if you use any other utilities from `linaria` (`cx` and `styled`), they are actually needed in runtime, so we can only remove the import if you only use `css`. Maybe it'll be better to use something like `babel-plugin-rewrite-require` when publishing the library where you rewrite them to some empty local file.

**Comment by chrisbateman** [comment]
Yeah, good point. I'm good with whatever y'all want to do!

**Comment by jayu** [comment]
It's a good idea but for rare use cases. But PRs welcome :)
