### ISSUE TITLE
Add scope option for libraries

### ISSUE THREAD

**Issue by zamotany** [callstack/linaria#299]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

**What is the expected behavior?**

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**

**Comment by jayu** [comment]
@zamotany what is a use case for this feature. Do you want to be able to add a prefix to class names generated by linaria?  I would be useful while building component libraries, right?

**Comment by thymikee** [comment]
Yup, avoiding classname conflicts when publishing css from a library was the goal

**Comment by jayu** [comment]
Since code for this feature is already there (#369), but only needs migration to TypeScript, I mark it as good first issue

**Comment by jayu** [comment]
I missed out that we have `classNameSlug` option. So it is possible to have library scoped class name now.
