### ISSUE TITLE
using both `css` and `styled` throws error

### ISSUE THREAD

**Issue by egorovli** [callstack/linaria#301]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

When used separately, both `css` and `styled` APIs work. When used in the same file, it throws

```
Error: Using the "css" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly.
```

The code is something like this:

```jsx
import React from 'react'
import { styled } from 'linaria/react'
import { css } from 'linaria'

let Wrapper = styled.div`
  display: flex;
`

let someStyle = css`
  color: red;
`

let SomeComponent = ({ children }) => {
  return (
    <Wrapper className={someStyle}>
      {children}
    </Wrapper>
  )
}

export default SomeComponent
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

Please, test the above code snippet. If it doesn't throw, I'll set up a repo with all the webpack configs and all.

**Please provide your exact Babel configuration and mention your Linaria, Node, Yarn/npm version and operating system.**

_babel.config.js_:

```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        useBuiltIns: 'usage'
      }
    ],
    '@babel/preset-react',
    'linaria/babel'
  ],
  plugins: [
    '@babel/plugin-syntax-dynamic-import',
    'react-hot-loader/babel'
  ]
}
```

_webpack rule_:

```js
{
  test: /\.jsx?$/,
  include: [
    srcDir
  ],
  use: [
    {
      loader: 'babel-loader'
    },
    {
      loader: 'linaria/loader',
      options: {
        preprocessor: 'none'
      }
    }
  ]
}
```

* linaria `1.0.0-beta.11`
* yarn `1.13.0`
* node `v11.2.0`
* macOS `10.14.2 (18C54)`

**Comment by satya164** [comment]
thanks! i'll check it asap
