### ISSUE TITLE
Usage side by side with css modules

### ISSUE THREAD

**Issue by otbe** [callstack/linaria#307]
**Do you want to request a *feature* or report a *bug*?**
Maybe bug, maybe misconfiguration

**What is the current behavior?**
I tried to add linaria to an existing codebase which uses `css-loader` and `modules: true`. 
My test component is something like that:
```
import { styled } from 'linaria/react';

const Svg = styled.svg<{ size: string; color: string }>`
  display: inline-block;
  height: ${props => props.size};
  width: ${props => props.size};
  color: ${props => props.color};
  transition-property: fill;
`;
```
and `<Svg color="currentColor" size="2rem"/>` gets rendered to 
```
<svg class="s1vsmjlt" style="--s1vsmjlt-0:2rem; --s1vsmjlt-2:currentColor;"></svg>
```
This seems to be fine, but the extracted css doesnt contain a class `s1vsmjlt`. It contains a `_33NZOXTD-dui-uP-Z0cOhb` class with all the css from my component. I guess this is related to my css modules setup, but I dont know how to fix it :/

**What is the expected behavior?**
It should work :)

Is this supposed to work?

**Comment by satya164** [comment]
The CSS files generated by Linaria have `.linaria.css` extension, so you can exclude those from CSS modules and use `css-loader` without modules to process them.

**Comment by otbe** [comment]
Smart! Thanks, got it working 👍
Very nice lib by the way!
