### ISSUE TITLE
so confused with the error "[TypeError: _this.setMessage is not a function]

### ISSUE THREAD

**Issue by tenjojeremy** [callstack/linaria#314]
so confused with the error "[TypeError: error.setMessage is not a function]
![annotation 2019-02-15 111314](https://user-images.githubusercontent.com/25231946/52878940-bf4a4a00-3112-11e9-9e42-dcd6c435a19f.jpg)

**Comment by satya164** [comment]
can you post your code?

**Comment by tenjojeremy** [comment]
Fixed. I forgot to add `css-hot-loader` module

Thanks for the quick response and great job on the project!
