### ISSUE TITLE
API for adding global CSS

### ISSUE THREAD

**Issue by satya164** [callstack/linaria#33]

**Comment by thymikee** [comment]
Any ideas on that? Should we go mainstream way and provide something similar like `injectGlobal`?
Would happily use such api for SSR.

**Comment by namnm** [comment]
Hi guys, any news on this?

**Comment by zamotany** [comment]
Since, we have now `css-loader` in the pipeline, you can use normal CSS files.

**Comment by alexfedoseev** [comment]
> Since, we have now css-loader in the pipeline, you can use normal CSS files.

But it's impossible to use variables defined in js?

**Comment by alexfedoseev** [comment]
Workaround (Webpack only I guess):

```js
export const globals = css`
  :global {
    * {
      box-sizing: border-box;
    }
  }
`;
```

**Comment by lauritzsh** [comment]
@alexfedoseev I am trying your workaround but am not having luck with it. It does not seem to add any global styling. I have a separate `globals.css` file but like you, I want to use variables I have defined. Where did you add your snippet and did you have to configure webpack somehow for it to work?

**Comment by satya164** [comment]
You can also do this if you want to use variables and/or pass props:

```js
const Global = styled(React.Fragment)`
  :global {
    html {
      box-sizing: border-box;
      height: 100%;
      width: 100%;
    }

    *,
    *:before,
    *:after {
      box-sizing: inherit;
    }
  }
`;
```
