### ISSUE TITLE
Defualt props on styled element (.attrs)

### ISSUE THREAD

**Issue by SchlagerKhan** [callstack/linaria#331]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Using the `styled` variable there is no way to set default props/attributes on the elements. In `styled-components` there is a way using the `.attrs` property such as

```js
styled.img.attrs({
  src: require('...')
})`
  width:100%;
`
```

Have I missed some documentation of this (or a similar) feature or is this not (yet?) supported by linaria? Or is there another best practise of this?

**Comment by satya164** [comment]
They are normal React components. So you'd just use default props like you'd on React components.

```js
const Image = styled.img`
  ...
`;

Image.defaultProps = {
  src: require('...'),
};
```

**Comment by SchlagerKhan** [comment]
So you don't agree that the code sometimes can get more concise if you would expose an `.attrs` property on the styled elements?

**Comment by satya164** [comment]
It may be sometimes more concise, but we don't want to reinvent APIs already provided by React. You're already using React, so no reason to hide it by abstracting over a React API.

**Comment by SchlagerKhan** [comment]
Fair enough - I agree with the philosophy in general. Better to do one think right than a lot in less quality. But I don't think this is reinventing the API more than adding a useful component wrapper helper. 

You are probably more familiar with styled-components than I am and I'm not saying that they are doing everything right. But I would argue that one general purpose for this css-in-js approach (that these projects has in common) is to facilitate the creation of components which this feature greatly does.

Also, to be clear. I'm not simply requesting a way to declare the default props. I'm humbly requesting that the `.attr`-function should be more of a wrapper - as in styled-components.

For instance, consider these two approaches:

```js
// A very simple comparison

// Linaria
const _Wrapper = styled.div`
  ...
`;

const Wrapper = ({ type }) => <_Wrapper color={type === 'primary' : 'red' : 'blue'} />;

// Styled-components
const Wrapper = styled.div.attrs(props => ({
  color: props.type === 'primary' ? 'red' : 'blue',
  ...
})`
  ...
`
```

I can provide more extensive examples if needed. But the point is that in one module there might be a lot of these smaller components (each could possibly have a lot more custom properties than just `color`) that don't deserve their own file. Without this feature the file quickly gets bloated.

I'm not saying that this is an easy implementation - this I don't know. But I am saying that I think you should not discard this feature request so easily.

**Comment by satya164** [comment]
Yeah, the `attrs` prop is useful if you want to derive props from props. However, implementing it also means extra work.

For a small amount of usage, usually, an HOCs is fine, or we can move the computation to an external function.

Do you need this functionality often?

**Comment by SchlagerKhan** [comment]
Yeah, no surprise that this requires extra work and also may become a problem by adding extra complexity to the transpiler(?). However, personally I think this is quite an essential feature that might be a deal breaker for me. Despite the other amazing features of Linaria, clean and concise code is prio 1 for me.

If I use it often or not I think is quite irrelevant because I don't want to trade your time against only my convenience. My main purpose was only to make the library better in general for any developer. 

But to answer your question, yeah I use this feature in pretty much every other file. This mainly regards very simplistic components (such as in the example above), but also sometimes as a hoc using the `styled(Component)`-function.

But once again; This is not a demand, I'm only saying that I think you might have discarded this feature a bit quick.
