### ISSUE TITLE
Array<Object> interpolation - polished normalize fails

### ISSUE THREAD

**Issue by SchlagerKhan** [callstack/linaria#332]
**Do you want to request a *feature* or report a *bug*?**
feature/bug

**What is the current behavior?**
The `normalize` function from `polished` returns an array of styles which makes the following break:

```js
import { normalize } from 'polished';

const globalCss = css`
  :global() {
    ${normalize()}
  }
`
```

It's unclear why polished returns an array and it could of course be solved by doing:

`${normalize()[0]}`

 But it's not vert stylish and, without knowing anything about your implementation, it seems like an easy fix?

**Comment by satya164** [comment]
Yeah we can handle it. Wanna send a PR?

**Comment by SchlagerKhan** [comment]
Beat me to it

**Comment by JohnnyCrazy** [comment]
Just FYI, this happens again on the latest `3.0.0-beta.15`

`normalize` also returns 2 elements now, so we now need the following snippet to circumvent this...

```
:global() {
  ${normalize()[0]}
  ${normalize()[1]}
}
```
