### ISSUE TITLE
Avoid breaking eslint rule react/no-unknown-property 

### ISSUE THREAD

**Issue by IanVS** [callstack/linaria#347]
Because the prop name of `class` that linaria chose, I found that eslint was automatically changing it into `className` when I saved the file, and realized it was because of [`react/no-unknown-property`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unknown-property.md).

Have you considered using a prop named `css` instead?  This is what emotion uses, and from what I can tell, it might make it a lot easier to migrate from emotion to linaria as well, since the API is pretty much the same, at least for tagged template literals.  

Anyways, I'm continuing to experiment with using this in Gatsby, and haven't completely gotten it working yet, but wanted to at least let you know one source of friction that I hit, in case you weren't aware.  I can fix it in my eslint config, but it was still surprising.  Thanks!

**Comment by satya164** [comment]
The `css` tag returns a class name, how you pass it to your component is up to you. Linaria doesn't require you to use `class`. You can use either `class` or `className` for React. `className` is preferred, but both are perfectly valid prop names.

Regarding gastby, have you tried https://github.com/silvenon/gatsby-plugin-linaria ?

**Comment by IanVS** [comment]
Oh that makes perfect sense.  I didn't realize the example in `https://github.com/callstack/linaria#syntax` was just html, and not jsx.  I'm so used to looking at react-based projects!  😆 	

Regarding the gatsby plugin, that's what I'm using, but unfortunately have not yet gotten to generate an actual css file yet.  Still trying to figure out what's going on there…

Anyways, thanks for the help!

**Comment by satya164** [comment]
Maybe @silvenon can help since he wrote the plugin

**Comment by IanVS** [comment]
Thanks. I opened https://github.com/silvenon/gatsby-plugin-linaria/issues/9 in that project.  I'm really excited to get this working. I've always thought it would be great to ship real CSS files and use custom properties.  Seems a particularly good fit for Gatsby.
