### ISSUE TITLE
How to configure typescript

### ISSUE THREAD

**Issue by IanVS** [callstack/linaria#348]
## Ask your Question

I'm trying to set up linaria (v1.3.1) in a gatsby typescript project, and I'm hitting a few issues.  What I'm asking about in this particular issue is that I'm getting errors in VS Code (and when running `tsc --noEmit` to check types on the command line).  For example, I get:

```
Type '{ children: Element; class: string; }' is not assignable to type 'DetailedHTMLProps<LiHTMLAttributes<HTMLLIElement>, HTMLLIElement>'.
  Property 'class' does not exist on type 'DetailedHTMLProps<LiHTMLAttributes<HTMLLIElement>, HTMLLIElement>'.
```

I tried to configure my `tsconfig.json` with `"types": ["node", "linaria"],`, but that didn't seem to help.  Any suggestions of what I could try?

**Comment by satya164** [comment]
I believe the typescript types use `className` and not `class`. Use `className` and it'll be fine.

**Comment by IanVS** [comment]
Yep, thanks!  This stemmed from my misunderstanding in https://github.com/callstack/linaria/issues/347.
