### ISSUE TITLE
Rollup: Unused classes are not removed from css file when using rollup and unused imported styles

### ISSUE THREAD

**Issue by vladshcherbin** [callstack/linaria#349]
## Environment

linaria - 1.3.1
rollup - 1.6.0
rollup-plugin-css-only - 1.0.0

## Description

When using rollup and importing styles from a separate file, unused classes from unused exports are not removed from css file, only from js one.

## Reproducible Demo

Repo - https://github.com/vladshcherbin/experiments/tree/master/linaria-rollup-imports

Run: `yarn build`

I've also added pre-built files.

When using linaria in the same file, classes are correctly removed.

**Comment by TMaszko** [comment]
We are not able to remove unused classes because it would require additional tree shaking from linaria and this is not possible.

**Comment by vladshcherbin** [comment]
I believe it should be possible in rollup to find what imports are not used and remove them, after removal linaria shouldn't have them 🤔
