### ISSUE TITLE
Rollup: Unused css import is not removed by rollup, produces error

### ISSUE THREAD

**Issue by vladshcherbin** [callstack/linaria#350]
## Environment

linaria - 1.3.1
rollup - 1.6.0
rollup-plugin-css-only - 1.0.0

## Description

Rollup doesn't remove unused `css` import and produces an error in bundle instead.

## Reproducible Demo

Repo - https://github.com/vladshcherbin/experiments/tree/master/linaria-rollup-non-used-error

Run: `yarn build`

I've also added pre-built files.

**Comment by TMaszko** [comment]
I'll close it because It's not related to linaria with rollup itself. See more details here #624

**Comment by vladshcherbin** [comment]
I've checked #624 and #626 fix and result bundle is the same.
