### ISSUE TITLE
Rollup: doesn't remove linaria from bundle without using plugins, which produces browser error

### ISSUE THREAD

**Issue by vladshcherbin** [callstack/linaria#351]
## Environment

linaria - 1.3.1
rollup - 1.6.0
rollup-plugin-css-only - 1.0.0

## Description

When using only `css` function with rollup, `linaria` is not removed from bundle and is set as a global variable. If you run it, browser will give you an error.

To solve this, currently you need to use `rollup-plugin-node-resolve` and `rollup-plugin-commonjs`. If linaria will be correctly removed from bundle, this plugins won't be needed.

## Reproducible Demo

Repo - https://github.com/vladshcherbin/experiments/tree/master/linaria-rollup-global

Run: `yarn build`

I've also added pre-built files and `build/index.html` file to see error.

Rollup warnings:

![Screen Shot 2019-03-11 at 01 05 38](https://user-images.githubusercontent.com/6711845/54092251-143c5180-439b-11e9-9616-b5b14411e328.png)

Probably related: https://github.com/callstack/linaria/issues/293

**Comment by LukasBombach** [comment]
@vladshcherbin how do you solve this with `rollup-plugin-node-resolve` / `rollup-plugin-commonjs`? I am using `@rollup/plugin-commonjs` / `@rollup/plugin-node-resolve` and I have that error still


import commonjs from "@rollup/plugin-commonjs";
import resolve from "@rollup/plugin-node-resolve";

**Comment by vladshcherbin** [comment]
@LukasBombach don't remember, sorry. I gave up on using linaria and rollup, too many issues, unfortunately.

**Comment by LukasBombach** [comment]
No worries, thank you

**Comment by TMaszko** [comment]
@LukasBombach  Bumping up rollup version and using @rollup/plugin-commonjs, @rollup/plugin-node-resolve seems to resolve this issue :).

**Comment by eemeli** [comment]
I'm not sure what the commonjs & node-resolve plugins are supposed to do about this, but the right workaround for this is to add something like this to your Rollup config:

```js
export default {
  ...,
  treeshake: {
    moduleSideEffects: (id) => id !== 'linaria'
  }
}
```

The proper-er fix would be to remove the `css` import specifier at the same time as its template string invocations are removed, and to then also drop the whole import statement if it doesn't include any other specifiers.

**Comment by jayu** [comment]
I'm glad that there is a workaround, we could think of implementing https://github.com/callstack/linaria/issues/293 to solve the issue in it's source

**Comment by vladshcherbin** [comment]
@eemeli solution should be added to docs example because following current example will result in an error.
