### ISSUE TITLE
linaria/loader: cacheDirectory is ingored when webpack aliases are used within monorepo

### ISSUE THREAD

**Issue by Hotell** [callstack/linaria#359]
## Environment

```
macOs Mojave
linaria@1.3.1
node@8.15.0
```

## Description

I have following config/project structure:

**webpack loader config:**

```js
const linariaLoaderConfig = {
  sourceMap: true,
  babelOptions: {
    rootMode: 'upward',
  },
 cacheDirectory: '/Users/hotell/Projects/devel/my-ui/packages/customer-registration/.linaria-cache',
};
```

**webpack aliases:**

```js
{
alias: {
 '@twisto/components': '/Users/hotell/Projects/devel/my-ui/packages/components/src'
}
}
```

**project tree ( simplified ):**

```sh
-/packages
- babel.config.js
  --/components
     --/src
         - button.tsx 
         - button.styles.ts // 👉 linaria css
  --/ app
       - app.tsx // uses button 👉 import {Button} from '@my/components'
       - webpack.config.js // set up linaria/loader
```

**The issue:**

Loader outputs file within `app/components/src/button/button.style.linaria.css` (basically mirrors the file structure from `components` package),  which is not what one would expect ( also you cannot "handle" this via .gitignore ), even when `cacheDirectory` is explicitly defined via absolute path

![image](https://user-images.githubusercontent.com/1223799/54594198-7565c400-4a30-11e9-8b3b-b434b1605fad.png)

**Comment by amaranth** [comment]
This doesn't really have anything to do with webpack aliases, it'll happen any time you import something above your project root. The code responsible is https://github.com/callstack/linaria/blob/eda0efaa437b267f536fa4866efd9299f9738767/src/loader.ts#L42-L49.

  * `cacheDirectory` is `/Projects/my-ui/packages/app/.linaria-cache`
  * `root` is `/Projects/my-ui/packages/app`
  * `this.resourcePath` is `/Projects/my-ui/packages/components/src/button/button.styles.ts`

When you call `path.relative` you wind up with `../components/src/button/button.style.linaria.css` and when you `path.join` that to `cacheDirectory` you get `/Projects/my-ui/packages/app/components/src/button/button.style.linaria.css`.

We need to somehow strip the leading `../` or `..\\` from the relative path to ensure we don't escape the cache directory.
