### ISSUE TITLE
 How to use linaria and config  vue.config.js file in @vue/cli 3.0

### ISSUE THREAD

**Issue by guochun** [callstack/linaria#373]
we tream wants to  use linaria in vue framework. needs config linaria/loader into   vue.config.js . But i don't konw How to config

**Comment by satya164** [comment]
Unfortunately, I have never used vue, so I don't have much idea. But let us know if there's something we can do to make it easier.

**Comment by guochun** [comment]
thanks for helping . i have been find method  for Vue.

**Comment by jayu** [comment]
close via #273
