### ISSUE TITLE
Webpack resolve 

### ISSUE THREAD

**Issue by ivarshavets** [callstack/linaria#380]
## Environment

"@babel/core": "7.4.0",
"@babel/plugin-proposal-class-properties": "7.4.0",
"@babel/plugin-proposal-export-default-from": "7.2.0",
"@babel/plugin-proposal-export-namespace-from": "7.2.0",
"@babel/plugin-proposal-object-rest-spread": "7.4.0",
"@babel/plugin-syntax-class-properties": "7.2.0",
"@babel/plugin-syntax-export-default-from": "7.2.0",
"@babel/plugin-syntax-export-namespace-from": "7.2.0",
"@babel/plugin-syntax-object-rest-spread": "7.2.0",
"@babel/plugin-transform-regenerator": "7.4.0",
"@babel/plugin-transform-runtime": "7.4.0",
"@babel/preset-env": "7.4.2",
"@babel/preset-react": "^7.0.0",
"@babel/runtime": "7.4.2",
"@babel/runtime-corejs2": "7.4.2",

"webpack-dev-server": "3.2.1"
"webpack": "^4.29.6",
"webpack-assets-manifest": "^3.1.1",
"webpack-cli": "^3.2.3",
"linaria": "^1.3.1"

## Description

Expected component:

```js
import {styled} from 'linaria/react'
import {constants} from 'app/styles/constants'

export default styled.button`
  display: inline-block;
  box-sizing: border-box;
  border: none;
  border-radius: 2px;
  font-size: ${constants.fontSizeBaze};
  padding: 5px 20px;
  background-color: #00b2b2;
`
```

"app/styles/constants" will be resolved with this path  '/app/javascript/src'. Here is a part of a webpack config with resolve.modules: 

```js
  resolve:
   { extensions:
      [ '.jsx',
        '.js',
        '.sass',
        '.scss',
        '.css',
        '.module.sass',
        '.module.scss',
        '.module.css',
        '.png',
        '.svg',
        '.gif',
        '.jpeg',
        '.jpg' ],
     modules:
      [ '/app/javascript',
        '/app/javascript/src',
        'node_modules' ] }
```

I get the following error:

```js
Module build failed (from ./node_modules/linaria/loader.js):
SyntaxError: /app/javascript/src/app/components/button/index.jsx: An error occurred when evaluating the expression: Can't resolve 'app/styles/constants' in '/app/javascript/src/app/components/button'. Make sure you are not using a browser or Node specific API.
```

Trace:

```js
    at File.buildCodeFrameError (/node_modules/@babel/core/lib/transformation/file/file.js:261:12)
    at NodePath.buildCodeFrameError (/node_modules/@babel/traverse/lib/path/index.js:157:21)
    at /node_modules/linaria/lib/babel/visitors/TaggedTemplateExpression.js:200:22
    at Array.forEach (<anonymous>)
    at TaggedTemplateExpression (/node_modules/linaria/lib/babel/visitors/TaggedTemplateExpression.js:127:16)
    at TaggedTemplateExpression (/node_modules/linaria/lib/babel/extract.js:28:61)
    at NodePath._call (/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/node_modules/@babel/traverse/lib/context.js:118:16)
```

If it is changed to "../../styles/constants" - everything works.

But looks like you've made the fix for this issue in this PR: https://github.com/callstack/linaria/pull/297

Could you please explain how to use it
Thanks for explanation.

**Comment by domeknn** [comment]
@ivarshavets you have to use `babel-plugin-module-resolver`

**Comment by ivarshavets** [comment]
@domeknn Thanks
