### ISSUE TITLE
linaria/babel doesn't work within tests in monorepo

### ISSUE THREAD

**Issue by Hotell** [callstack/linaria#390]
## Environment

- macOs
- linaria 1.3.1
- "@babel/core": "7.3.4"

## Description

if I wanna use static variables from package  A within package B css declaration via linaria, tests are failing.

## Reproducible Demo

- using jest for running tests, with custom module mapper ( that resolves monorepo packages )

```
moduleNameMapper: {
    '@twisto/(.+)$': '<rootDir>/packages/$1/src',
  },
```

babel.config.js:
```js
const { IS_TEST } = require('./environment')

/** @type {import('babel').BabelConfigFunction} */
const config = (api) => {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const env = api.env()

  return {
    presets: [
      [
        '@babel/preset-env',
        {
          // Allow importing @babel/polyfill in entrypoint and use browserlist to select polyfills
          useBuiltIns: 'entry',
          // Do not transform modules to CJS
          modules: IS_TEST ? 'commonjs' : false,
          loose: true,
        },
      ],
      '@babel/preset-react',
      '@babel/preset-typescript',
      ['linaria/babel'],
    ],
    plugins: [
      '@babel/plugin-syntax-dynamic-import',
      ['@babel/plugin-proposal-class-properties', { loose: true }],
      ['@babel/plugin-proposal-object-rest-spread', { loose: true }],
    ],
    // @see https://babeljs.io/docs/en/options#env
    env: {
      production: {
        ignore: [
          '**/*.d.ts',
          '**/*.test.tsx',
          '**/*.test.ts',
          '**/*.story.tsx',
          '__snapshots__',
          '__tests__',
          '__stories__',
        ],
      },
    },
    ignore: ['node_modules'],
  }
}

module.exports = config
```

some-component.styles.ts:
```ts
import { css } from 'linaria'
import { theme } from '@twisto/styles'

export const heading1 = css`
  font-size: ${theme.fontSize.xxl};
  font-weight: 400;
`
```

some-component.tsx
```tsx
import * as classes from './some-component.styles'

export const Cmp = () => <div className={classes.heading1}>hello</div>
```

Error:

![image](https://user-images.githubusercontent.com/1223799/56268621-16a86e80-60f2-11e9-8b56-906872b1aa31.png)

**Comment by Hotell** [comment]
I've investigated further this issue, which takes our intenral project into  unfortunate situation. As previously mentioned the problem is monorepo + linaria/babel combo, when executing tests.

`@twisto/styles` package is being imported within `*.styles.ts` in other packages (mainly `@twisto/components`), which linaria/babel is unable to resolve. I don't see any quickfix on the horizon. So my solutions/findings are following:

1. use https://github.com/tleunen/babel-plugin-module-resolver, which will extremely slow down test execution ( from 5 sec to 180 sec 🗣🤦‍♀️ )
2. run manual babel build for @twisto/styles before running tests ( with that if you'll change anything linaria css related within styles package you'll have to kill your tests and rerun them again. Overall time for this solution 👉 2.5 sec for building js + 4 sec for running tests

I'll use 2nd option for now.

**Comment by ShanonJackson** [comment]
Having similar problem in monorepo setup where linaria components resolve fine in another direction however refuse to evaluate nested components in css / using Theme variables exported from another file in the other directory

**Comment by 0xsven** [comment]
@Hotell @ShanonJackson 
Have you found a solution? I am seeing this issue as well?

**Comment by ShanonJackson** [comment]
@0xflotus Yeah fixed this along time ago if i remember correctly its that you need to configure your build AND linaria to transpile that module in your node_modules explicitly.

I.E
linaria option: {ignore: "/node_modules[\/\\](?!YOUR-FOLDER-NAME)/"
with YOUR-FOLDER-NAME === your node_modules folder name that's symlinked or whatever in monorepo.
Then you'll end up in two boats.
Either it works.
Or it doesn't - If it doesn't you'll need to configure your build to transpile that folder in node_modules aswell explicitly as node_modules normally it is excluded from all transpiling by default. If you're using NextJS like i was you can use https://www.npmjs.com/package/next-transpile-modules.

Let me know if you have any issues.

I would also like to caveat this with. In my 8 months of pain and suffering and slow builds in monorepo i finally caved and now have a monorepo where each project is actually built and compiled and published to a private npm package, then consumed by the surrounding projects.

**Comment by jayu** [comment]
Closing for the same reason as described in https://github.com/callstack/linaria/issues/531#issuecomment-644755300
