### ISSUE TITLE
Deterministic Class Names

### ISSUE THREAD

**Issue by ShanonJackson** [callstack/linaria#419]
## Ask your Question

New to Linaria, playing around with it on weekends so don't roast too hard.

Setting up SSR on Backend.
Have to compile my frontend through web pack to get the style sheet. (style.css).
style.css comes out with my test component styles `.TestComponent.112XYZ`
Have to compile my frontend again with my backend for SSR.
TestComponent.js comes out something like... `(0, styled...)("div")....({class: "TestComponent.119ZYX")`
style.css and underlying element are out of sync.
SSR fails.

How do I get these classNames to sync up, they seem deterministic but i can't see whats causing them to come out differently depending on if webpack compiles it or if my backend babel compiles it

**Comment by ShanonJackson** [comment]
Well to answer my own question after some digging through the source the culprit is this...

TaggedTemplateExpression.js, has a parameter called state.file.opts.root that gets passed into the slug.

When the backend executes it this is the root dir of the backend.
When the frontend executes it this is the root dir of the frontend (backend/src/frontend)

When these are aligned to the same directory, the classNames come out the same.

The solution will probably be to run the webpack build command from my backend directory rather than from my frontend directory.

**Comment by pbitkowski** [comment]
> why you'd salt class names against the directory the script is running from

We need a path to generate a slug to keep the names deterministic. We can use either absolute or relative path, but using absolute path means that the slug will differ between machines. That's why we use relative path. Ideally we would use the path relative to project root, but we don't know what your project root is, we only know where you are running it from.

**Comment by rolftimmermans** [comment]
I am running into the same issue. A question I have, is whether you considered to use the CSS content itself as the seed of the hash? That seems deterministic as well, and much more resilient. Getting the relative paths aligned between client and server is a disaster...
