### ISSUE TITLE
Error: Cannot find module 'core-js/modules/es6.regexp.to-string'

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [callstack/linaria#420]
I ran this [example](https://codesandbox.io/s/2x93v25p3j) on my computer and I got this error:

`ERROR in ./src/App.js
Module build failed (from ./node_modules/linaria/loader.js):
Error: Cannot find module 'core-js/modules/es6.regexp.to-string'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/egortrubnikov-panov/Downloads/linaria-demo 2/node_modules/linaria/lib/loader.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
`

how can I fix this?

**Comment by egor-a-trubnikov-panov** [comment]
I added "core-js": "^2.0.0", in package.json and everything worked

**Comment by skywickenden** [comment]
Also having this problem. I'm a first time user to Linaria and was simply following the install instructions.  I added 

    "core-js": "^2.6.8"

to devDependencies. (^2.0.0 has vulnerabilities!)

This looks like https://github.com/callstack/linaria/issues/361 and should be fixed but isn't

**Comment by c01nd01r** [comment]
Looks like `package.json` in master branch and in npm (https://unpkg.com/linaria@1.3.1/package.json) has differences
<details>
  <summary>diff</summary>
  
![img diff](https://user-images.githubusercontent.com/3511312/58386694-1b731300-800c-11e9-9aa6-b5f4e3f1c714.png)
</details>

**Comment by pbitkowski** [comment]
Hi! Thanks for your input. Could you try alpha version?

**Comment by le0pard** [comment]
@pbitkowski thanks. Can you publish 1.4.0-alpha.0 to npm?

**Comment by Hotell** [comment]
we are using corejs v3 -> that won't work with linaria 1.3.1, if we bump to 1.4. hell breaks loose.  `RangeError: Maximum call stack size exceeded` all the things...

**Comment by imbsky** [comment]
`1.4.0-alpha.0` is working for us!
https://github.com/imbsky/linaria-module-issue

**Comment by deklanw** [comment]
`1.4.0-alpha.1` fixed it for me.

But, does it not include Typescript types?

**Comment by nhooyr** [comment]
Yea it looks like the alpha version doesn't have typescript types.

**Comment by nhooyr** [comment]
For now I'm just using

```
declare module "linaria" {
  // @ts-ignore
  export const css
  // @ts-ignore
  export const cx
}

declare module "linaria/react" {
  // @ts-ignore
  export const styled
}
```

Added into a `custom.d.ts` file.

**Comment by ahuglajbclajep** [comment]
Dependencies version can also be specified using a commit hash.
https://docs.npmjs.com/files/package.json#github-urls

Since [package.json in the current master branch contains core.js](https://github.com/callstack/linaria/blob/7e326c3/package.json#L86), you may be able to avoid the error with the following command: `npm i callstack/linaria#7e326c3` or `yarn add callstack/linaria#7e326c3`.

**Comment by megabayt** [comment]
any workaround without using alpha version?

**Comment by JakeAdler** [comment]
Is there a fix in the works for this? Experiencing the same issue.

**Comment by Daniel15** [comment]
I used `yarn add --dev core-js@2` to add the core-js dependency, which worked for me.

**Comment by sirluis** [comment]
Core-js 2 is deprecated. There are projects that could depend on core-js latest version features. Any plans to drop v2 on linaria?

**Comment by Denis-NV** [comment]
> Yea it looks like the alpha version doesn't have typescript types.
yarn add linaria@1.4.0-alpha.1 + custom.d.ts (to avoid TypeScript errors) worked for me.

I'm using firebase in my project. So downgrading core-js to version 2 was not an option for me.

Also, using [craco-linaria plugin](https://www.npmjs.com/package/craco-linaria) with [craco](https://github.com/sharegate/craco/blob/master/packages/craco/README.md) made it possible to use Linaria in React with create-react-app, but without ejecting

**Comment by ElForastero** [comment]
I also ran into this problem with create-react-app and craco plugin for linaria.

**Comment by chenyong** [comment]
Run into this as well. Why is linaria using old version of core-js?

**Comment by imbsky** [comment]
By the way, why doesn't release 1.4.0?

**Comment by hemlok** [comment]
> if we bump to 1.4. hell breaks loose. RangeError: Maximum call stack size exceeded all the things...

@Hotell did you find a solution for this on the alpha?

**Comment by Hotell** [comment]
> > if we bump to 1.4. hell breaks loose. RangeError: Maximum call stack size exceeded all the things...
> 
> @Hotell did you find a solution for this on the alpha?

yes, we ditched linaria completely. there is no/lack of activity from maintainers (I don’t blame them, it’s OSS) and relying on unfinished software for business critical features is a no go.

**Comment by oreqizer** [comment]
So what's going on? Am getting that it cannot find `core-js/modules/es7.array.includes`

It's really a shame, I wanted to use this in production. This is like the **holy grail** of CSS-in-JS libraries, guys. Keep it alive!

**Comment by funkybunky** [comment]
> I also ran into this problem with create-react-app and craco plugin for linaria.

Had the same problem and solved it just now by installing the latest beta like so:
`npm i -D linaria@1.4.0-beta.1`

**Comment by jayu** [comment]
Thank you for all the responses, I created an issue where we would try to address the problem better. I'm happy that some workarounds exist. Hence I'm closing.
