### ISSUE TITLE
style-loader and/or css-hot-loader are no longer needed

### ISSUE THREAD

**Issue by skywickenden** [callstack/linaria#421]
## Describe the feature

The bundlers instructions page mention using style-loader or css-hot-loader to achieve hot reloads of changed styles. This can now be achieved with mini-css-extract-plugin using the following in the css rules of webpack.config.js

          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              hmr: process.env.NODE_ENV !== 'production'
            }
          },

**Comment by thymikee** [comment]
Maybe you'd like to send a PR with the fix and some background on why to use this instead of other solutions? :)

**Comment by skywickenden** [comment]
Done: https://github.com/callstack/linaria/pull/422
