### ISSUE TITLE
Interop with emotion/styled-components

### ISSUE THREAD

**Issue by Anber** [callstack/linaria#424]
## Describe the feature

Add an ability to use Linaria components together with Emotion/styled-components/etc.

## Motivation

Complete migration from emotion/styled can be challenging or inappropriate for a lot of reasons, but Linaria can be used for optimization in critical parts. The problem there that migrated components cannot be interpolated in styles of non-migrated.

I have a draft implementation of this feature in separate babel plugin (https://github.com/anber/linaria-interop), but it also can be implemented as a part of Linaria.

**Comment by jayu** [comment]
@Anber do you have any new thoughts on this :)? Is it possible to do it? Is it worth doing in the nearest future?

**Comment by Anber** [comment]
> do you have any new thoughts on this

It can be added to the future linaria monorepo and published under @linaria scope.

**Comment by Anber** [comment]
Published as `@linaria/babel-plugin-interop`
