### ISSUE TITLE
[1.4.0-alpha.0] TypeScript error "Argument of type 'TemplateStringsArray' is not assignable to parameter of type 'string[]'."

### ISSUE THREAD

**Issue by kryops** [callstack/linaria#429]
## Environment

Tested with TypeScript 3.4.5 and 3.5.1, linaria 1.4.0-alpha.0

## Description

With the TS migration, the TypeScript typings seem to have changed in a way that breaks TypeScript consumers:

1.3.1 - typings.d.ts
```ts
export function css(
  strings: TemplateStringsArray,
  ...exprs: Array<string | number | CSSProperties>
): string;
```

1.4.0.alpha.0 - css.d.ts
```ts
export default function css(
_strings: string[],
..._exprs: Array<string | number | CSSProperties>
): string;
```

I now get the following error when using the `css` function with a tagged template literal:

```
Argument of type 'TemplateStringsArray' is not assignable to parameter of type 'string[]'.
  Type 'TemplateStringsArray' is missing the following properties from type 'string[]': pop, push, reverse, shift, and 7 more.ts(2345)
```

Maybe the type for `_strings` in https://github.com/callstack/linaria/blob/develop/src/core/css.ts#L6 should be something like `string[] | TemplateStringsArray` if you want to support both?

## Reproducible Demo

index.ts
```ts
import { css } from 'linaria'

const className = css`color: red`
```

**Comment by satya164** [comment]
cc @Anber

**Comment by Anber** [comment]
`TemplateStringsArray` already extends `readonly string[]` so we don't need to explicitly specify `string[]`.

**Comment by thymikee** [comment]
Fixed in `alpha.1`
