### ISSUE TITLE
Support Svelte.

### ISSUE THREAD

**Issue by tonykiselis** [callstack/linaria#435]
Currently compiler breaks when it encounters <script> tag:

```
ERROR in ./src/login/base/base.svelte
Module build failed (from ./node_modules/linaria/loader.js):
SyntaxError: /home/tony/Projects/auxilia/src/login/base/base.svelte: Unexpected token (1:0)

> 1 | <script>
    | ^
  2 |     import style from './styles';
  3 |     import Field from '../input/input.svelte';
  4 |     import { css } from 'linaria';
```
I suppose Vue would have very similar problem as compiler doesn't recognize that javascript is contained within the <script> tag.

Now for those who might not be aware, Svelte is a compiler for web standard compliant vanilla javascript components. Which made me think that Linaria sould be such a perfect fit to go hand in hand.

It's important to note that it actually does work, as I import generated class name, as the styles get compiled from separate file, but that beats the point of single-file-components.

**Comment by pbitkowski** [comment]
Hi Tony. Thanks for your request! I checked [Svelte](https://svelte.dev/) and it looks like a really good idea to support it.

**Comment by praneybehl** [comment]
Interest to find out if this issue progressed, or as why it might be happening?

**Comment by jayu** [comment]
We don't have capacity to provide support for every bundler right now. Prs are very welcomed ❤️

**Comment by madhavarshney** [comment]
Linaria works out-of-the-box with Svelte using webpack. The trick is to make sure `linaria/loader` comes after `svelte-loader` so that the `svelte` syntax is compiled away by the time `linaria` processes it. The following rules in your webpack config should work:

```js
module: {
  rules: [
    {
      test: /\.m?js$/,
      exclude: /node_modules/,
      use: 'linaria/loader',
    },
    {
      test: /\.svelte$/,
      use: [
        'linaria/loader',
        {
          loader: 'svelte-loader',
          options: {
            emitCss: true,
            hotReload: true,
          },
        },
      ],
    },
  ],
}
```

_Note: webpack runs loaders starting from the bottom._

**Comment by madhavarshney** [comment]
For Rollup, [follow the docs](https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#rollup) and enable `emitCss: true` for `rollup-plugin-svelte`.  The following should work:

```js
import svelte from 'rollup-plugin-svelte';
import css from 'rollup-plugin-css-only'; // for CSS bundling
import linaria from 'linaria/rollup';

export default {
  ...
  plugins: [
    svelte({
      dev: process.env.NODE_ENV !== 'production',,
      // allow `plugin-css-only` to bundle with CSS generated by linaria
      emitCss: true,
    }),
    linaria({
      sourceMap: process.env.NODE_ENV !== 'production',
    }),
    css({
      output: '<OUT_FOLDER>/bundle.css',
    }),
  ],
};
```

**Comment by jayu** [comment]
Thank you @madhavarshney, awesome contribution! I will test it soon If this will work we can update our docs. Wouldn't you mind to open a PR and update [bundler integrations docs](https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md) ?

**Comment by madhavarshney** [comment]
@jayu Sure! Did you get a chance to try it out? Let me know if I should spin up a sample repo that you can clone directly.

**Comment by jayu** [comment]
@madhavarshney Unfortunately I didn't have time for testing it. I wouldn't like to overuse your time, but any repo would be very helpful! Even for other users if you leave a link here 😀

**Comment by madhavarshney** [comment]
@jayu Here you go: https://github.com/madhavarshney/svelte-linaria-sample. Let me know what you think! I'll open a PR to update the docs sometime this week.

**Comment by jayu** [comment]
@madhavarshney I just tested your setup with rollup and webpack, It works like a charm! I'm really happy that people could use linaria with one more, amazing tool. If you still want to update docs, feel free to open a PR. I will assign this issue to you. I really appreciate your help 🥇 !

**Comment by seaneking** [comment]
Is anyone successfully using Linaria with Svelte props? Using linaria for plain CSS in svelte components works, but whenever I try using a dynamic prop in a Linaria declaration I get the following error: 

```
An error occurred when evaluating the expression: ctx is not defined. Make sure you are not using a browser or Node specific API.
  51 | 
  52 | attr_dev(div0, "class", div0_class_value = css`
> 53 | flex-basis: ${/*primaryBasis*/ ctx[0]}%;`);
```

Original code is something like 

```svelte
<div class={css`flex-basis: ${primaryBasis}%;` />
```

Looks like Linaria can't handle Svelte's prop hoisting/optimisations?
