### ISSUE TITLE
definition of "critical css"

### ISSUE THREAD

**Issue by PutziSan** [callstack/linaria#436]
Hi,
I think I've completely gone through the documentation. It is often said that critical css can be extracted. But I haven't found anywhere how "critical" is defined? Is there an attempt to extract css "above the fold" or does it depend on certain style tags?

**Comment by brandonkal** [comment]
@PutziSan the term "critical css" means the minimum css to render a view. You can look at the code:

https://github.com/callstack/linaria/blob/7e326c356b65639de10e405ebf5b29eec8742f10/src/server/collect.js#L80-L91

For any given html string, it will return the CSS classes that match it and all tags e.g. `span {}, div {}`.
This will usually be the SSR portion before React hydrates on the client.

If you wish to only return css that matches "above the fold" content, make sure the html you feed the collect function does not include "below the fold" content. However, that distinction should really not be necessary.

However, you should generally prefer server push and chunking CSS if your stylesheet is really big enough to warrant this.

**Comment by PutziSan** [comment]
Thank you very much for your explanation!
I just stumbled across the article/course [Critical Rendering Path](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/) and I guess that's where the term comes from. If so, it might be a good idea to link to the article in the documentation when you first mention "critical css".
