### ISSUE TITLE
Can't we use css-in-js syntax in stylelint?

### ISSUE THREAD

**Issue by imbsky** [callstack/linaria#440]
Can't we use css-in-js syntax in stylelint config? 
I got this message when I run stylelint with fix option.

> Autofix is incompatible with processors and will be disabled. Are you sure you need a processor?

`linaria/stylelint-config` has custom processor. But, since `stylelint@9.10.0`, it has `css-in-js` syntax option.

**Comment by brandonkal** [comment]
@imbsky Please look into this. Auto fix will be very hard to do safely, especially for fixes that sort lines.
The css-in-js option is quite impressive, but is quite new and has some issues. The main issue right now is that it doesn't understand how to handle interpolations:

```jsx
styled('div')`
  span {
    color: purple;
    ${'background-clip: border-box'};
    background-clip: ${'border-box'};
  }
`
```
With the code above, you will see false positive errors:
- Unexpected extra semicolons on line 3 (it looks to be completely removing the interpolation here).
- Can't parse value "${'border-box'}" stylelint(csstree/validator) - In this case it appears the csstree plugin is trying to read the code directly before the css-in-js removes all interpolations (which would also be an error).

This is the stylelintrc I was using to experiment:
```json
{
  "plugins": ["stylelint-csstree-validator"],
  "extends": ["stylelint-config-recommended"],
  "rules": {
    "no-descending-specificity": null,
    "comment-empty-line-before": null,
    "csstree/validator": true
  }
}
```

It appears that a custom syntax will need to be created, similar to the "css-in-js" [which is actually](https://github.com/stylelint/stylelint/blob/9efd6f4187c2e411b140e0ef53128a721009ce85/lib/getPostcssResult.js#L68-L72) "postcss-jsx"

This syntax would handle evaluating and substituting the contents of interpolations. Unfortunately, stylelint has no documentation on this API.


https://github.com/gucong3000/postcss-jsx

**Comment by hudochenkov** [comment]
> Auto fix will be very hard to do safely, especially for fixes that sort lines.

[stylelint-order](https://github.com/hudochenkov/stylelint-order) sorts CSS-in-JS safely :) When it's not possible to do safe sort, sorting not happening, only reporting happens.

> Unexpected extra semicolons on line 3 (it looks to be completely removing the interpolation here).

Yeah, there some limitation in `postcss-jsx`. For this case semicolon should be placed inside interpolation: `${'background-clip: border-box;'}`.

> Can't parse value "${'border-box'}" stylelint(csstree/validator) - In this case it appears the csstree plugin is trying to read the code directly before the css-in-js removes all interpolations (which would also be an error).

Correct. `postcss-jsx` doesn't evaluate code in interpolations. So the following abstract syntax tree is generated for `background-clip: ${'border-box'};`:

```js
{
  type: "decl",
  prop: "background-clip",
  value: "${'border-box'}"
}
```

> This syntax would handle evaluating and substituting the contents of interpolations.

Evaluation is not what PostCSS syntax does. Syntax contains both parser and stringifier. Parser parses input string to node’s tree. Stringifier generates output string by node’s tree.

**Comment by brandonkal** [comment]
What I mean when I say that using something like stylelint-order will be hard when evaluation comes into play:

```js
const fragment = `
  appearance: none;
  cursor: pointer;
`

const Sort = styled.div`
  background: black;
  ${fragment}
`
```
If for instance you proxied the autofix with a processor that evaluate, runs autofix on that, and then replaces the interpolations with the originals you could easily break the intent of the code:

After pre-evaluation, "css-in-js" would see this input:
```js
const Sort = styled.div`
   background:black;
   appearance:none;cursor:pointer;
`
```
An autofix would with order set to alphabetical would return:
```js
const fragment = `
  appearance: none;
  cursor: pointer;
`

const Sort = styled.div`
  appearance: none;
  ${fragment}
`
```
The auto fix has assumed it is safe to switch rules, when it is not due to the interpolation. This is where things get very tricky.
With a processor, things are much simpler:
1. Take input code and generate a CSS like file with the same line numbers
2. Stylelint parses that and returns results
3. Map results to original file.

With pre-evaluation, you can detect more errors:
```js
const invalidSelector = 'invalid'
function brandColor() {
  return 'notAColor'
}

const button = styled.button`
  color: ${brandColor()}; /* A */
  ${{ notARule: true }} /* B */

  ${invalidSelector} { /* C */
      appearance: none;
      cursor: pointer;
      background: black; /* D */
   }
`
``` 
There needs to be some way to report errors for A, B, C and have D be safely moved. Not sure how to do that yet. PostCSS doesn't evaluate template literals so it would appear proxying it with a processor would be one way, but it is pretty.

**Comment by brandonkal** [comment]
In fact, it would be very powerful test all known outputs of an interpolation: 
```js
const theme =  {
  small: '10em',
  large: '50em'
}

const Article = styled.article`
  width: $${props => props.big ? theme.large : theme.small}px
`
```
Error: 50empx and 10empx not valid.

**Comment by imbsky** [comment]
In my environment it seems that 'css-in-js' option works correctly, so I close this issue.

**Comment by imbsky** [comment]
I just wanted to ask if it's possible to replace linaria parser with the css-in-js option of stylelint. And linaria config had very few configs, so I decided to write my own config.
