### ISSUE TITLE
stylelint complains about :global selector

### ISSUE THREAD

**Issue by nhooyr** [callstack/linaria#443]
```
// https://github.com/callstack/linaria/blob/60962090410ea3878f3c190817c1667a124d7df9/docs/BASICS.md#adding-global-styles
export const globalCSS = css`
  :global() {
    @import-sanitize;
  }
`
```

Running stylelint on the above code will give:

```
src/App.tsx
 9:3  ✖  Unexpected unknown pseudo-class selector ":global"   selector-pseudo-class-no-unknown
```

My stylelint config is:

```
extends:
  - stylelint-config-recommended
  - linaria/stylelint-config
```

**Comment by nhooyr** [comment]
`:global(html)` works. See #450

**Comment by nhooyr** [comment]
Nvm it doesn't, my bad.

**Comment by satya164** [comment]
We can probably add `ignorePseudoClasses: ["global()"]` in the default config

**Comment by PaulRBerg** [comment]
This also happens for `:export`.

**Comment by nhooyr** [comment]
Going to close as it has been a while and I'm not sure if this is relevant anymore.

**Comment by ricardo-teixeira** [comment]
For those who still have this problem, just add this rule to your .stylelintrc:
```
 "rules": {
    ...
    "selector-pseudo-class-no-unknown": [
      true,
      {
        "ignorePseudoClasses": ["global"]
      }
    ]
  }
```
Reference: https://stylelint.io/user-guide/configure#rules

**Comment by andreachalmers** [comment]
> For those who still have this problem, just add this rule to your .stylelintrc:
> 
> ```
>  "rules": {
>     ...
>     "selector-pseudo-class-no-unknown": [
>       true,
>       {
>         "ignorePseudoClasses": ["global"]
>       }
>     ]
>   }
> ```
> 
> Reference: https://stylelint.io/user-guide/configure#rules

Happy to have found this @ricardo-teixeira :) This does help with removing the export issue but only on that line and not the content of the respective export.

For example:
in the `scss` file:

```css
:export {
    red: $color--red;
    black: $color--black;
    gray: $color--gray;
    inputbar: linear-gradient(0deg, #{$color--gray-light} 0%, #{$color--gray-light} 100%);
}
``` 

In the `.stylelintrc` as you mentioned

```js
'selector-pseudo-class-no-unknown': [
            true,
            {
                "ignorePseudoClasses": ["export"]
            }
        ],
```
however the properties in the `:export{} ` are unknown:
![image](https://user-images.githubusercontent.com/12075190/209989911-7dc4f0dc-5f73-43f8-aa30-b0eea91f1892.png)

Were you able to find a solution for this?
