### ISSUE TITLE
Not working in Gatsby production mode

### ISSUE THREAD

**Issue by ryan-ds** [callstack/linaria#444]
## Environment

node: `8.12.0`
gatsby: `2.12.0`
gatsby-plugin-linaria: `1.2.0`
linaria: `1.3.1`
react: `16.8.6`

## Description

- I have created a new starter project with Gatsby via the following command:
`npx gatsby new my-default-starter https://github.com/gatsbyjs/gatsby-starter-default`

- Then added the required packages via:
`yarn add gatsby-plugin-linaria linaria`

- After that, I added the `gatsby-plugin-linaria` plugin at the end of plugins in the `gatsby-config.js` file.

- Lastly I edited the `components/header.js` file to reflect the following:
```js
import { Link } from 'gatsby'
import { styled } from 'linaria/react'
import PropTypes from 'prop-types'
import React from 'react'

const MainHeader = styled.header`
  background: rebeccapurple;
  margin-bottom: 1.45rem;
`

const Header = ({ siteTitle }) => (
  <MainHeader>
    <div
      style={{
        margin: `0 auto`,
        maxWidth: 960,
        padding: `1.45rem 1.0875rem`,
      }}
    >
      <h1 style={{ margin: 0 }}>
        <Link
          to="/"
          style={{
            color: `white`,
            textDecoration: `none`,
          }}
        >
          {siteTitle}
        </Link>
      </h1>
    </div>
  </MainHeader>
)

Header.propTypes = {
  siteTitle: PropTypes.string,
}

Header.defaultProps = {
  siteTitle: ``,
}

export default Header
```

---

After following these steps, I ran the project in development via `npm start` and it works flawlessly.

But running in production via `npm run build && npm run serve`, the build is successful  styles do not get applied. The class is applied but the styles are not reflected anywhere.

![image](https://user-images.githubusercontent.com/38418557/60515606-9dd0b000-9cf9-11e9-9e96-2dd47dc59f32.png)

I also tried deleting the `public`, `.cache` and `linaria-cache` folders but it didn't make any difference.

**Comment by cometkim** [comment]
Resolved in gatsby-plugin-linaria v1.2.2, @ryan-ds You can close this 😉 
(See https://github.com/silvenon/gatsby-plugin-linaria/issues/17)
