### ISSUE TITLE
Inline styling uses JavaScript DOM style names, not CSS property.

### ISSUE THREAD

**Issue by lqez** [callstack/linaria#455]
https://github.com/callstack/linaria/blob/master/docs/DYNAMIC_STYLES.md#inline-styles
shows how to use inline styling. But we should use JavaScript DOM style property names(like `fontFamily`), not CSS property(like `font-family`).

e.g.
```JSX
<div class={button} style={{ fontFamily: `sans-serif` }}>Sans-serif</div>
```

This fails.
```JSX
<div class={button} style={{ font-family: `sans-serif` }}>Sans-serif</div>
```

Expected behavior:
Accept CSS property names. Or, this design has to be documented, at least.

**Comment by brandonkal** [comment]
This is documented React behavior. This is nothing unique to this linrary. It makes no sense for Linaria to change the behavior of JSX.

**Comment by lqez** [comment]
Thanks @brandonkal.
