### ISSUE TITLE
Cyclic imports result in infinite loop

### ISSUE THREAD

**Issue by samdenty** [callstack/linaria#457]
## Description

I was using linaria with gatsby, modified a few components and it froze. Through debugging, I narrowed it down to cyclic imports not working

## Reproducible Demo

https://github.com/samdenty/linaria-cyclic - `yarn; yarn build`

**a.js**
```js
import { styled } from 'linaria/react'
import { B } from './b.js'

export const margin = 10
const A = styled.div`margin: ${margin}`
```

**b.js**
```js
import { styled } from 'linaria/react'
import { margin } from './a.js'

const B = styled.div`margin: ${margin}`
```

**Comment by jayu** [comment]
It will no longer be an issue with the `1.4.0` release. I just checked with `1.4.0-beta.4` and it works fine
