### ISSUE TITLE
Missing type definitions for js files in the root directory

### ISSUE THREAD

**Issue by dkamyshov** [callstack/linaria#460]
## Environment

NodeJS, yarn

linaria versions: linaria@1.4.0-alpha.0 and up

## Description

TS declaration files for JS files in the root directory (react.js, server.js, etc) are missing.

## Reproducible Demo

https://github.com/dkamyshov/linaria-missing-ts-report

Clone this repo and run `$ yarn`.

**Workaround**

Import stuff directly from the 'lib' directory: `import { styled } from 'linaria/lib/react';`

Is this behaviour intentional?

**Comment by jayu** [comment]
this is an inactive duplicate of #520 closing, please refer to #520
