### ISSUE TITLE
Is it possible to use Object Style syntax?

### ISSUE THREAD

**Issue by peduarte** [callstack/linaria#464]
Hello 👋 

I'm curious about how my team can use Linaria for our [product](https://modulz.app) and public [design system](https://radix.modulz.app).

The first question I have is if it's possible to use Object Style syntax rather than template strings?

```js
const Title = styled.h1({ color: 'red' })
```

Many thanks!

**Comment by thomkrupa** [comment]
Hey, you can use something like:

```javascript
const sectionStyles = css`
  ${{
    marginTop: '1rem',
    background: 'green',
  }};
`

<section className={sectionStyles} />
```

That's how I use Linaria in one of my projects. Not sure if there is a better way to use Object Style.

**Comment by peduarte** [comment]
@thomkrupa Hmmm, seeps a bit of a workaround but I appreciate the reply. Thank you

**Comment by jayu** [comment]
Hey, if you would like to have this feature, please open a new issue with a feature request. However, it might be tricky to introduce this syntax to linaria since we are strongly basing on `TaggedTemplateExpressions`
