### ISSUE TITLE
Brunch bundler integration

### ISSUE THREAD

**Issue by roper79** [callstack/linaria#467]
https://brunch.io/

**Comment by jayu** [comment]
We would appreciate if someone would at least check how much work it would be to support this bundler and whether its popularity is high enough to take up this effort.

**Comment by matthewoates** [comment]
0 activity for 3 years - I think it's safe to close, especially given the effort that went into the original request.

**Comment by jayu** [comment]
Fair enough 🤪 I didn't hear about brunch since I first seen this issue
