### ISSUE TITLE
Using the "styled" tag in runtime is not supported -- unused components

### ISSUE THREAD

**Issue by brandonkal** [callstack/linaria#471]
## Environment

Storybook + webpack + linaria@develop

## Description

When a styled component is unused, the error will be thrown during HMR. On one hand, it is nice to have an error when a component is unused, but unfortunately it breaks the build when this error is thrown.

## Reproducible Demo

```js
const Unused = styled.div``
// note that this declaration is not exported.

function Used() {
  //...
}

**Comment by jayu** [comment]
We definitely should support this kind of case. Maybe we should replace errors to some kind of warning for development.

**Comment by jayu** [comment]
I cannot repro this with `1.4.0-beta.4`
