### ISSUE TITLE
Additional unitless properties

### ISSUE THREAD

**Issue by brandonkal** [callstack/linaria#473]
animation: true,
  baselineShift: true,
  borderImage: true,
  fontSizeAdjust: true,
  gridArea: true,
  maskBorder: true,
  maskBorderOutset: true,
  maskBorderSlice: true,
  maskBorderWidth: true,
  maxLines: true,
  shapeImageThreshold: true,

**Comment by jayu** [comment]
This issue is not very informative :P If you decide to update description let me know and I will reopen

**Comment by brandonkal** [comment]
Linaria was doing some special logic on numbers that are unitless (i.e. they don't require px, em, etc). The logic was adding "px" when it encounters a unitless number which is incorrect for the CSS properties above. React also has this issue as well.

**Comment by jayu** [comment]
Thanks, any repro appreciated 😊

**Comment by jayu** [comment]
I tried but could not repro this one. The code below result in values without `px` suffix

```
styled.h1`
  grid-area: ${getPadding()};
  border-image: 50 round;
`
```
