### ISSUE TITLE
Specify the path for the babel config?

### ISSUE THREAD

**Issue by Pixelatex** [callstack/linaria#478]
## Ask your Question

So it seems like linaria only uses the babel config in your root... is there some other way I can specify this? Like passing the config manually or specifying a path to where it is?

**Comment by jayu** [comment]
Do you use linaria as babel plugin or with bundler like webpack? What is you use case for specifying path to babel config?

**Comment by Jayphen** [comment]
I'd like to be able to specify a path to the babel config as I am using Linaria in a monorepo where the config does not necessarily live in the root of the app.

**Comment by satya164** [comment]
@Jayphen how do you run linaria? you can also specify same options in the babel plugin config as well as webpack config (or reuse config file: `...require('/path/to/linaria.config.js)'`)

**Comment by Jayphen** [comment]
I'm working on a framework that uses Linaria internally & handles the build process for consuming apps - I don't want them to have to have a babel config in the root of their app.

So does this mean the [first line here](https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#pre-requisites) is not entirely accurate?

Do you mean that I should just pass the babel config to the `babelOptions` setting in `linaria.config.js`?
