### ISSUE TITLE
Babel wouldn't preprocess `import { styled as M } from 'linaria/react';`

### ISSUE THREAD

**Issue by eldeni** [callstack/linaria#488]
## Environment
```
"linaria": "^1.3.1",
"react": "^16.8.6",
"webpack": "^4.33.0",
```

## Description
Babel wouldn't preprocess 
```ts
import { styled as M } from 'linaria/react';

const SomeComponent = M.div`...`;
```

while the following works
```ts
import { styled } from 'linaria/react';

const SomeComponent = styled.div`...`;
```

FYI, I use `linaria` and `styled-components` at the same time (for experiment purpose), and this issue came about while I was avoiding the name collision.

If this is an intended behavior, I believe the document should at least mention it.

**Comment by evp3103** [comment]
This issue blocks the replacing of styled-components for linaria during build. Instead of you can replace the named import of styled with a default. It is necessary to maintain compatibility with the most popular css-in-js library for the promotion of your project

**Comment by Jayphen** [comment]
I have opened a PR for this at https://github.com/callstack/linaria/pull/544

**Comment by Anber** [comment]
Fixed by @Jayphen and will be released in the next 1.4-beta.

**Comment by Anber** [comment]
@evp3103 btw, I have [small babel-plugin](https://github.com/Anber/linaria-interop) for interop between Linaria and Styled/Emotion. Maybe you will found it useful.

**Comment by evp3103** [comment]
@Anber, Thanks, is your plugin only to resolve imports? What about keyframes?

**Comment by Anber** [comment]
@evp3103 it currently supports only interpolation of linaria-components in styled/emotion components. It was enough for us for migration, but if you need more, feel free for creating an issue/PR :)
