### ISSUE TITLE
Support target another linaria styled components

### ISSUE THREAD

**Issue by phmngocnghia** [callstack/linaria#492]
!-- Describe the requested Feature -->
Support select another linaria styled components
https://emotion.sh/docs/styled#targeting-another-emotion-component
https://www.styled-components.com/docs/advanced#referring-to-other-components

## Motivation
The element, which I want to target, contains both linaria elements and normal react elements. I want to target linaria elements.

**Comment by jayu** [comment]
Can you provide some code sample in which you would like to use it?

**Comment by jayu** [comment]
The behavior you are requesting is currently supported https://github.com/callstack/linaria/blob/master/docs/BASICS.md#referring-to-another-component-or-class-name
