### ISSUE TITLE
Is repo actively maintained? It looks like not🙅‍♀️

### ISSUE THREAD

**Issue by Whispers12** [callstack/linaria#500]
So, it looks like its abandoned repository. Lack of community communication, issuing support doesn't exist at all. So I want to start a project with some CSS-in-js solution. Linaria at first glance seems very good (at least a lot of twitter influencers actively promote this solution), but if we see on help and support, all in all, you understand that linaria is very overrated.

So I think Emotion and Styled-components are still the best solutions for CSS-in-js styling.

**Comment by thymikee** [comment]
You're right that we could be better at communicating our intents. We (me, @zamotany and @satya164) currently don't have bandwidth to maintain this repository as we'd like. However, there's amazing @Anber who is actively contributing his time to improve Linaria, and he's a direct collaborator to this repository. We're currently working with him on pushing this project forward.

Linaria offers a similar API to styled-components, so until it's stabilized, feel free to use it :)
