### ISSUE TITLE
Import existing SASS mixins?

### ISSUE THREAD

**Issue by kallebornemark** [callstack/linaria#502]
Is it possible to import and make use of existing SASS mixins with Linaria?

**Comment by Anber** [comment]
Probably yes. Linaria just extracts plain text from template tags and then you can process it as simple css files.
If you need help, you can create a sample repository and I’ll take a look.

**Comment by kallebornemark** [comment]
Not able to create a repo at the moment, but perhaps I can explain myself.

I have an NPM package that contains some mixins, and I want to use this in a React component using Linaria. I currently have something like this:

```js
import React from 'react';
import  '@ingka/grid/style.scss';
import { styled } from 'linaria/react';

const StyledMyComponent = styled.div`
  background-color: red;
  @include my-mixin($arg1: 3, $arg2: 9, $arg3: 12);
`;

export const MyComponent = ({ children }) => {
  return <StyledMyComponent>{children}</StyledMyComponent>;
};
```

The output of the generated `MyComponent.linaria.css`:
```css
@include my-component( $arg1:3, $arg2:9, $arg3:12 );.s10vu26i{background-color:red;}
/*# <sourcemap stuff> */
```

Do I need a Webpack loader to process the `@include` in the generated CSS file in a succeeding build step?

**Comment by Anber** [comment]
Yep, you can use Webpack or Rollup like it is described here https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md

**Comment by jayu** [comment]
Did you manage to make work @kallebornemark ?

**Comment by shiro** [comment]
Sorry for replying to old issues, but I thought clearing this up might be easier than opening a separate issue.

As stated above linaria produces:
```
@include my-mixin( $arg1:3, $arg2:9, $arg3:12 );.s10vu26i{background-color:red;}
```
but should produce:
```
.s10vu26i{background-color:red; @include my-mixin( $arg1:3, $arg2:9, $arg3:12 );}
```
The mixins seem to be dragged out into the root scope rather than be included in the extracted classes which of course produces an error.

If linaria really extracted the plain text the mixin would be in the same scope so something else seems to be going on, maybe the `@` symbol confuses it?

After fixing this I'm certain it would actually be possible to use `scss` mixins in linaria which sounds amazing IMO :P

**Comment by czabaj** [comment]
I tried SCSS with linaria and came to the same limitations (the curly braces in SCSS expression are removed thus the sass fails to process the expression), but I realized that in linaria, we shall use JavaScript for such expressions in tagged templates.

The use of sass in linaria will solve the style-and-code colocation problem and allows us to use some legacy code, but dropping the sass and using JavaScript is the right way to go.

**Comment by Yuyz0112** [comment]
Years later, I found the same issue as @shiro.

After some experiments, I fixed the issue by setting `preprocessor: "none"`.
