### ISSUE TITLE
Doesn't seem to work with safe-area-inset-* env variables

### ISSUE THREAD

**Issue by IljaDaderko** [callstack/linaria#508]
## Environment
linaria: 1.3.1
device: iPhoneX
browser: Safari
iOS: 13.x

## Description
Safari exposes `safe-area-inset-*` variables to account for things like iphone notch https://developer.mozilla.org/en-US/docs/Web/CSS/env

But it seems like no matter what I try I can't het these to work with linaria. Are css variables / env variables supported?

## Reproducible Demo
add _<meta name="viewport" content="... **viewport-fit=cover"**>_ to your document

```
const content = css`
  padding-top: env(safe-area-inset-top, 20px);
  padding-bottom: env(safe-area-inset-bottom, 20px);
`;
```

**Comment by Anber** [comment]
We extract CSS almost as it is and everything should work. Could you please provide a repo with a reproducible demo?

**Comment by islam-belfihadj** [comment]
d
