### ISSUE TITLE
Why has the updates on this lib stopped?

### ISSUE THREAD

**Issue by vongohren** [callstack/linaria#509]
## Ask your Question

I wonder what is the future of this lib! I like it alot, but it seems to have stopped

**Comment by sgoll** [comment]
I was wondering the same thing.

**Comment by Anber** [comment]
We have published the first beta of 1.4, which is mostly about TypeScript and general performance. After 1.4 we will focus on further performance optimization (it will probably be based on the @brandonkal's PR#437) and better supporting of JS during evaluation stage (PR #499).
