### ISSUE TITLE
Trying to use linaria in a monorepo SSR

### ISSUE THREAD

**Issue by vongohren** [callstack/linaria#510]
## Description

Trying to build a minimal package with linaria
Getting this error on webpack
```
$ webpack
Hash: 143cb96d3038294e6415
Version: webpack 4.41.2
Time: 4154ms
Built at: 12/09/2019 3:39:15 PM
 2 assets
Entrypoint main = main.js main.js.map
 [2] ./src/index.js 358 bytes {0} [built]
[10] ./.linaria-cache/src/index.linaria.css 5.19 KiB {0} [built] [failed] [1 error]
[11] ./node_modules/@emotion/is-prop-valid/dist/is-prop-valid.browser.esm.js + 1 modules 4.36 KiB {0} [built]
     |    2 modules
    + 9 hidden modules

ERROR in ./.linaria-cache/src/index.linaria.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: this[MODULE_TYPE] is not a function
    at childCompiler.runAsChild (/Users/snorre/code/fouc-example/packages/linaria-BROKEN/node_modules/mini-css-extract-plugin/dist/loader.js:170:24)
    at compile (/Users/snorre/code/fouc-example/packages/linaria-BROKEN/node_modules/webpack/lib/Compiler.js:343:11)
    at hooks.afterCompile.callAsync.err (/Users/snorre/code/fouc-example/packages/linaria-BROKEN/node_modules/webpack/lib/Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/snorre/code/fouc-example/packages/linaria-BROKEN/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
```

## Reproducible Demo
Move the linaria broken folder into packages and rename, then build and run. It crashes with the description above.
https://github.com/vongohren/fouc-example

**Comment by ShanonJackson** [comment]
Currently have a working monorepo with NextJS + Linaria; Can confirm it does indeed work. A quick skim read of your demo is looks like you have "next-transpile-modules", you'll also need next-css OR a fork of next-css with ignoreOrder: true turned on in MiniCssExtractPlugin (perferred approach). You'll also need to follow the config in the with-linaria example in NextJS repository here:
https://github.com/zeit/next.js/tree/canary/examples/with-linaria

Turn on these things let me know if the error persists and also update inbuilt support for linaria in next here.
https://github.com/zeit/next.js/issues/9931

**Comment by vongohren** [comment]
@ShanonJackson thanks for the response, but I turned in the end to emotion js and got it working with next.js. I went through many different ways of finding the right way to do this, but I felt linaria was not up to speed and being updated enough for us to take into our system

**Comment by ShanonJackson** [comment]
Before you get too heavily invested in emotion or styled-components i would say that for SSR based applications (ESPECIALLY) NextJS you're going to want to prefer css-modules to linaria if you're leaving. NextJS 9.2.0+ comes with inbuilt support for css-modules now and they're adding scss support extremely soon. Both styled-components and emotion come with a significantly higher runtime cost that makes the initial page load alot slower (since you need to run another function to collect all the styles and render them to the head; but also because emotion wraps every single element in two context consumers).

**Comment by vongohren** [comment]
@ShanonJackson good arguments! I really liked how easy it was to use linaria with next, it was the first thing I got working. But was concerned that it was not beeing updated. This is not just for next js, it's a component library. So should work everywhere. But I will take it into consideration
