### ISSUE TITLE
Linaria uses all available memory using webpack-dev-server

### ISSUE THREAD

**Issue by jarodpeachey** [callstack/linaria#515]
## Description

Linaria is set up correctly, but when I run webpack-dev-server, I get an error that says FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory. This error comes from my local machine, but it's because Linaria uses up a ton of memory.

The repo has over 144 files which use Linaria.

If there's any way to disable using the memory, that would be awesome. It seems like all the files are generated in linaria-cache, but webpack won't move on because all the memory is taken up.

## Reproducible Demo

Clone the repo, and run npm install, then run npm start
https://github.com/jarodpeachey/WebApp/tree/LinariaTest

**Comment by Anber** [comment]
It was probably happened because of circular references in your project. `1.4.0-beta.0` should help. Please let us know if you still have that error in 1.4.
