### ISSUE TITLE
Doesn't work in nextjs if granularChunks are enabled until page is refreshed

### ISSUE THREAD

**Issue by IljaDaderko** [callstack/linaria#516]
## Environment
```
"linaria": "1.4.0-alpha.1",
"next": "9.1.6"
```

## Description

I am using linaria inside nextjs v9, where my production builds work correctly as expected. There is new experimental feature called `granularChunks`. When it is enabled, substantial positive bundle size differences are visible, plus it takes better advantage of http2 parallel requests by loading more smaller chunks rather than one bigger file.

However linaria seems to break with it in a way where styles are broken on initial page access, but once page is refreshed they work fine.

As a side note I notice same behaviour without `granularChunks` disabled in dev mode. I need to refresh pages in order for styles to take effect.

**Comment by IljaDaderko** [comment]
I did some further digging and found that if you have css that doesn't need to be evaluated, there is no issue. But as soon as you use `${someVar}` or `${require(...)}` etc... in your `css`, this weird behaviour comes up where styles seem broken initially and work fine after refresh.

**Comment by Anber** [comment]
@Asimetriq May I ask you to provide a sample repo with this issue?

**Comment by IljaDaderko** [comment]
@Anber of-course, I was just working on it actually. I noticed it worked in some cases and not the others. I will link it to this issue tomorrow once I wrap it up 👍(a lot of mess in it atm)

**Comment by IljaDaderko** [comment]
I can't get any of my minimal project reproductions to trigger this error, so I think it must be something specific I am doing in my own project or it's size. I came across this issue in next js https://github.com/zeit/next-plugins/issues/282 and this is basically what I experience (but not just in dev, also in production when using `granularChunks`). They have few fixes there that seem to work, but are hacky.

I'm not sure if `next-css` is enough for linaria either, maybe it needs some custom config? In which case official nextjs example for linaria https://github.com/zeit/next.js/tree/canary/examples/with-linaria might be wrong.

Will close this issue, I think it is related to next js / next js example.
