### ISSUE TITLE
[1.4.0-beta.0] A build error

### ISSUE THREAD

**Issue by Anber** [callstack/linaria#517]
This problem was reported by @Guria (#495)

## Description

```
node_modules/react-scripts/node_modules/@babel/runtime/helpers/esm/taggedTemplateLiteral.js:1
export default function _taggedTemplateLiteral(strings, raw) {
^^^^^^

SyntaxError: Unexpected token 'export'
```

**Comment by Anber** [comment]
@Guria could you please provide some details?

**Comment by Guria** [comment]
Will try to dig in and provide reproduction

**Comment by matiasbuildops** [comment]
After upgrading to 1.4.0-beta.0, seeing a the same (or at least, very similar) error message:
```
Module build failed (from ./node_modules/linaria/loader.js):
...\node_modules\react-dnd\dist\esm\index.js:1
export * from './common';

SyntaxError: Unexpected token export
    at new Script (vm.js:83:7)
    at Module.evaluate (...\node_modules\linaria\lib\babel\module.js:200:18)
    at Module.<anonymous> (...\node_modules\linaria\lib\babel\module.js:184:13)
    at Module.require (...\node_modules\linaria\lib\babel\module.js:134:23)
    at C:\Users\matias\code\bops\buildhero-dispatchboard\lib\components\Component2.js:32:17
    at Script.runInContext (vm.js:133:20)
    at Module.evaluate (...\node_modules\linaria\lib\babel\module.js:203:12)
    at Module.<anonymous> (...\node_modules\linaria\lib\babel\module.js:184:13)
    at Module.require (...\node_modules\linaria\lib\babel\module.js:134:23)
    at C:\Users\matias\code\bops\buildhero-dispatchboard\lib\components\Component1.js:3:22
 @ ../lib/components/MainView.js
 @ ../lib/index.js
 @ ./src/App.js
 @ ./src/index.js
```

Not sure if @Guria is also seeing it from linaria *loader*? Seems to me that for some reason, babel is somehow getting confused when getting run through linaria, as both errors seem to be triggered by unrelated modules having ES6 code being included but not getting transpiled by babel?

filenames anonymized a bit; but the use case is basically styled(Component2) (and it works a-ok without that nesting) so seems like a possible regression from #343? Will try to get a better reproduction going as, well.

**Comment by Anber** [comment]
@Guria @matiasbuildops hi guys. Any news here?

**Comment by Guria** [comment]
@anber clean cra + linaria has no such problem. I am still wondering what is needed to add to reproduce this problem

**Comment by Guria** [comment]
@matiasbuildops could you try to describe your setup. Are you using yarn workspaces or something similar?

**Comment by matiasbuildops** [comment]
Hi @Guria!

I was not using yarn workspaces when I hit that but after investigating another issue relating to them (see #529), I think I might know what is causing at least my report - not sure if your error was raised in loader, as well? As these both seem to be somehow trying to import non-babelized files, I'm guessing both of these originate from the call to babel in [transform.ts](https://github.com/callstack/linaria/blob/29ffee9a02b7a9286f961acc8f3e0e0e71592f16/src/transform.ts#L30) that only passes in linaria/loader as the presets and not what the user had defined in their babelrc or anything like that. 

However, I'm really not at all sure why or when transform() actually gets called on files or whether this is/was a side-effect of other configuration so can't do more than a guess for now. Will try to investigate further when I have some time.

I can add one more datapoint, though. In my case, the problematic use was one module importing another module that was importing linaria. eg; all the problems happened when the code was running inside node_modules which is why I feel it could just be a side-effect of babel ignoring node_modules at some point above linaria? Not sure if that makes sense either but hey..

**Comment by Guria** [comment]
@matiasbuildops Hi. I have applied your patch and seems it works for me

**Comment by Guria** [comment]
@Anber could we release beta.1 with above patch?

**Comment by Anber** [comment]
@Guria probably, yes. I'll check regressions and build the next beta tomorrow.

**Comment by Guria** [comment]
it's weird. this patch works for me on local machine, but doesn't work on CI where it applied with `patch-package`

**Comment by Anber** [comment]
@Guria `beta.2` has been fixed. Could you please check it?

**Comment by Guria** [comment]
Didn't worked unfortunately :(
![image](https://user-images.githubusercontent.com/36270/74108563-02f45a00-4b95-11ea-8c4e-eef6136f56b8.png)

Will try to investigate further

**Comment by Guria** [comment]
ok, I digged in a bit now.
So it seems [babel.transformFromAstSync](https://github.com/callstack/linaria/blob/0b820afe61b9ea459b70a4a877249b0e62aa3ce7/src/transform.ts#L30) fails to parse with following error for some of style files:
```
node_modules/@babel/runtime/helpers/esm/taggedTemplateLiteral.js:1
(function (exports) { export default function _taggedTemplateLiteral(strings, raw) {
                      ^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:88:7)
    at Module.evaluate (./node_modules/linaria/lib/babel/module.js:264:20)
    at Module.Object.assign.ensure (./node_modules/linaria/lib/babel/module.js:177:15)
    at ./web/desktop/VisitCardMultiService/styles.ts:10:54
    at ./web/desktop/VisitCardMultiService/styles.ts:434:3
    at Script.runInContext (vm.js:131:20)
    at Module.evaluate (./node_modules/linaria/lib/babel/module.js:267:12)
    at Module.Object.assign.ensure (./node_modules/linaria/lib/babel/module.js:177:15)
    at ./web/desktop/VisitCardMultiService/ServiceRow/styles.ts:11:19
    at ./web/desktop/VisitCardMultiService/ServiceRow/styles.ts:20:3 {
  code: 'BABEL_TRANSFORM_ERROR'
}
```

I've checked the source of this files and common part for them is that they have import from another style.tsx file.

**Comment by Guria** [comment]
The only working patch I were succeded for now is replacing `export default ` with `module.exports = ` in `node_modules/@babel/runtime/helpers/esm/taggedTemplateLiteral.js`.
But I fill that isn't an appropriate solution :)

**Comment by Anber** [comment]
@Guria Could you please try that workaround https://github.com/callstack/linaria/issues/540#issuecomment-585228851?

**Comment by skywalker512** [comment]
I also have this problem. I have configured the following information in **linaria.config.js** to solve this problem. It seems that Linaria does not convert the content in **node_modules** by default. You need to specify it manually.

```js
module.exports = {
	ignore: /node_modules[\/\\](?!some-module|other-module)/
}
```

You can get more information here https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md#options

**Comment by jayu** [comment]
I will try to reproduce it and see if it can be solved.

**Comment by Anber** [comment]
Fixed

**Comment by Guria** [comment]
just tried `linaria@^2.0.0-alpha.5` and it builds without errors,
but when run jest linaria is failing on parsing typescript syntax in styles files now.

**Comment by Guria** [comment]
nevermind. it looks more like issue of craco-linaria

**Comment by Guria** [comment]
@Anber btw 1.4.10-alpha still errors for me

**Comment by Anber** [comment]
@Guria it's because `2.0` uses `shaker` strategy as a default strategy, whereas `1.4` uses `extractor`. You can find more details [here](https://github.com/callstack/linaria/blob/master/docs/HOW_IT_WORKS.md#evaluators)
