### ISSUE TITLE
Support Parcel 2 Plugin API

### ISSUE THREAD

**Issue by Pytal** [callstack/linaria#519]
## Describe the feature

Parcel 2 implemented a plugin api, and it would be great if a `parcel-transformer-linaria` package could be made!

There are already plugins for webpack with [linaria/loader](https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#webpack) and rollup with [linaria/rollup](https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#rollup), it'd be great to have Parcel 2 support as well!

## Motivation

Support new [Parcel 2](https://medium.com/@devongovett/parcel-2-0-0-alpha-1-is-here-8b160c6e3f7e) extensibility!

**Comment by jayu** [comment]
We should extend https://github.com/callstack/parcel-plugin-linaria to support Parcel 2. 
I believe a long term goal would be to extract `webpack` and `rollup` plugins to separate packages.

**Comment by huw** [comment]
Raised an issue ([#20](https://github.com/callstack/parcel-plugin-linaria/issues/20)) over there to track this work

**Comment by kaifaty** [comment]
Why this issue marked as complete?
There is no plugin for Parsel 2  for now. Have any plans to add it?
