### ISSUE TITLE
Ensure we throw nice errors when users do something unsupported

### ISSUE THREAD

**Issue by satya164** [callstack/linaria#52]
### Using undefined variables

Handled in #81

### Errors thrown during preval

Handled in #111 

If a function throws an error during `preval`, we should catch it and throw nice error with proper stacktrace.

```js
const test = () => {
  throw new Error('Some weird error');
}

const test = css`
  color: ${test()};
`;
```

### Typos in CSS

If the user mistyped a variable name, we could print an error instead of generating invalid CSS. For example, say we get `undefined` during interpolation:

```js
const colors = {
  blue: 'blue'
}

cont title = css`
  color: ${colors.bleu};
`
```

**Comment by zamotany** [comment]
@satya164 

> Typos in CSS
How do you want to catch this?

**Comment by satya164** [comment]
@zamotany this can be done by the `css` function. If `Errors thrown during preval` works, it'll work automatically.
