### ISSUE TITLE
Unexpected token, expected "(" 

### ISSUE THREAD

**Issue by mattoni** [callstack/linaria#521]
## Environment

TSDX 0.9.0 using Rollup plugin ([https://github.com/jaredpalmer/tsdx](https://github.com/jaredpalmer/tsdx))
Linaria 1.4.0-beta.0 

Also using storybook for component lib w/ webpack plugin

## Description

This happens in both 1.3.0 and 1.4.0 beta. I try importing a stylesheet like so:

![image](https://user-images.githubusercontent.com/5110855/71742756-9ceb1900-2e17-11ea-87a9-68d2ba63e41d.png)

In storybook (compiling using webpack) this works fine. However, when I run it through the rollup plugin, I get this:

```
✓ Creating entry file 4.1 secs
(linaria plugin) SyntaxError: /Users/alexandermattoni/Development/cycle/cycle-ui/src/setup.ts_fdv18c.css: Unexpected token, expected "(" (1:8)

> 1 | @import url("https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,300italic,400italic,600,600italic,700,700italic,200,200italic");html{font-size:62.5%;height:100%;width:100%;margin:0;padding:0;box-sizing:border-box;}body{font-size:1.6rem;font-style:normal;line-height:1.825;text-rendering:auto;width:100%;height:100%;margin:0;padding:0;font-family:"Source Sans Pro",sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;}.s63fm5e *,.s63fm5e *:before,.s63fm5e *:after{box-sizing:inherit;}code{font-family:source-code-pro,Menlo,Monaco,Consolas,"Courier New", monospace;}input{box-sizing:border-box;}
    |         ^
```

If I remove the import line, it builds just fine. Looks like it's getting stuck there for some reason.

**Comment by mattoni** [comment]
It appears the removing the `/` from the end of the URL allows it to compile properly, i.e.

`https://fonts.googleapis.comcss?family=Source+Sans+Pro:400,300,300italic,400italic,600,600italic,700,700italic,200,200italic`

So there might be something there worth investigating.

**Comment by jayu** [comment]
might be related to #368 and #391

**Comment by TMaszko** [comment]
Hi, Thanks that you have opened this issue!
Could you provide repository where we can easily reproduce this bug?
Thanks in advance! :)

**Comment by layershifter** [comment]
This is an old issue and does not have reproduction, please try latest versions and open a new issue if it still happens.
