### ISSUE TITLE
Make unassigned css tag become global style

### ISSUE THREAD

**Issue by bolasblack** [callstack/linaria#526]
## Describe the feature

If linaria find there are a `css` tag didn't assign result to any variable, then transform it as global style.

For example:

```tsx
// SomeComponent.tsx
export const Modal: FC = () => null

css`
html.Modal__html--visible {
}
`
```

Currently it output:

```css
.SomeComponent0 html.Modal__html--visible {
}
```

I hope it can be:

```css
html.Modal__html--visible {
}
```

## Motivation

I know there is a `:global()` pseudo-selector, but it was added by stylis.js. Our team is using the sass pre-compiler, so the `:global` pseudo-selector is no longer working.

And in current design, if a `css` tag not assigned to any variable, it has virtually no effect, because no one can know the class name. So we may be able to add an option to the `linaria.config.js` to allow people to selectively enable this feature.

I also have another confusion:

```tsx
// I have already set `classNameSlug: '[title]'` in linaria.config.js

// Overview.tsx

// I want to create a component named `Overview`
export const Overview: FC = props => (
  <div className={Overview}>
  </div>
)

// I hope the root div can have a class name prefixed `Overview`, so I can write css in other file:
//
//   css`
//     .${Overview} {
//       ...
//     }
//   `
//
// How can I take this variable name?
export const Overview = css`
...
`
```

**Comment by Anber** [comment]
Hi @bolasblack 
I don't like the idea with unassigned `css` because it at least will cause 'unsued expression' in TS but we probably can introduce something like `globalCss`.

**Comment by bolasblack** [comment]
Hi @Anber, thanks for your reply!

> but we probably can introduce something like globalCss.

This idea looks good, expect this feature to be implemented :D 

And do you have any idea about how can I take the variable name?

**Comment by Anber** [comment]
Why do you need a variable name?
In your example you have variable names collision (`Overview` as a component and `Overview` as a name of css class) and it looks a bit confusing. It’s better to declare components with `styled` ( https://github.com/callstack/linaria/blob/master/docs/BASICS.md#styling-custom-components ) because then you can simply interpolate it in other `styled` and `css` tags (https://github.com/callstack/linaria/blob/master/docs/BASICS.md#referring-to-another-component-or-class-name).

**Comment by bolasblack** [comment]
Hi @Anber, thanks for your reply.

Because sometimes I want to write all the style code of a component in one place

For example, if we want to use `styled` tag to refactor this code:

```jsx
const WidgetMedal = ({info}) => (
    <section className={WidgetMedalCss}>
      <h1 className={`${WidgetMedalCss}-title`}>本月达成</h1>
      <p className={`${WidgetMedalCss}-hero`}>
        <span className={`${WidgetMedalCss}-hero-number`}>{info.days}</span>
        天
      </p>
      <p className={`${WidgetMedalCss}-rank`}>
        太棒了！你超过团队中 {formatPercent(info.teamRank)} 的用户啦！
      </p>
    </section>
)

// I hope `css` can be used in a similar way
const WidgetMedalCss = magicCss("WidgetMedal")`
    padding: 24px 26px;
    &-title {
      font-weight: normal;
      font-size: $fontSize;
    }
    &-hero {
      margin: 14px 0;
    }
    &-hero-number {
      font-size: 50px;
    }
    &-rank {
      color: $gray;
    }
}
`
```

Maybe we will create 5 components:

```jsx
<MedalContainer>
  <MedalTitle>本月达成</MedalTitle>
  <MedalHero>
    <MedalHeroNumber>{info.days}</MedalHeroNumber>
    天
  </MedalHero>
  <MedalRank>
    太棒了！你超过团队中 {formatPercent(info.teamRank)} 的用户啦！
  </MedalRank>
</MedalContainer>
```

But actually the style code is simple, creating 5 components is too cost-effective, and it is not good for the next maintenance work (because the style code is split into several places).

And if I write styles in `style` prop, This will make the code look complicated.

**Comment by Anber** [comment]
You can probably do something like this:
```javascript
export const UnstyledWidgetMedal = ({ className, info }) => (
    <section className={className}>
      <h1 className={`${className}-title`}>本月达成</h1>
      <p className={`${className}-hero`}>
        <span className={`${className}-hero-number`}>{info.days}</span>
        天
      </p>
      <p className={`${className}-rank`}>
        太棒了！你超过团队中 {formatPercent(info.teamRank)} 的用户啦！
      </p>
    </section>
)

export const WidgetMedal = styled(UnstyledWidgetMedal)`
    padding: 24px 26px;

    &-title {
      font-weight: normal;
      font-size: $fontSize;
    }
    &-hero {
      margin: 14px 0;
    }
    &-hero-number {
      font-size: 50px;
    }
    &-rank {
      color: $gray;
    }
}
```

**Comment by mikestopcontinues** [comment]
A globalCss helper would be great. I think the unused variable solution would get in the way of proper tree shaking.

**Comment by bolasblack** [comment]
Hi @Anber, sorry for the late reply, I tried you suggestion, and encountered an issue when I using linaria in TypeScript project:

<img width="1098" alt="图片" src="https://user-images.githubusercontent.com/382011/73172009-028fa400-413d-11ea-9016-2dde0bba30b5.png">

Here is the tsx webpack rule:

```js
      {
        test: /\.tsx?$/,
        use: [
          /* config.module.rule('ts').use('cache-loader') */
          {
            loader: 'cache-loader',
            options: {
              cacheDirectory: 'node_modules/.cache/ts-loader',
              cacheIdentifier: '{"typescript":"3.7.2","ts-loader":"5.4.5"}::{\n  "extends": "@c4605/toolconfs/tsconfig",\n  "compilerOptions": {\n    "jsx": "react",\n    "typeRoots": ["node_modules/@types"]\n  }\n}\n'
            }
          },
          /* config.module.rule('ts').use('babel-loader') */
          {
            loader: 'node_modules/poi/lib/webpack/babel-loader.js',
            options: {
              cacheDirectory: true,
              cacheCompression: false,
              cacheIdentifier: 'jsx:react::namedImports:undefined',
              babelrc: undefined,
              configFile: undefined
            }
          },
          /* config.module.rule('ts').use('linaria/loader') */
          {
            loader: 'linaria/loader',
            options: {
              sourceMap: true,
              preprocessor: 'none',
              cacheDirectory: 'node_modules/.cache/linaria-cache'
            }
          },
          /* config.module.rule('ts').use('ts-loader') */
          {
            loader: 'ts-loader',
            options: {
              transpileOnly: true,
              happyPackMode: false,
              configFile: 'tsconfig.json',
            }
          }
        ]
      }
```

This is `.linariarc.js`:

```js
module.exports = {
  displayName: true,
}
```

Did I missed any thing?

**Comment by jayu** [comment]
@bolasblack issue from your last comment seems not to be related to Linaria. 
As for support for global styles - it is already possible to have global styles defined with linaria. Introducing a special purpose `globaCSS` is not reasonable for me because it do not solve any problem and also introduces more code to maintain. In the end, global styles can be introduced by regular `*.css file.
