### ISSUE TITLE
Allow `classNameSlug` to be a function.

### ISSUE THREAD

**Issue by soluml** [callstack/linaria#541]
## Describe the feature
Currently the `classNameSlug` [option](https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md#options) can only be set as a string. This gives us some customization, however, it'd be nice to have the ability to set this property as a function with the title and hash coming in as arguments.  This would allow us to fully customize the class names to our project's needs.

## Motivation
Sometimes on projects we have to adhere to very strict naming conventions at a project or company level. Other times, I like to squish the class names as small as possible with something like [Sweat Map](https://github.com/soluml/SweatMap).

In either situation, a little flexibility here would be great if possible!

**Comment by Jayphen** [comment]
@soluml This should be in the next beta :)
