### ISSUE TITLE
Add styles to html

### ISSUE THREAD

**Issue by fanich37** [callstack/linaria#550]
Is there possibility to add styles to the `html` tag via `linaria`?
To clarify the question: how to apply global styles w/o passing them to any element?

**Comment by GuillaumeAmat** [comment]
You can use that: https://github.com/callstack/linaria/blob/master/docs/BASICS.md#adding-global-styles

**Comment by fanich37** [comment]
@GuillaumeAmat Thanks for the reply.
Yeah, I read it but didn't follow the idea it should be imported w/o any names like:
```js
import 'pathToStyle.js';
```
My bad.
