### ISSUE TITLE
Support for the "dash" symbol in the CSS identifiers

### ISSUE THREAD

**Issue by klimcode** [callstack/linaria#554]
## Dash is a valid symbol frequently used in CSS classnames.

Would be great to include this symbol in the sanitization regex here: "linaria/src/babel/utils/toValidCSSIdentifier.ts", so the regex will be like this:
`/[^-_0-9a-z]/gi`

## Motivation

Currently it's impossible to use this Slug "[title]-[hash]". The dash is converted to underscore.

The difference is significant: in the DevTools, double click on a classname "class-abcde" will select only the first part, so it's easy to copy the original classname.
But doubleclick on the "class_abcde" will select the scoped name which forces me to manually remove the hash from selection or select the classname not by doubleclick, but dragging the cursor over the original classname which is much slower and irritating.

**Comment by soluml** [comment]
To add to this issue, there are actually thousands of valid characters beyond the regex above. Mathias Bynens has a [great write up about escaping normally invalid characters for CSS class names](https://mathiasbynens.be/notes/css-escapes) and in that same article he discusses many of character ranges that can be used, including emojis which don't require any escaping at all.

Unless there's a programmatic reason to have Linaria sanitize class names, I think it'd be better to just not sanitize them at all. I think it's fair to trust the developer to use the slug name correctly.  If you do need to sanitize certain characters, then I think it's important to document which characters will be filtered out or transformed and to what.

Finally, at the very least, I too would love to get dashes back 👍

**Comment by jayu** [comment]
Thanks for the research.  I would highly encourage you, folks, to check if changing this regexp does not break the test (it probably will break some snapshots) and what's more important -  builds.  I don't know why it is so strict, maybe there was a reason. From a maintainer perspective, the issue does not have very high priority but is reasonable so I look forward to community contributions :D  

Please check [how you can link](https://github.com/callstack/linaria/blob/master/CONTRIBUTING.md) the development version of Linaria into your existing project

**Comment by jayu** [comment]
Lol, didn't notice the PR is already there 😅 Thanks!

**Comment by soluml** [comment]
PR #564  has merged, so I think this can be closed once available.  Thanks everyone!
