### ISSUE TITLE
Add shouldForwardProp method

### ISSUE THREAD

**Issue by Pytal** [callstack/linaria#555]
## Describe the feature
A `shouldForwardProp` config method should be added so that custom props don't leak into the DOM.

This feature was recently added to styled-components/styled-components#3006.

## Motivation
I often use custom `boolean` props to toggle styles but since `boolean` attributes are not valid in the DOM React complains about them.

`shouldForwardProp` would allow you to explicitly define which props should be passed to the DOM and which props are for internal use.

## Related Issues
#256

**Comment by jayu** [comment]
Hey @Pytal, could you provide a code example to visualize the problem?

**Comment by Pytal** [comment]
😅 Turns out the issue was with react-spring since I wrapped a react-spring component.
