### ISSUE TITLE
dev tools for chrome

### ISSUE THREAD

**Issue by duxiaofeng-github** [callstack/linaria#560]
## Ask your Question

is there any linaria dev tools for chrome?

Cos i need to identify those className hashes.

for example:
```
export function SomeComp() {
    return <div className={someCss}>123</div>;
}

const someCss = css`
  color: red;
`;
```

it will be transformed to:
```
.some-unrecognized-hash {
  color: red;
}
...
<div class="some-unrecognized-hash">123</div>
```

in some pages with complicated component structure, these hashes are hard to identify. one of my colleague who's not familiar with my code told me he can barely find the style of my components.

so, is there any way to solve this problem? any idea?

**Comment by thymikee** [comment]
You can turn on `displayName` in the config: https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md#options
If you're in React context, you can use React DevTools to identify components
