### ISSUE TITLE
Solve issue with core-js, check if we can remove or at least upgrade.

### ISSUE THREAD

**Issue by jayu** [callstack/linaria#561]
## Motivation

There are a few issues related to core-js. They are built errors and build performance issues.
We should check how we can address them. We need to investigate
- [ ] if we can remove `core-js` dependency
- [x] if we can upgrade `core-js` to most recent version
- [ ] check what stop of the maintenance of `core-js` means for us in terms of upgrading/removing a dependency https://github.com/zloirock/core-js/issues/548#issuecomment-494112872 and https://github.com/zloirock/core-js/issues/767

## Related Issues

#420 #468

**Comment by jayu** [comment]
Just found a PR that is a good step on moving forward, #420
babel-core is included in 

```
linaria/lib/babel/visitors/TaggedTemplateExpression.js
linaria/lib/babel/module.js
linaria/lib/transform.js
linaria/lib/loader.js
```
none of these modules is executed in the browser so polyfill is not needed.
If the author of the mentioned PR is right, we should be able to get rid of core-js by targeting node@8 in `babel-preset-env`

**Comment by satya164** [comment]
@jayu babel-core is not the same as core-js. core-js is a polyfill that different babel transforms add to the code. we're not importing it explicitly.

> we should be able to get rid of core-js by targeting node@8
I think we can't do that. We need to support browsers which may have different features/syntax available. We'll need to check which code is causing babel to include a polyfill and then change that code to some older syntax/API that doesn't need a polyfill.

**Comment by jayu** [comment]
Yes, I was tired while writing it, I meant `core-js` :D thanks @satya164
