### ISSUE TITLE
Document usage of evaluation strategies as plugins

### ISSUE THREAD

**Issue by jayu** [callstack/linaria#566]
## Describe the feature

- [x] Document usage of evaluation strategies as plugins.
- [x] Set `shaker` as a default strategy in `2.0.0`
- [x] Add note about evaluator breaking change with link to configuration docs into `docs/2.0_MIGRATION_GUIDE.md`

Also, I would suggest exporting evaluation strategies from root file, like we do with `linaria/babel`, `linaria/styled` and others

It could be 
```
const Evaluators = require('linaria/evaluators')
// ...
Evaluators.shaker, Evaluators.extractor
```
It will be more clear than importing them from `linaria/dist/...`

## Motivation

Get ready to 2.0 release :D

**Comment by Anber** [comment]
PR #608
