### ISSUE TITLE
Add a third argument to the preprocessor option that gives us the file name

### ISSUE THREAD

**Issue by soluml** [callstack/linaria#571]
## Describe the enhancement
In the webpack linaria/loader, we have a [preprocessor option](https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#options) which gives us the ability to further augment the text before passing it down the line. It would be very helpful to have a 3rd argument which features the output file name for this file.

## Motivation

This would allow us to conditionally make changes, like, adding a Sass `@use` at the top of the file to include mixins and or variables.

Currently, we have to work around it doing something like so:

```
{
  loader: 'linaria/loader',
  options: {
    extension: '.linaria.scss',
    preprocessor: (selector, cssText) => `
      @import 'Styles/helpers';
      ${selector} { ${cssText} }
    `,
    sourceMap: stage.startsWith('develop'),
  },
}
```

This works, but results in importing the file over and over again a lot. With a third argument, we could determine which file we're in and conditionally add `@use`/`@import`'s as needed.

**Comment by jayu** [comment]
@soluml As I understand, Inside preprocessor callback you want to access the filename from where styles were extracted? Or rather the path. So the use case might look like
```
 preprocessor: (selector, cssText, filePath) => filePath === 'foo' ? `
      @import 'Styles/helpers';
      ${selector} { ${cssText} }
    ` : 'sorry, co css',
```

**Comment by soluml** [comment]
Yea, exactly. Sorry I wasn't clear. Below is something I'd do if this was implemented:

```
// Somewhere in the file
const filePathMap = new Map();

// Loader Options
preprocessor: (selector, cssText, filePath) => {
  const imports = filePathMap.get(filePath) ? "" : "@use 'Styles/helpers';";  
  filePathMap.set(filePath, true);
  return `${imports} ${selector} { ${cssText} }`;
}
```
Basically, if this file has been written to already, don't add [Sass's @use](https://sass-lang.com/documentation/at-rules/use) as it must be at the top of each file.

**Comment by soluml** [comment]
I opened up a PR for this issue: #572

**Comment by satya164** [comment]
@soluml not sure if keeping external map is something you should do. files can be rebuilt at a future point. your external cache won't be consistent with the actual output.

**Comment by soluml** [comment]
My thought was to add the filePathMap at the top of my `webpack.config.js` file. The theory being that it would re-initialize anytime the build runs or re-runs so I could re-apply the "banner" text to every file. Though, in a **watch** situation, I'm not entirely sure if it'd be re-initialized or not... might depend on the bundler setup.

**Comment by soluml** [comment]
In my specific testing instance, I'm using Gatsby which[ leverages Webpack Dev Server](https://www.gatsbyjs.org/docs/node-apis/#onCreateDevServer). It provides hooks where I could reset the Map as needed to ensure I was setting the @use directive appropriately for each file, only once.

Not sure if that will help anyone googling for an answer to something like this, but there ya go.

**Comment by satya164** [comment]
I think the easiest way would be to write a simple webpack loader which runs for CSS files, then inserts what you need into those files. With a loader, you can make sure that it runs for each file and not each rule.
