### ISSUE TITLE
📢 Status of Linaria and road to 2.0

### ISSUE THREAD

**Issue by jayu** [callstack/linaria#582]
## Status Note

Recently @Anber was working on a new evaluation strategy called _shaker_. The goal was to make Linaria more flexible and reliable.

All work regarding shaker had been releasing with `1.4.0` tag, currently in `beta` stage.

Meanwhile, we wanted to introduce some breaking changes, so we decided to release `2.0.0` in `alpha` stage.

All `1.4.x` work can be found on [`1.4.x` branch](https://github.com/callstack/linaria/tree/1.4.x)

Current `master` branch contains work that is planned to be released as `2.0.0`. It is a continuation of `1.4.x` but with some breaking changes. You can track progress on new major version in [`2.0.0` milestone](https://github.com/callstack/linaria/milestone/7). 

We will release stable `1.4.0` once we finnish _shaker_ effort. **Documentation** for `1.4.x` can be found on [`1.4.x` branch](https://github.com/callstack/linaria/tree/1.4.x)

We will release stable `2.0.0` just after stable `1.4.0` but with breaking changes documented in [`2.0.0` migration guide](https://github.com/callstack/linaria/blob/master/docs/2.0_MIGRATION_GUIDE.md)

**Comment by Jayphen** [comment]
Is the new evaluation strategy already used in the 2.0 alpha? Or is it necessary to opt-in to it?

**Comment by jayu** [comment]
@Jayphen not yet, you can configure it as it is said https://github.com/callstack/linaria/issues/447#issuecomment-620656902
It will be set as default in a few days I believe. Would be awesome if you could test it and let us know if this not break anything :D

**Comment by Jayphen** [comment]
@jayu I've just tried that with the alpha and it did not break anything. I am not sure how to even know if it is using the new strategy or not.

**Comment by blasterpistol** [comment]
What about a build time penalty? Linaria 1.3.x adds 7-8 minutes to a build process and 30-40 seconds to a rebuild on a middle size project, it's why we moved to Emotion.

**Comment by chyzwar** [comment]
There is chance to list work that need to be completed for v2 ? Community could help to implement some changes these are well defined.

Maybe you consider adding Github Funding for a project ?

**Comment by jayu** [comment]
@blasterpistol we added a couple of optimizations so it should be faster now. You have to check it on your project :D

@chyzwar Here is a milestone that contains issues that should be resolved https://github.com/callstack/linaria/milestone/7 before the stable release. 
As for Github Funding, we didn't consider it yet, interesting idea!

**Comment by sewinter** [comment]
> ## Status Note
> Recently @Anber was working on a new evaluation strategy called _shaker_. The goal was to make Linaria more flexible and reliable.
> 
> All work regarding shaker had been releasing with `1.4.0` tag, currently in `beta` stage.
> 
> Meanwhile, we wanted to introduce some breaking changes, so we decided to release `2.0.0` in `alpha` stage.
> 
> All `1.4.x` work can be found on [`1.4.x` branch](https://github.com/callstack/linaria/tree/1.4.x)
> 
> Current `master` branch contains work that is planned to be released as `2.0.0`. It is a continuation of `1.4.x` but with some breaking changes. You can track progress on new major version in [`2.0.0` milestone](https://github.com/callstack/linaria/milestone/7).
> 
> We will release stable `1.4.0` once we finnish _shaker_ effort. **Documentation** for `1.4.x` can be found on [`1.4.x` branch](https://github.com/callstack/linaria/tree/1.4.x)
> 
> We will release stable `2.0.0` just after stable `1.4.0` but with breaking changes documented in [`2.0.0` migration guide](docs/2.0_MIGRATION_GUIDE.md)

The migration guide 404s.

**Comment by arendjr** [comment]
I just filed #681, which I think might be relevant to include in your 2.0 roadmap. Given the nature of `enhanced-resolve`, I doubt it will be feasible to be compatible with Webpack 4 and 5 at the same time, so then it'd make sense to keep `1.x` on Webpack 4 and support Webpack 5 with in `2.0`.

**Comment by Anber** [comment]
`1.4` and `2.0` have been released
