### ISSUE TITLE
Blank page is shown on first run when using CRA

### ISSUE THREAD

**Issue by jayu** [callstack/linaria#584]
## Environment

MacOS Catalina;
Create React App;
TypeScript.

## Description

> Error initially reported as a part of #537.

Once project bootstrapped with Linaria and Create React App is built for the first time, a blank page appears. It works well without Linaria. 

## Reproducible Demo

use `rm -rf src/.linaria-cache && yarn start` to reproduce the issue in linked repo

https://github.com/zaguiini/linaria-sandbox

**Comment by Anber** [comment]
Finally fixed in 2.2.0 and 3.0.0-beta.16!
