### ISSUE TITLE
Support for css within styled

### ISSUE THREAD

**Issue by marchaos** [callstack/linaria#603]
## Describe the enhancement

In styled-components I can do something like:

```js
const StyledInput = styled.input`
   ${props =>
    props.hasError &&
    css`
        background: red;
        color: white;
      `
}
`
```

When I attempt to do this in linaria, I get an error "Unknown word". Is this something that could be supported in the future?

## Possible implementations

See example right on their homepage - https://styled-components.com/

## Related Issues

https://github.com/callstack/linaria/issues/409

Let me know if this is a duplicate of above

**Comment by jayu** [comment]
Yep it is kind of duplicate and it will be hard to support this syntax in linaria with reasonable static extraction of the values. You can leave comment in #409  with the syntax you would like to use.
Also We currently do not support the interpolations of `css`
