### ISSUE TITLE
Using the "css" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly.

### ISSUE THREAD

**Issue by tanphamhaiduong** [callstack/linaria#617]
## Environment

Development

- Linaria version: ^1.3.3
- Bundler (+ version): ^1.3.3
- Node.js version: v10.20.1
- OS: MacOS

## Description

-It run correct for webpack but cannot run in jest test snapshot
![image](https://user-images.githubusercontent.com/22660833/82524601-960c3b00-9b59-11ea-99c7-f7a1a8f260a8.png)

My webpack config
```
...
{
      test: /\.(ts|tsx)$/,
      use: [
        {
          loader: 'babel-loader',
          options: {
            presets: [
              [
                '@babel/preset-env',
                {
                  useBuiltIns: 'entry',
                  corejs: '3',
                  targets: {
                    esmodules: true,
                    chrome: '58',
                    ie: '11',
                  },
                },
              ],
              'linaria/babel',
            ],
          },
        },
        {
          loader: 'linaria/loader',
          options: {
            sourceMap: process.env.NODE_ENV !== 'production',
          },
        },
        { loader: 'ts-loader', options: { happyPackMode: true, transpileOnly: true } },
        require.resolve('react-docgen-typescript-loader'),
      ],
    },
    {
      test: /\.stories\.tsx?$/,
      loaders: [
        {
          loader: require.resolve('@storybook/addon-storysource/loader'),
          options: { parser: 'typescript' }
        }
      ],
      enforce: 'pre'
    },
    {
      test: /\.scss$/,
      use: [
        {
          loader: MiniCssExtractPlugin.loader,
          options: {
            hmr: process.env.NODE_ENV !== 'production',
          },
        },
        {
          loader: 'css-loader',
          options: {
            sourceMap: process.env.NODE_ENV !== 'production',
          },
        },
        'sass-loader'
      ],
      include: path.resolve(__dirname, '../')
    },
...
```

## Reproducible Demo

http://g.recordit.co/f53GQ6OPWt.gif

**Comment by TMaszko** [comment]
Hi, Could you provide repository where we can reproduce this bug? We are not able to reproduce all bugs by ourselves. Thanks :)

**Comment by tanphamhaiduong** [comment]
@TMaszko My PR here https://github.com/reapit/foundations/pull/1303/files. This is public repo. So for the work around way is add `jest.mock('linaria')` to the test

**Comment by satya164** [comment]
Setup the Babel plugin like the error says https://github.com/callstack/linaria#setup

Add the Linaria preset to your `babel.config.js`

**Comment by tanphamhaiduong** [comment]
@satya164  I tried to set up babel.config.js and the error still appear. So that is the reason why I raise bug issue

**Comment by tanphamhaiduong** [comment]
@satya164 pls see in https://github.com/reapit/foundations/pull/1303/files#2

**Comment by satya164** [comment]
Make sure Jest is actually using your babel config. You have babel config at the root, but it's a monorepo, and jest probably doesn't read that babel config.

**Comment by tanphamhaiduong** [comment]
@satya164 I also have config for the repo which I use linaria by extends from root config
![image](https://user-images.githubusercontent.com/22660833/82552026-8d345d00-9b8b-11ea-92ad-8a8d904d57b1.png)

**Comment by TMaszko** [comment]
@tanphamhaiduong Make sure that `jest` is using babel. You have to either register manually your babel config or add env `test` https://babeljs.io/docs/en/options#env.

**Comment by TMaszko** [comment]
This could help https://jestjs.io/docs/en/configuration#transform-objectstring-pathtotransformer--pathtotransformer-object

**Comment by tanphamhaiduong** [comment]
There is 2 ways to solve this problem
1. Use the babel-jest like the link above. So for the jest config you need to add this one
```
...
transform: {
  "^.+\\.[jt]sx?$": "babel-jest",
}
...
```
2. If you use ts-jest for jest test, you should mock linaria in setupTest.ts
```
...
jest.mock('linaria', () => {
  css: jest.fn(() => ''),
  cx: jest.fn(() => ''),
})
...
```

**Comment by jakeleboeuf** [comment]
> There is 2 ways to solve this problem
> 
> 1. Use the babel-jest like the link above. So for the jest config you need to add this one
> 
> ```
> ...
> transform: {
>   "^.+\\.[jt]sx?$": "babel-jest",
> }
> ...
> ```
> 
> 1. If you use ts-jest for jest test, you should mock linaria in setupTest.ts
> 
> ```
> ...
> jest.mock('linaria', () => {
>   css: jest.fn(() => ''),
>   cx: jest.fn(() => ''),
> })
> ...
> ```

What about mocking `styled` from `lineria/react`? I have a Gatsby build and am running into the same problem as @viczhuravlev here https://github.com/callstack/linaria/issues/636#issue-650266792. Attempting to slide by with some mocks, but not sure how to handle all cases...

```js
jest.mock("linaria/react", () => ({
  styled: () => jest.fn(),
}));
```

```jsx
// WORKS
styled(Link)`
  display: none;
`;

// NOT WORKING
styled.header`
  display: none;
`;
```

**Comment by turadg** [comment]
> not sure how to handle all cases...

@jakeleboeuf this isn't a great solution but it does handle all the cases:
```
jest.mock('linaria/react', () => {
  function styled(tag) {
    return jest.fn(() => `mock-styled.${tag}`);
  }
  return {
    styled: new Proxy(styled, {
      get(o, prop) {
        return o(prop);
      },
    }),
  };
});
```

**Comment by fxOne** [comment]
With` ts-jest` you can also active the [babelConfig option](https://kulshekhar.github.io/ts-jest/user/config/babelConfig) which also solves the issue.
```js
// jest.config.js
module.exports = {
  // [...]
  globals: {
    'ts-jest': {
      babelConfig: true
    }
  }
};
```

**Comment by findawayer** [comment]
> With` ts-jest` you can also active the [babelConfig option](https://kulshekhar.github.io/ts-jest/user/config/babelConfig) which also solves the issue.
> 
> ```js
> // jest.config.js
> module.exports = {
>   // [...]
>   globals: {
>     'ts-jest': {
>       babelConfig: true
>     }
>   }
> };
> ```

I like this approach because (1) I want to use `ts-jest` (2) mocking styled elements brings me `<mock-styled.nodeName />` as result, while @fxOne's solution translates them into actual DOM elements; this makes selector methods like `getByLabelText` that `@testing-library/jest-dom` library be able to find them.

**Comment by JimmyLv** [comment]
> > not sure how to handle all cases...
> 
> @jakeleboeuf this isn't a great solution but it does handle all the cases:
> 
> ```
> jest.mock('linaria/react', () => {
>   function styled(tag) {
>     return jest.fn(() => `mock-styled.${tag}`);
>   }
>   return {
>     styled: new Proxy(styled, {
>       get(o, prop) {
>         return o(prop);
>       },
>     }),
>   };
> });
> ```

@turadg I found it does not work for wrapper `styled(Comp)`?

![01-05-WebStorm-dingtalk-okr-client – jest config js 2](https://user-images.githubusercontent.com/4997466/148158748-dc6bb28e-c499-44b1-9705-c20fbca380f6.jpg)

**Comment by glassdimlygr** [comment]
> With` ts-jest` you can also active the [babelConfig option](https://kulshekhar.github.io/ts-jest/docs/options) which also solves the issue.
> 
> ```js
> // jest.config.js
> module.exports = {
>   // [...]
>   globals: {
>     'ts-jest': {
>       babelConfig: true
>     }
>   }
> };
> ```

I did this, but this did not solve the issue for me.

**Comment by nvh95** [comment]
This works for `babel-jest`

```js
// jest.config.js
transform: {
    "^.+\\.(js|jsx|mjs|cjs|ts|tsx)$": "babel-jest",
```

Use `linaria/babel` instead of `@linaria`
```js
module.exports = {
  presets: [
    ["@babel/preset-env", { targets: { node: "current" } }],
    ["@babel/preset-react", { runtime: "automatic" }],
    "linaria/babel",
  ],
};

```
