### ISSUE TITLE
"Unexpected token ..." error

### ISSUE THREAD

**Issue by nodabladam** [callstack/linaria#618]
I occasionally see this error in my production logs:
```
Unexpected token ...
```

Sentry says it is coming from here:
```
 const { as: component = tag, class: className, ...rest } = props;
```
https://github.com/callstack/linaria/blob/eda0efaa437b267f536fa4866efd9299f9738767/src/react/styled.ts#L69

- Linaria version: 2.0.0-alpha.3
- Bundler (+ version): Next.js 9.4.0
- Node.js version: 13.11.0
- OS:  Chrome 79.0.3945 on windows 10
- User Agent:  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.136 Safari/537.36
--

## Description

I thought this was an older browser issue at first so I ignored it but it says Chrome 79 which I think should support rest spread.

![image](https://user-images.githubusercontent.com/57159187/82587661-702d6900-9b4e-11ea-8c26-76bfca5e202f.png)

## Reproducible Demo

Unfortunately I can't reproduce, I just see it in Sentry error monitoring from time to time.  Is there some rest spread babel during build not happening?  I only see a few instances so I assume it must be something edge case so feel free to close.  I see there are new versions out I will update to.  Unfortunately it happens infrequently enough it will be hard to know for a while if it is fixed.  I just wanted to call it out just incase.

**Comment by nodabladam** [comment]
I got this again after updating to '2.0.0-alpha.5'.  Does spread operator support need to be added to babel or something?
https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread

**Comment by nodabladam** [comment]
I got this error again with a slightly different message: `Expected identifier, string or number`

![image](https://user-images.githubusercontent.com/57159187/83061978-b719d380-a012-11ea-811c-5b30e1215969.png)

Shouldn't linaria be transpiling the spread `...`?

**Comment by nodabladam** [comment]
Update: I do seem to reproduce this error when visiting a site powered with linaria using `Microsoft Edge 44.18362.449.0`
![image](https://user-images.githubusercontent.com/57159187/83062544-b170bd80-a013-11ea-8542-b01acf317968.png)

**Comment by nodabladam** [comment]
I am using next.js and was able to work around the problem by transpiling linaria myself:

next.config.js
```
module.exports = phase => {
  if (phase === PHASE_DEVELOPMENT_SERVER || phase === PHASE_PRODUCTION_BUILD) {
    const withTM = require("next-transpile-modules")(["linaria"]); 
    return withTM({...nextConfig})       
  }
  return withOffline(nextConfig);
};
```
This could be a recommended solution if default pre-chromium Edge isn't supported by Linaria.  Although Linaria should be zero runtime so I am surprised I am having js issues in production.

This is how I am using it...perhaps this causes some runtime issue
```
import StyledComponent from "./mystyles.scss";

function AboutUsPage(props) {
    <StyledComponent>
       ...
    </StyledComponent>
}
```
./mystyles.scss
```
import { styled } from "linaria/react";
export default styled.div`
    .my-scss-styles {
        ....
    }
`;
```

I am also doing some custom webpack to get custom sass working
```
    config.plugins.push(
      new FilterWarningsPlugin({
        // ignore linaria css order warnings which next.js causes but don't seem to effect prod
        exclude: /Conflicting order/
      })
    );

    config.module.rules.push({
      enforce: "pre",
      test: /(\.linaria\.css|\.scss)$/,
      exclude: ["/node_modules/"],
      loader: "sass-resources-loader",
      options: {
        resources: [
          path.resolve(__dirname, "src/components/styles/variables.scss"),
          path.resolve(
            __dirname,
            "node_modules/bootstrap/scss/_functions.scss"
          ),
          path.resolve(
            __dirname,
            "node_modules/bootstrap/scss/_variables.scss"
          ),
          path.resolve(__dirname, "node_modules/bootstrap/scss/_mixins.scss"),
          path.resolve(__dirname, "node_modules/sassdash/_index.scss"),
          path.resolve(__dirname, "node_modules/sass-svg/_index.scss")
        ]
      }
    });
    config.module.rules.push({
      test: /(\.linaria\.css|\.s[ac]ss)$/i,
      exclude: ["/node_modules/"],
      use: [
        {
          loader: "sass-loader",
          options: {
            prependData:
              "$ASSET_PREFIX: '" +
              process.env.ASSET_PREFIX +
              "';" +
              "$CDN_OPTIMIZER_PREFIX: '" +
              process.env.CDN_OPTIMIZER_PREFIX +
              "';"
          }
        }
      ]
    });

    // Linaria default preprocessor is stylis.  We disable that to run through our sass stuff
    config.module.rules.push({
      test: /\.js$/,
      exclude: ["/node_modules/"],
      use: [
        {
          loader: "linaria/loader",
          options: {
            preprocessor: "none",
            sourceMap: process.env.NODE_ENV !== "production",
            classNameSlug: (hash, title) => `linaria_${hash}_${title}`
          }
        }
      ]
    });
```

**Comment by TMaszko** [comment]
@nodabladam Thanks for you effort! We are aware that this spread operator shouldn't be there. I'm going to fix it asap

**Comment by wereHamster** [comment]
What compatibility guarantees does Linaria make? Is that documented anywhere?

**Comment by jayu** [comment]
The only high-level compatibility info is that linaria will not work in Internet Explorer. This is still path to explore and have it clearly defined in our docs. I hope the linked PR will help with that

**Comment by wereHamster** [comment]
I highly recommend to officially support:

 - LTS Node (currently 10, 12, 14) in entry points consumed by node
 - Latest ES (currently ES2020) in entry points consumed by web bundlers

Especially in entry points used by bundlers, it's really up to the consumers of the library to downcompile or polyfill as necessary. Otherwise they will ship more code to browsers than strictly necessary, with no way to avoid that.
