### ISSUE TITLE
Theming example in docs not working with Shaker evaluator

### ISSUE THREAD

**Issue by Jayphen** [callstack/linaria#628]
Using the latest 2.0 alpha with the shaker evaluator, the `theming` function described [in the docs here](https://github.com/callstack/linaria/blob/master/docs/THEMING.md#class-names) no longer works.

```js
// Put your colors in an object grouped by the theme names
const colors = {
  light: {
    text: 'black',
  },
  dark: {
    text: 'white',
  },
};

// Create a small helper function to loop over the themes and create CSS rule sets
const theming = cb =>
  Object.keys(colors).reduce((acc, name) => Object.assign(acc, {
    [`.theme-${name} &`]: cb(colors[name]),
  }), {});

// Use the helper in your styles
const Header = styled.h1`
  text-transform: uppercase;

  ${theming(c => ({
    color: c.text,
  }))};
`;
```

When calling the `theming` function here it compiles to:

```
.theme-light .Comp_h1j1g21v{color:black;}
```

If I switch the evaluator back to Extractor, it correctly compiles to:

```
.theme-light .Comp_h1j1g21v{color:black;}
.theme-dark .Comp_h1j1g21v{color:white;}
```

**Comment by jayu** [comment]
It works as expected in my exemplary project. Can you provide a reproduction?

**Comment by layershifter** [comment]
This issue is old and does not have a repro case. Please try latest versions and report a new one if it still happens.
