### ISSUE TITLE
Replace calls to `cx()` with constants whenever possible

### ISSUE THREAD

**Issue by wereHamster** [callstack/linaria#634]
## Describe the enhancement

Replace calls to `cx()` with constants whenever possible.

## Motivation

Trivial, static uses of `cx()` could be detected and replaced with constants, reducing file size by removing the `cx()` function altogether from the output. 

The following code:

```
import { cx, css } from "linaria"

const noLayout = css``;
export const extendedWidth = cx(noLayout, css``); 
```

Will be compiled and bundled into this output:

```
function cx(...classNames) {
  return classNames.filter(Boolean).join(' ');
}

const noLayout = "n13r7o41";
const extendedWidth = cx(noLayout, "ev9kr8h");

export { extendedWidth }
```

Notice how the `cx()` function is included in the output, even though the whole code could be simplified to essentially this:

```
const extendedWidth = "n13r7o41 ev9kr8h";
export { extendedWidth }
```

## Possible implementations

Detect use of `cx()` which can be statically determined, and evaluate the code at build time, similar to how calls to `css()` are being treated.

**Comment by Anber** [comment]
Hi @wereHamster 
It may slightly reduce the bundle size in some cases but it increases build time and adds a lot of excess complexity. In my opinion it may have a sense if we are able to replace all `cx` calls but we are not.
