### ISSUE TITLE
linaria/stylelint-config is causing build errors

### ISSUE THREAD

**Issue by neefrehman** [callstack/linaria#635]
## Environment

- Linaria version: 1.4.0-beta.10
- Bundler (+ version): Webpack (via Gatsby 2.23.11)
- Node.js version: 12
- OS: MacOS 10.14.6

## Description

I've just tried adding stylelint to a Gatsby project using `linaria/stylelint-config` alongside [`gatsby-plugin-stylelint`](https://github.com/danbruegge/gatsby-plugin-stylelint), but when following the instructions from `LINTING.md` I'm now getting build errors like the following (without having any errors in the css).

```bash
ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

src/pages/index.js
 8:24  ✖  Unexpected token (8:24)   10 | export default       BABEL_PARSE_ERROR
          Container;   11 |
```

These errors stop appearing only once I remove `linaria/stylelint-config` from the `extends` array in my `.stylelintrc` file.

## Reproducible Demo

Here is a minimal codesandbox with the setup we're using: https://codesandbox.io/s/vibrant-fog-778mc

**Comment by amankkg** [comment]
I'm not using `gatsby-plugin-stylelint` but I faced another `BABEL_PARSE_ERROR`. Adding Babel config with `babel-preset-gatsby` and `linaria/babel` presets fixed my problem.

Hope it will help or at least narrow down the issue

**Comment by amankkg** [comment]
I got your demo working by adding explicit Babel config and `core-js` dependency (which can be skipped for `linaria@alpha`), also updated `gatsby-plugin-linaria`

https://codesandbox.io/s/eloquent-microservice-8w1xb?file=/package.json

**Comment by neefrehman** [comment]
@amankkg thank you! That solved it.
