### ISSUE TITLE
Jest tests fail: Using the "styled" tag in runtime is not supported.

### ISSUE THREAD

**Issue by viczhuravlev** [callstack/linaria#636]
## Environment

- Linaria version: 1.3.3
- Node.js version: v12.16.2
- OS: MacOS 10.15.5
- jest/babel-jest: 26.1.0
- react: 16.13.1

## Description

Hi! I want to change emotion to linaria, but I met a problem with testing.

I have a component with `styled.*`:

```
export const Clamper = styled.span<T.Clamper>`
  overflow: hidden;
   
   ....
`;
```

jest.config.js:
```
module.exports = {
  preset: 'ts-jest',
  testMatch: ['**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|tests).[tj]s?(x)'],
  // setupFilesAfterEnv: ['<rootDir>/config/jest/jest.setup.ts'],
  testPathIgnorePatterns: ['<rootDir>/node_modules/'],
  moduleNameMapper: {
    '@/(.*)$': '<rootDir>/src/$1',
    '.*\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga|pdf)$':
      '<rootDir>/config/jest/fileMock.js',
    '\\.(css)$': '<rootDir>/config/jest/styleMock.js',
  },
  globals: {
    'ts-jest': {
      babelConfig: true,
    },
  },
};
```

And when I run test, I get the problem(but with build is fine):
<img width="503" alt="Screenshot 2020-07-03 at 03 07 02" src="https://user-images.githubusercontent.com/11217819/86418877-47b29600-bcda-11ea-863d-1cbcb5258e8f.png">

Please, help me, I tried different ways already

## Reproducible Demo

Please clone and install the following git repo: [https://github.com/viczhuravlev/gramr-ui/tree/feat/changeEmotionToLinaria](https://github.com/viczhuravlev/gramr-ui/tree/feat/changeEmotionToLinaria)

**Comment by jazevedo620** [comment]
I'm also facing this error with Jest + Linaria + React + TypeScript, using `ts-jest` and using the following config:

```js
module.exports = {
  testRegex: "(/__tests__/.*|(\\.|/)(test|spec))\\.([tj]sx?)$",
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json"],
  testPathIgnorePatterns: [`node_modules`],
  testURL: `http://localhost`,
  moduleNameMapper: {
    ".+\\.(css|styl|less|sass|scss)$": `identity-obj-proxy`,
  },
  transform: {
    "^.+\\.tsx?$": `ts-jest`,
  },
  globals: {
    __PATH_PREFIX__: ``,
    "ts-jest": {
      babelConfig: {
        presets: [
          ["@babel/preset-env", { targets: { node: "current" } }],
          "@babel/preset-react",
          ["linaria/babel", { evaluate: true, displayName: true }],
        ],
      },
    },
  },
};
```

**Comment by jrjcky98** [comment]
Found the solution here: https://github.com/callstack/linaria/issues/617.
Changed from `ts-jest` to `babel-jest` and worked.

**Comment by jrjcky98** [comment]
Maybe this can help: https://github.com/callstack/linaria/issues/617
