### ISSUE TITLE
CSSProperties no longer exported

### ISSUE THREAD

**Issue by neefrehman** [callstack/linaria#641]
## Environment

- Linaria version: 1.4.0-beta
- Bundler (+ version): Webpack

## Description

The type `CSSProperties` is no longer being exported from `core` or `/react` (seemingly) as of the 1.4.0-beta. I import this in a few projects to type any `style` props that I give to components.

Is there a reason for this removal or is it accidental? Happy to open up a PR and fix if it's the latter.

**Comment by jayu** [comment]
We refactored codebase to TS starting from `1.4.0` so it might be possible regression
