### ISSUE TITLE
HMR Not reloading latest changes, but previous to latest

### ISSUE THREAD

**Issue by ehtb** [callstack/linaria#642]
## Environment

- linaria: 1.3.3
- webpack: 4.43.0
- mini-css-extract-plugin: 0.8.0

## Description

When using webpack's `mini-css-extract-plugin`'s hot reload, it takes two reloads to load the styles from the current build (basically every hot reload is delayed by one update). Checking the css file directly I see that it was updated with the lastest changes.

## Configuration

This is the mini-css-extract configuration, linaria is configured in the regular way.

```
{
  test: /\.css$/,
  use: [
    {
      loader: MiniCssExtractPlugin.loader,
      options: {
        hmr: __DEV__,
        reloadAll: true, // no effect
        esModule: true, // no effect
        ignoreOrder: true,  // no effect
      },
    },
    {
      loader: 'css-loader',
      options: {
        sourceMap: false,
      },
    },
  ],
}
```

I have only seen this problem with Linaria so far.

**Comment by Anber** [comment]
Fixed in 2.2.0 and 3.0.0-beta.16
