### ISSUE TITLE
Unable to use imported/external variables when Upgrading to 2.0.0-rc.0 from 2.0.0-alpha-3 

### ISSUE THREAD

**Issue by sambhav-gore** [callstack/linaria#646]
## Environment

- Linaria version: 2.0.0-rc.0
- Bundler (+ version):
- Node.js version: 10
- OS: Mac 

## Description

We have a setup in which variables are part of a published package (on internal registry) and we make use of the variables inside linaria css styles.

until 2.0.0-alpha.3 it used to work correctly, but after upgrading to `2.0.0-rc.0` our build fails due to errors reported by `templateProcessor`

Since it involves a bit of setup, I have made a reproducible demo at the following link. Please see more description and instructions to reproduce at the following repo:

## Reproducible Demo

https://github.com/sambhav-gore/linaria-demo

**Comment by Anber** [comment]
Hi @sambhav-gore!

Looks like it has been already fixed in `master`. I'll check it in the next rc.

**Comment by sambhav-gore** [comment]
> Hi @sambhav-gore!
> 
> Looks like it has been already fixed in `master`. I'll check it in the next rc.

@Anber Great. I can test and confirm after the next rc is out.

**Comment by sambhav-gore** [comment]
@Anber I confirm that the issue is resolved with the 2.0.0-rc.1 release. Closing this issue.
