### ISSUE TITLE
Webpack Loader Can't Resolve jsconfig.json Alias

### ISSUE THREAD

**Issue by pxwee5** [callstack/linaria#652]
Does this work with jsconfig.json ? I'm getting some issue with an alias set in `jsconfig.json`.
Probably related to https://github.com/callstack/linaria/issues/284

## File with linaria import & jsconfig alias:
```
import { css } from 'linaria';
import { colors } from '@themes/base';

css`
  :global() {
    .type-h3 {
      color: ${colors['gray-lynx']};
    }
  }
`;
```

Produces error:
```
Can't resolve '@themes/base' in ... Make sure you are not using a browser or Node specific API.

```

Using relative path like `../src/themes/base` works perfectly.

**Comment by Anber** [comment]
Hi @pxwee5 

Unfortunately, it doesn't. I can recommend you to use `babel-plugin-module-resolver` which is fully supported.
