### ISSUE TITLE
Linaria website is not available on now deployment

### ISSUE THREAD

**Issue by marvinhagemeister** [callstack/linaria#657]
I just get a blank page with this message instead of the linaria website:

![Screenshot 2020-08-15 at 10 10 51](https://user-images.githubusercontent.com/1062408/90308418-a5dcb680-dedf-11ea-86dd-55fb01cf0e3b.png)

**Comment by thymikee** [comment]
@satya164 mind having a look?

**Comment by jayu** [comment]
Since we have custom node.js server there, we have to migrate to some static solution. Next.js static generated pages could be an option for us.
