### ISSUE TITLE
Using linaria from an external library and compiling it with gatsby-plugin-compile-es6-packages fails

### ISSUE THREAD

**Issue by kuworking** [callstack/linaria#665]
I separated some of my `gatsby` methods in an external npm library, written in `ES6` and using `linaria`

Now, when using those methods, I am observing `Using the "styled" tag in runtime is not supported` errors when building the site, and they refer to static code like this

```js
import React from 'react'
import { styled } from 'linaria/react'

export const SPACE = styled.div`
  margin: 0px;
  background: linear-gradient(45deg, #d7dee199, transparent);
  height: 2px;
  max-width: 400px;
  width: 100%;
`
```

As far as I understand this should work, but it seems that the mere use of `styled` (even if it was like this)

```
export const SPACE = styled.div``
```

makes it look like if it was happening at runtime for linaria

Is it like this? Or I'm missing something, perhaps some babel configuration?

**Comment by Anber** [comment]
By default, node_modules is ignored by Linaria and all modules imported as is, so If you extract your styled components to separate package, you should configure `rules` section in a linaria config file https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md#options

If it doesn't solve your problem, feel free to reopen the issue.
