### ISSUE TITLE
Next.js + Linaria example doesn't work with 2.0.0-rc.1

### ISSUE THREAD

**Issue by opudalo** [callstack/linaria#667]
## Environment

- Linaria version: 2.0.0-rc.1

## Description

Latest version 2.0.0-rc.1 fails to work with next.js as per [with-linaria](https://github.com/vercel/next.js/tree/canary/examples/with-linaria) example. 2.0.0-rc.0 works fine.

## Reproducible Demo

1. [Download repo ](https://github.com/opudalo/linaria-bug)
2. `yarn` or `npm i`
3. `yarn dev` will fail with error.

![image](https://user-images.githubusercontent.com/775750/91566609-9bdd9d80-e94c-11ea-988f-96d83ace1c31.png)

**Comment by pavsidhu** [comment]
I managed to get this working with the config from [next-linaria](https://github.com/Mistereo/next-linaria)
