### ISSUE TITLE
linaria.now.sh is down

### ISSUE THREAD

**Issue by amankkg** [callstack/linaria#673]
## Environment

n/a

## Description

Seems like all Zeit 1.0 deployments are canceled. Weird, why would they do this...

## Reproducible Demo

https://linaria.now.sh

**Comment by cellog** [comment]
I'm confused - is this project no longer maintained? The website being down is pretty significant

**Comment by amankkg** [comment]
@cellog v2 is in progress and new RC was released recently, so I'd say no

And this issue is a chore, it just needs to update to Vercel (Zeit 2.0) I believe

The fact that they (Vercel/Zeit) decided to cancel old deployments is quite outrageous

**Comment by rsturim** [comment]
Many users get the wrong impression that the project is abandoned when they get to https://linaria.now.sh/ and find it erroring out, as was the case for the hosts on the Syntax.fm podcast (episode 284) a few days ago. This podcast has a massive following of subscribers/listeners. I fear linaria is significantly losing adoption as long as this url is failing.

**Comment by Anber** [comment]
Since there is seems to be an unresolvable problem with Zeit, we've moved to GitHub Pages. Unfortunately, it means that the current domain name is lost. The new one is https://linaria.dev/.
