### ISSUE TITLE
Custom Props Leaked To DOM Element

### ISSUE THREAD

**Issue by damonbauer** [callstack/linaria#677]
## Environment

- Linaria version: 1.3.3
- Bundler (+ version): webpack 4.22.0
- React & React DOM: 16.5.2
- Node.js version: 
- OS:

## Description

When providing a custom prop to a `styled` element, the custom prop **sometimes** leaks to the DOM.

Given this styled `h1`:

```js
const Title = styled.h1`
  font-family: sans-serif;
  font-size: 48px;
  color: ${({ primary }) => (primary ? "#BADA55" : "#C0FFEE")};
  width: ${({ span }) => (span === 12 ? "100%" : "50%")};
`;
```

The following usage results in `span="12"` to be output to the DOM:
```jsx
<Title primary span={12}>Hello world!</Title>
```

The following usages do not result in any custom prop to be output to the DOM:
```jsx
<Title primary>Hello world!</Title>
<Title>Hello world!</Title>
```

![Screen Shot 2020-09-28 at 2 34 52 PM](https://user-images.githubusercontent.com/368723/94478049-5228e280-0198-11eb-9560-336fecde755a.png)

## Reproducible Demo

https://codesandbox.io/s/linaria-custom-prop-leak-jf6iv

Related: #555

**Comment by MrFlashAccount** [comment]
Hello! 
This is because `span` is a valid html attribute, see: https://github.com/emotion-js/emotion/blob/master/packages/is-prop-valid/src/props.js#L143

If you don't want to see these attributes in the DOM, you should prefer to choose different prop name.

**Comment by damonbauer** [comment]
Whoa, I had no idea! Thanks @MrFlashAccount!

**Comment by MrFlashAccount** [comment]
You’re welcome!
