### ISSUE TITLE
Write css for the different devices in one place

### ISSUE THREAD

**Issue by knastordin** [callstack/linaria#689]
## Write css for the different devices in one place

I would like to be able write code like this:
styled.div`
  font-size: 24px;
  color: ${props => props.color};
  ....
@mobile{
  font-size: 12px;
}

@tablet{
font-size: 18px;
}
`;

## Motivation
In case not all values can be computed i would like to be able specify and set some special values for different devices in one place.

## Possible implementations
Add reusable mixins for different devices based on screen resolutions into.

**Comment by turadg** [comment]
You can do this now with [media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries). You can define whatever queries you want in some file and then use them in Linaria like so:
```js
styled.div`
  ${mobile} {
    font-size: 12px;
  }
`;
```

It helps to have a JS module that defines a set of media queries for [devices](https://css-tricks.com/snippets/css/media-queries-for-standard-devices/) you target, such as this extreme example:
```js
export const iPhoneXPortrait = `
@media only screen 
  and (min-device-width: 375px) 
  and (max-device-width: 812px) 
  and (-webkit-min-device-pixel-ratio: 3)
  and (orientation: portrait) { 
`;
```

However outside the scope of Linaria.

**Comment by knastordin** [comment]
Ok, thanks!

**Comment by devinrhode2** [comment]
I love how this seemingly fancy feature is so easily implemented in any way you like with a simple javascript variable! :100:
