### ISSUE TITLE
Const declarations are not supported in strict mode.

### ISSUE THREAD

**Issue by AntiMoron** [callstack/linaria#690]
## Environment

mobile safari 9;
"linaria": "^1.3.3"
node: v10.16.0

## webpack

part of my webpack config:

```js
  optimization: {
    moduleIds: 'named',
    chunkIds: 'named',
    splitChunks: {
      minSize: 30000,
      cacheGroups: {
        vendors: {
          test: /node_modules/,
          name: 'vendors',
          minSize: 30000,
          minChunks: 2,
          priority: 1, 
        },
```

Found js error in production which caused blank page: 

```
Const declarations are not supported in strict mode.
```

Please fix this.

![Snip20201102_6](https://user-images.githubusercontent.com/6587734/97850339-ddb10880-1d2e-11eb-910c-319d76bc6358.png)

**Comment by AntiMoron** [comment]
I've found where these `const`s located:

https://github.com/callstack/linaria/blob/80b7337578d92fa49db9ce2aba62667027cc75b2/src/react/styled.ts

**Comment by Anber** [comment]
Hi @AntiMoron 

Linaria supports only relatively modern browsers which support CSS Variables and unfortunately, Safari 9 is not one of them.

**Comment by AntiMoron** [comment]
Thanks.
