### ISSUE TITLE
Missing `linaria/server` TS types

### ISSUE THREAD

**Issue by oreqizer** [callstack/linaria#691]
TypeScript types for `linaria/lib/server` are not present. Don't know what more needs to be included here.

This is the error I am getting:

```
node_modules/linaria/server.d.ts:1:25 - error TS7016: Could not find a declaration file for module './lib/server'. '/.../node_modules/linaria/lib/server/index.js' implicitly has an 'any' type.

1 export { collect } from './lib/server';
```

**Comment by Anber** [comment]
Hi @oreqizer

Thank you for your report! The problem was fixed in `2.0.1`
