### ISSUE TITLE
Issue with reporting and detection of violations of the `indentation`, `max-empty-lines` and `no-empty-first-line` rules when extending `linaria/stylelint-config`

### ISSUE THREAD

**Issue by jpnelson** [callstack/linaria#693]
## Environment
- Linaria version: 1.3.3
- Node version: 12
- OS: Mac

## Description

When extending `linaria/stylelint-config` and using these rules:

* indentation
* max-empty-lines
* no-empty-first-line

Error reporting happens for code outside of `css` template literals, and errors are reported incorrectly.

![image](https://user-images.githubusercontent.com/1518604/98161492-ac524d00-1e94-11eb-88cd-6db216194122.png)

## Reproducible Demo

https://codesandbox.io/s/linaria-demo-forked-bxdvh?file=/src/App.js

**Comment by Anber** [comment]
Unfortunately, we can't use a source map here because SourceMapConsumer is async whereas custom stylelint processor must be sync. However, I've tried to adjust warnings positions with a naive implementation of source-map, but I'm not sure if this will always work.

**Comment by Anber** [comment]
@jpnelson btw, have you tried `@stylelint/postcss-css-in-js`?
