### ISSUE TITLE
Cannot install @linaria/webpack-loader -> Not found

### ISSUE THREAD

**Issue by kuworking** [callstack/linaria#699]
Following the docs about webpack configuration, @linaria/webpack-loader is needed but the package is not found (at least in my hands)

(*) https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#webpack

```
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@linaria%2fwebpack-loader: Not found".
info If you think this is a bug, please open a bug report with the information provided in "...\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by Anber** [comment]
Webpack loader was published as `@linaria/webpack4-loader`. `@linaria/webpack-loader` is currently reserved for universal webpack 4/5 loader and will be published with the next beta.

https://github.com/callstack/linaria/issues/681
