### ISSUE TITLE
Linaria errors when using Svelte props

### ISSUE THREAD

**Issue by madeleineostoja** [callstack/linaria#702]
## Environment

- Svelte 3+
- Linaria version: ^1.3.3
- Bundler (+ version): Webpack 5
- Node.js version: 12.6.0
- OS: MacOS Big Sur

## Description

I'm using Linaria in [Svelte](https://svelte.dev/) components. Using plain CSS and plain JS constants works, but whenever I try using a dynamic svelte prop in a Linaria declaration I get the following error:

(simplified example)

```sh
Module build failed (from /[...]/node_modules/linaria/loader.js):
An error occurred when evaluating the expression: ctx is not defined. Make sure you are not using a browser or Node specific API.
  
  52 | attr_dev(div0, "class", div0_class_value = css`
  53 | color: ${/*color*/ ctx[0]}%;`);
```

Original code is something like

```svelte
<script>
	export let color;
</script>

<div class={css`color: ${color};` />
```

Looks like Linaria is erroring at missing a clientside/internal Svelte dep in its compiled component?

**Comment by seaneking** [comment]
Anything I can help to move this along or further debug? It's currently a breaking issue for us and forcing us to use Emotion, which doesn't play nice with Svelte's SSR.

**Comment by Anber** [comment]
Hi @seaneking 

Have you tried Linaria 2.0?

**Comment by seaneking** [comment]
@Anber yep unfortunately still get the same issue with Linaria 2.0, just a slightly more detailed error message:

```sh
> ctx is not defined. 

  Make sure you are not using a browser or Node specific API and all the variables are available in static context.
  Linaria have to extract pieces of your code to resolve the interpolated values.
  Defining styled component or class will not work inside:
    - function,
    - class,
    - method,
    - loop,
  because it cannot be statically determined in which context you use them.
  That's why some variables may be not defined during evaluation.
```

**Comment by Anber** [comment]
@seaneking could you please provide a repo?

**Comment by seaneking** [comment]
Nothing I'm working on at the moment is public, but I'll spin up a quick example with the svelte starter when I get a mo 👍

**Comment by kjj6198** [comment]
IMO, I think currently linaria with svelte can only be used when it's fully static.
In svelte, `export let color` means prop, so it has to be evaluated at runtime. For my understanding linaria API `css` can not do that.

Furthermore, Svelte is a compiler, so it will compile your code and then pass to linaria.
For example your code will be compiled into something like this:

```jsx
function create_fragment(ctx) {
	let div;
	let div_class_value;

	return {
		c() {
			div = element("div");
			// notice here.	
			attr(div, "class", div_class_value = css`color: ${/*color*/ ctx[0]};`);
		},
		m(target, anchor) {
			insert(target, div, anchor);
		},
		p(ctx, [dirty]) {
			if (dirty & /*color*/ 1 && div_class_value !== (div_class_value = css`color: ${/*color*/ ctx[0]};`)) {
				attr(div, "class", div_class_value);
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div);
		}
	};
}
```
You can refer to [REPL](https://svelte.dev/repl/faf4258b17c649d1b533371d0a30d240?version=3.31.0) for more detail. Since `ctx[0]` is not defined at build time, linaria throws error.

I guess if we want to support it, we have to write a stand-alone babel plugin just like `@linaria/react` does. svelte currently doesn't have API to create element at runtime like `React.createElement`, I think it will be harder if we want to integrate svelte with `linaria`?

**Comment by madeleineostoja** [comment]
yep that's a good analysis, and makes sense. We would definitely need a Babel plugin to handle dynamic props by the look of it, to deal with the Svelte runtime in an SSR scenario. That's way beyond my head, maybe we need someone from the Svelte team to chime in.

Conditionals are easy enough to hack around, it's using the values from props that aren't possible.

**Comment by madeleineostoja** [comment]
Actually after some more thinking there are decent workaround for all of Linaria's issues with dynamic svelte props. For anyone else coming to this issue:


### Conditionals

```
class="css`${condition ? styles : otherStyles}`"
```

Becomes
```
class="{condition ? css`${styles}` : css`${otherStyles}`}
```

### Prop Values

Just use CSS custom props directly

```svelte
<script>
  export let color;
</script>

<style>
  h1 {
    color: var(--color)
  }
</style>

<h1 style="--color: {color}" />
```


And there's an RFC open with an active PR for Svelte for a shorthand to set the variable like this too

```svelte
<h1 --color={color} />
```

**Comment by madeleineostoja** [comment]
Might be worth documenting this in the Svelte integration guide, since it is a big gotcha that will catch people out using Linaria with Svelte

**Comment by madeleineostoja** [comment]
Coming back to Linaria after a long break and I think this can be closed now that [Dynamic Styles with `css`](https://github.com/callstack/linaria/blob/master/docs/DYNAMIC_STYLES.md) is well documented
