### ISSUE TITLE
@linaria/babel doesn't work

### ISSUE THREAD

**Issue by ym-project** [callstack/linaria#704]
## Environment

**packages**
* "@babel/cli": "^7.12.7"
* "@babel/core": "^7.12.7"
* "@linaria/babel": "^3.0.0-beta.0"
* "@linaria/webpack4-loader": "^3.0.0-beta.0"
* "babel-loader": "^8.2.1"
* "webpack": "^4.44.2"
* "webpack-cli": "^4.2.0"

**software**
* nodejs: v15.2.1
* os: ArchLinux 5.5.13-arch2-1

## Description

When I try to bundle the project I get an error:
```sh
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@linaria/babel-preset-babel' from '.../linaria-test'
- If you want to resolve "@linaria/babel", use "module:@linaria/babel"
    at Function.resolveSync [as sync] (.../linaria-test/node_modules/resolve/lib/sync.js:90:15)
    at resolveStandardizedName (.../linaria-test/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePreset (.../linaria-test/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
    at loadPreset (.../linaria-test/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
    at createDescriptor (.../linaria-test/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at .../linaria-test/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (.../linaria-test/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (.../linaria-test/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (.../linaria-test/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
```
As I understand babel can not to find `@linaria/babel`. Instead of necessary package babel try to find  `@linaria/babel-preset-babel`. Previous version (2.0) has `linaria/babel` package and it works great.

## Reproducible Demo
https://github.com/ym-project/linaria-babel-bug

**Comment by Anber** [comment]
Hi @ym-project 

I've also faced that problem. As a workaround, you can replace `@linaria/babel` in a config with `module:@linaria/babel`.

**Comment by ym-project** [comment]
> Hi @ym-project
> 
> I've also faced that problem. As a workaround, you can replace `@linaria/babel` in a config with `module:@linaria/babel`.

Your solution requires an additional dependency
```sh
Error: [BABEL] .../linaria-test/src/index.js: Cannot find module '@linaria/shaker'
```
But after installing it's ok.

**Comment by Anber** [comment]
Yep, it's correct dependency. Just forgot to add it to the documentation.

**Comment by shaodahong** [comment]
I use `require.resolve(@linaria/babel)` to resolved.

**Comment by ym-project** [comment]
> I use `require.resolve(@linaria/babel)` to resolved.

It's a [kludge](https://en.wikipedia.org/wiki/Kludge) too. Also if your config file is `*.json`, `.babelrc`, ..., you can't do it.

I never write babel plugin and never work with monorepo. What's really wrong with this plugin?

**Comment by Anber** [comment]
According to https://github.com/babel/babel/blob/208acb1d6c216b265fd49b9d393237a45725ff6a/packages/babel-core/src/config/files/plugins.js#L79, Babel tries to standardize all names of plugins and presets. If we rename `@linaria/babel` to `@linaria/babel-preset` it will be possible to use short `@linaria` as a preset name.
@satya164 @thymikee what do you think?

**Comment by satya164** [comment]
> According to https://github.com/babel/babel/blob/208acb1d6c216b265fd49b9d393237a45725ff6a/packages/babel-core/src/config/files/plugins.js#L79, Babel tries to standardize all names of plugins and presets. If we rename `@linaria/babel` to `@linaria/babel-preset` it will be possible to use short `@linaria` as a preset name.
> @satya164 @thymikee what do you think?

Sounds good to me

**Comment by Anber** [comment]
`@linaria/babel` was renamed to `@linaria/babel-preset` in `3.0.0-beta.1`. It should fix the issue.
