### ISSUE TITLE
Use in typescript will report type error.

### ISSUE THREAD

**Issue by xpol** [callstack/linaria#730]
## Environment

- Linaria version: 2.0.2
- Bundler (+ version): ?
- Node.js version: v14.15.4
- OS: Mac 11.1 (20C69)
- Typescript: 3.7.0

## Description

TS2345: Argument of type '(props: any) => any' is not assignable to parameter of type 'StaticPlaceholder'.   Property '__linaria' is missing in type '(props: any) => any' but required in type 'StyledMeta'.

## Reproducible Demo

index.tsx:

```typescript
import React from 'react'
import {View} from '@tarojs/components'
import {styled} from 'linaria/react'

type Props = {
  color: string
};

const Title = styled(View)<Props>`
  color: ${ ( props ) => props.color }
`;

const Index: React.FC = (): JSX.Element => {
  return <Title color='red'>
    Hello World!
  </Title>
}

export default Index
```

**Comment by xpol** [comment]
I have to use `@ts-ignore`.

```typescript
const Title = styled(View)<Props>`
  color: ${
    // @ts-ignore
    ({ color }) => color
  }
`;
```

**Comment by Adherentman** [comment]
same error

**Comment by Anber** [comment]
It's not an issue, it's a legitimate type check error: if you use props-based values, Linaria converts them to css-variables and adds those variables to the `style` attribute, so this error means that your `View` component doesn't have `style` prop and prop-based values can be missed. A bit unclear, but it's the best what TS can offer right now.

**Comment by gthrm** [comment]
Today I got the same error and see that it's closed without some solution. What should I do? ☹️

**Comment by wcldyx** [comment]
Brothers, I also encountered this problem, how to solve

**Comment by Anber** [comment]
Guys, I'm so sorry. There was an error that makes impossible to wrap a class component.

**Comment by rquanx** [comment]
get type error after update new version

**Comment by Anber** [comment]
Hi @rquanx 

Looks like #887 is going to fix that issue
![Screenshot 2021-12-16 12 43 20](https://user-images.githubusercontent.com/148258/146356966-1fe2e3e3-9dc8-4456-8c92-6286c9776d45.png)

**Comment by rquanx** [comment]
will， Can tell me when it will be released

**Comment by codingbycat** [comment]
I want to know how to resolve it right now.
