### ISSUE TITLE
Import custom identifier called css with error "Cannot find module 'linaria'"

### ISSUE THREAD

**Issue by GitaiQAQ** [callstack/linaria#739]
## Environment

- Linaria version: After split one `linaria` package into multiple `@linaria/*` 

## Description

When import `css` from some module like './utils',  webpack will throw an error "Cannot find module 'linaria'"

```js
import { css } from './utils';

...

```

Because the package 'linaria' is deprecated, At [here](https://github.com/callstack/linaria/blob/master/packages/babel/src/utils/hasImport.ts#L47) try the resolve this. And then require.resolve will throw an exception.

## Example

https://codesandbox.io/s/linaria-demo-forked-rbivr?file=/src/index.js

**Comment by chrisabrams** [comment]
I get the same error when using `import { css } from '@linaria/react'`.

**Comment by Anber** [comment]
Hi @chrisabrams 

> I get the same error when using import { css } from '@linaria/react'.

`css` is located in `@linaria/core` because `core` is a zero-runtime package, whereas `@linaria/react` imports a small amount of code for supporting props.

**Comment by chrisabrams** [comment]
> Hi @chrisabrams
> 
> > I get the same error when using import { css } from '@linaria/react'.
> 
> `css` is located in `@linaria/core` because `core` is a zero-runtime package, whereas `@linaria/react` imports a small amount of code for supporting props.

I blame lack of sleep. Thanks.

**Comment by Mavrin** [comment]
Could you please publish new package version with fix.
