### ISSUE TITLE
Cannot use Linaria with SSR

### ISSUE THREAD

**Issue by chrisabrams** [callstack/linaria#741]
## Environment

- Linaria version: 3.0.0-beta.1
- Bundler (+ version): Webpack 5.26.0
- Node.js version: 14.9
- OS: OS X Catalina

## Description

I try to use the [critical CSS example](https://github.com/callstack/linaria/blob/master/docs/CRITICAL_CSS.md), but I get the following error:

`Error: Using the "styled" tag in runtime is not supported.`

This is because I'm running `<App />` on Node.js, and it has not been Webpackified. Are we supposed to Webpackify our App before using it on Node.js? If so, how do you import a module on Node.js that has already been Webpackified?

Essentially, what is a safe way to say `import App from './App'` so that Linaria runs on Express/Node?

## Reproducible Demo

app.js

```js
import React from 'react'
import { styled } from '@linaria/react'

const StyledApp = styled.div``

function App() {
  <StyledApp>foo</StyledApp>
}
```

server.js

```js
import App from './App'
import express from 'express'
import React from 'react'

app.get('/', (req, res) => {
  const html = ReactDOMServer.renderToString(<App />)
})

app.listen(3333)
```

**Comment by Anber** [comment]
Hi @chrisabrams 

You don't need to webpackified, but you need `@linaria` in the list of babel presets.
