### ISSUE TITLE
React 17 not in peerDeps (breaks npm v7)

### ISSUE THREAD

**Issue by ntucker** [callstack/linaria#743]
## Environment
react>=17

- Linaria version: @linaria/react@3.0.0-beta.1
- Bundler (+ version): webpack 5
- Node.js version: v14.13.1
- OS: Ubuntu
- npm: 7.7.5

## Description

Warnings in most package installers, npm 7 will outright fail due to this problem. Cannot use with React 17.

```bash
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   dev react@"latest" from the root project
npm ERR!   peer react@">=16" from @linaria/react@3.0.0-beta.1
npm ERR!   node_modules/@linaria/react
npm ERR!     dev @linaria/react@"^3.0.0-beta.1" from the root project
npm ERR!   22 more (@rest-hooks/test, @rest-hooks/core, rest-hooks, ...)
```

**Comment by avindra** [comment]
`linaria` specifies  `react >=16`:

https://github.com/callstack/linaria/blob/4ee73ae362ca775999bf71c93279db5268108d13/packages/react/package.json#L51

Maybe it's coming from another dependency ?

Specific to `npm`, you may be able to bypass the problem with `--legacy-peer-deps`, which I've had to use on multiple occasions in the past year or so.

**Comment by ntucker** [comment]
This isn't blocking me from installing (I used the `--legacy-peer-deps` as suggested) but I'm worried about others and the friction it creates.

**Comment by ntucker** [comment]
Trying package.json entry from latest to actual version and get same thing:

```bash
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   dev react@"^17.0.2" from the root project
npm ERR!   peer react@">=16" from @linaria/react@3.0.0-beta.1
npm ERR!   node_modules/@linaria/react
npm ERR!     dev @linaria/react@"^3.0.0-beta.1" from the root project
npm ERR!   22 more (@rest-hooks/test, @rest-hooks/core, rest-hooks, ...)
```

**Comment by ntucker** [comment]
I believe they expect explicit versions listed with || now. "NPM modules must name specific versions of their peerDependencies"


More here: https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major

**Comment by Anber** [comment]
Hi @ntucker!

Could you please provide a repo? I've tried to reproduce the error but everything seems ok:
```
➜  linaria-743 cat package.json | grep "react"
    "@linaria/react": "^3.0.0-beta.1",
    "react": "latest"
➜  linaria-743 npm install

added 8 packages, and audited 9 packages in 2s

found 0 vulnerabilities
```

https://semver.npmjs.com says that there is no difference between `>=16` and `>=16 || >=17`.

**Comment by dmitryshelomanov** [comment]
not working with new jsx

**Comment by onygami** [comment]
Similar issue, I can't install when `preact` is present in the project `npm:@preact/compat`, had to use `--legacy-peer-deps`. Using npm v7.

```
npm ERR! While resolving: next-js-template@0.0.1
npm ERR! Found: react@0.0.4
npm ERR! node_modules/react
npm ERR!   react@"npm:@preact/compat@0.0.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=16" from @linaria/react@3.0.0-beta.4
npm ERR! node_modules/@linaria/react
npm ERR!   @linaria/react@"^3.0.0-beta.4" from the root project
```

**Comment by ntucker** [comment]
> 
> 
> Hi @ntucker!
> 
> Could you please provide a repo? I've tried to reproduce the error but everything seems ok:
> 
> ```
> ➜  linaria-743 cat package.json | grep "react"
>     "@linaria/react": "^3.0.0-beta.1",
>     "react": "latest"
> ➜  linaria-743 npm install
> 
> added 8 packages, and audited 9 packages in 2s
> 
> found 0 vulnerabilities
> ```
> 
> https://semver.npmjs.com says that there is no difference between `>=16` and `>=16 || >=17`.

The key is using npm 7 - not something normally enforceable in a repo.

**Comment by Anber** [comment]
> The key is using npm 7 - not something normally enforceable in a repo.

```
➜  npm --version
7.7.5
```

¯\\\_(ツ)\_/¯ 

Probably, there is another factor. That's why I asked for a repo.

**Comment by layershifter** [comment]
```
> npm -v
8.19.4
> npm install react@17
added 4 packages, and audited 5 packages in 858m
> npm install @linaria/react
added 80 packages, and audited 85 packages in 14s
```

No errors or warnings related to `peerDependencies`.
