### ISSUE TITLE
Published node module not ES5

### ISSUE THREAD

**Issue by jasperkuperus** [callstack/linaria#746]
## Environment

- Linaria version: 3.0.0-beta.1
- Bundler (+ version): Webpack 5.26.0
- Node.js version: 12.16.2
- OS: macOS

## Description

First off, I really like this lib. Keep up the good work.

The version of linaria that's published to npm isn't transpiled down to ES5 properly. I noticed due to spread operators, originating from `@linaria/core`, landing in my `bundle.js` that made older browsers crash. I guess the module should be properly transpiled to ES5 before publishing it to npm.

~While investigating, I noticed that I was on this `3.0.0` beta. So I figured to downgrade to `2.1.0`, which I saw in the releases. But it didn't allow me... Must be some renamed packages? Couldn't find any instructions on this.~ -> I managed to get `2.1.0` installed, but same issue there with spread operators in published package.

## Reproducible Demo

n/a

**Comment by Anber** [comment]
Hi @jasperkuperus!

Fixed and will be released in `3.0.0-beta.2`

**Comment by jasperkuperus** [comment]
Hi @Anber . Thanks for the quick reply! It looks like the spread operators are gone indeed. But now I'm running into the same issue with arrow functions:

<img width="849" alt="Screenshot 2021-04-13 at 10 01 13" src="https://user-images.githubusercontent.com/1655683/114518255-73868300-9c3f-11eb-8a58-dd237f43639d.png">

This unfortunately also lets my older browsers crash :( Can we reopen this?

**Comment by Anber** [comment]
Ouch!
I completely forgot that there are browsers without the support of arrow functions :)

**Comment by Anber** [comment]
btw, do you know that property-based interpolation for `styled` is not working in such old browsers? You still can use `css` and `styled`, but property-based interpolation requires css variables.

**Comment by jasperkuperus** [comment]
Yes, I'm well aware. I think I can get away with that and for these browsers I aim for graceful degradation. Some styling that didn't get picked up by the browser is OK, but the app crashing is not 😊

**Comment by Anber** [comment]
Ok! I'll release a fix in a couple of days.

**Comment by jasperkuperus** [comment]
Perfect, again thanks for the fast/adequate response!

**Comment by Anber** [comment]
In order to avoid future reopenings, could you please replace these files in your local node_modules and confirm, that everything is ok? :)

- https://gist.github.com/Anber/77ecc5ff3c49032000eed8264516f244
- https://gist.github.com/Anber/540ac5a326fb900f1dd75089f2339a90
- https://gist.github.com/Anber/492f23973bc65c8214cc4466a044a084

**Comment by jasperkuperus** [comment]
Still has the same issue. So, as I've set `webpack` to `target: es5`, it apparently picks up the source code from `core/esm`, which still has arrow functions.

Quick and maybe silly question. Why not add a transpiler like Babel and make sure it transpiles the code before publishing it? That way **you** can keep using your favourite language constructs and users of the library are free to use it in any environment.

**Comment by Anber** [comment]
It's transpilled: to es3 in `lib` and to es5 in `esm`. If you set webpack target to `es5`, webpack takes es5 version of code with arrows, const and imports/exports. However, there was a problem with the compilation target in babel, which excludes ie11, and the code itself has a few functions that weren't implemented in IE11.  I hope, that https://github.com/callstack/linaria/pull/750 fixes it.

**Comment by jasperkuperus** [comment]
Ah, pardon me for thinking it's not transpiled. I'll be happy to test it when it's published!

**Comment by jasperkuperus** [comment]
@Anber When are you going to publish this to npm? I'd like to test it 😊

**Comment by Anber** [comment]
@jasperkuperus done!

**Comment by jasperkuperus** [comment]
> It's transpilled: to es3 in `lib` and to es5 in `esm`. If you set webpack target to `es5`, webpack takes es5 version of code with arrows, const and imports/exports. However, there was a problem with the compilation target in babel, which excludes ie11, and the code itself has a few functions that weren't implemented in IE11. I hope, that #750 fixes it.

Tested `3.0.0-beta.3`, it still picked up `esm/`. But considering your quote here, I forced Webpack to pick up `lib/` and that fixed all my issues. No clue if this is the proper way to force loading `lib/` in stead of `esm/`, but I ended up doing this:

```
  resolve: {
    alias: {
      '@linaria/core': path.join(__dirname, './node_modules/@linaria/core/lib'),
    },
  },
```

**Comment by Anber** [comment]
Hi @jasperkuperus!

Take a look at that config option https://webpack.js.org/configuration/resolve/#resolvemainfields
If you want to support old browsers, you probably need to specify `main` as a first option.

**Comment by jasperkuperus** [comment]
I considered, but that would make the switch on all my libraries, but at this moment only linaria was an issue for me. I might have to go down that path one day though. Thanks!
