### ISSUE TITLE
@linaria/cli - Cannot find module '../lib/cli'

### ISSUE THREAD

**Issue by kinetifex** [callstack/linaria#753]
## Environment

- Linaria version: `3.0.0-beta.2` || `3.0.0-beta.3`
- ~Bundler (+ version):~
- Node.js version: `14.15.1`
- OS: `macOS 11.2.3`

## Description

The latest cli fails to find the lib module. Likely due to the file name change in 75f5d8d4712593641d7976618e7f3bbc30e48067.

If I hack in and fix this in my node_modules, then it finds the module but I start to get `Cannot find module '@babel/core'` so there are additional issues it seems.

## Reproducible Demo

```shell
> yarn global add @linaria/cli@3.0.0-beta.2
> linaria --version

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../lib/cli'
```

**Comment by Anber** [comment]
Hi @kinetifex!

I hope, I fixed it in `beta.4`
