### ISSUE TITLE
Presumably incorrect dist-tags on npmjs.com

### ISSUE THREAD

**Issue by dkamyshov** [callstack/linaria#756]
## Describe the enhancement

Use correct dist-tags on npmjs.com.

![image](https://user-images.githubusercontent.com/26835323/116444812-ce35f680-a85d-11eb-90ca-9b3109475c9b.png)

## Motivation

Running `$ yarn upgrade-interactive --latest` suggests updating to the `beta` version. In my opinion, it is expected that the `latest` tag refers to the latest stable version. See https://docs.npmjs.com/cli/v6/commands/npm-dist-tag.

## Possible implementations

Update the dist-tags so that the `latest` tag is only used for stable versions.

## Related Issues

Didn't find any.

**Comment by Anber** [comment]
Thank you @dkamyshov!

Fixed.
