### ISSUE TITLE
Rollup bundle generates invalid linaria imports instead of css since `@linaria/rollup@3.0.0-beta.6`

### ISSUE THREAD

**Issue by nstepien** [callstack/linaria#778]
## Environment

- Linaria version: 3.0.0-beta.6
- Bundler (+ version): rollup@2.51.1
- Node.js version: v16.3.0
- OS: win10

## Description

There is a regression with `@linaria/rollup@3.0.0-beta.6`, the issue is not present with `@linaria/rollup@3.0.0-beta.5`.
The bundle does not include the css anymore, linaria imports are left as is instead.

For example, with `@linaria/rollup@3.0.0-beta.5`:
![image](https://user-images.githubusercontent.com/567105/121511754-e5314200-c9e0-11eb-9f08-22417f470d8d.png)

After upgrading to `@linaria/rollup@3.0.0-beta.6`:
![image](https://user-images.githubusercontent.com/567105/121511946-19a4fe00-c9e1-11eb-9c8f-15add26c40eb.png)

## Reproducible Demo

1. clone https://github.com/adazzle/react-data-grid
2. `npm i`
3. `npm run build`
4. inspect the resulting bundle `lib/bundle.js`

**Comment by Anber** [comment]
Hi @nstepien!

I'm not familiar with `rollup`, but something went wrong after [that PR](https://github.com/callstack/linaria/pull/763). I'll try to figure out what to do with it in the next couple of days.

Thank you!

**Comment by wmzy** [comment]
```js
 external: (id) => !id.startsWith('.') || !isAbsolute(id)
```
to
```js
external: (id) => !id.startsWith('@linaria:') || ! !id.startsWith('.') || !isAbsolute(id)
```
will work?

**Comment by nstepien** [comment]
@wmzy 
This worked
```js
external: (id) => !id.startsWith('.') && !isAbsolute(id) && !id.startsWith('@linaria:'),
```
Nice catch, thanks.
Not sure if anything should be fixed in `@linaria/rollup` then.

**Comment by wmzy** [comment]
@nstepien  I don't think this is a bug.
Other rollup plugin may also use a virtual file name.

Maybe add a file name config to make It explicit is better:
```js
plugins:[
  linaria({
     mapFilename: (id) => '@linaria:' + id
   })
]
```
