### ISSUE TITLE
Normalize documentation across different places

### ISSUE THREAD

**Issue by hyoretsu** [callstack/linaria#791]
To put it simply, I started looking into Linaria and different places say different things. [withLinaria example repo](https://github.com/vercel/next.js/blob/master/examples/with-linaria/.babelrc) uses `linaria/babel` as a preset, but the [configuration page](https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md) tells us to use `@linaria`. After looking some more I found out that there's actually both `linaria` and `@linaria/core`.
If you go to each one of them in NPM, they both have different instructions, even though they link to the same repo. In fact, @linaria's last publish was 2 months ago, while linaria was 2 days ago. @linaria's also 1% the size of linaria.

**Comment by Anber** [comment]
`@linaria/*` is the new scope for all packages which previously (before `3.0`) were installed as one package `linaria`. However, `3.0` still has `linaria` metapackage in order to keep backward compatibility.

**Comment by hyoretsu** [comment]
Yes, I eventually discovered that, but I opened this issue because your documentation is different here and there.
