### ISSUE TITLE
Change default value for `cacheDirectory`

### ISSUE THREAD

**Issue by faergeek** [callstack/linaria#798]
## Describe the enhancement

It would be nice if `@linaria/webpack-loader` would store it's cache in `node_modules/.cache` by default like babel-loader and webpack do.

## Motivation

It's nice for cache to be placed inside `node_modules`, because that way you don't have to add one more folder to `.gitignore` or any other ignore file.

`babel-loader` and `webpack` use subfolders under `node_modules/.cache` to store cache if not specified otherwise:

babel-loader: https://github.com/babel/babel-loader#options
webpack: https://webpack.js.org/configuration/cache/#cachecachedirectory

## Possible implementations

It can be implemented using [find-cache-dir](https://www.npmjs.com/package/find-cache-dir) like this:

`findCacheDir({name: 'linaria'})`

How babel-loader does it: https://github.com/babel/babel-loader/blob/7fdf6f4ca85d4f7c25ca7952b6ec51f5cb059762/src/cache.js#L163

**Comment by Anber** [comment]
`cacheDirectory` was removed in `2.2.0` and `3.0.0-beta.16`, since the cache was moved from file system to memory.
