### ISSUE TITLE
Cannot find module 'core-js/modules/es.array.iterator.js'

### ISSUE THREAD

**Issue by iamyuu** [callstack/linaria#799]
## Environment

``` sh
System:
  OS: macOS 11.4
Binaries:
  Node: 14.17.0
  npm: 7.19.1
npmPackages:
  @linaria/babel-preset: 3.0.0-beta.4
  @linaria/core: 3.0.0-beta.4
  @linaria/react: 3.0.0-beta.7
  @linaria/shaker: 3.0.0-beta.7
  @linaria/webpack-loader: 3.0.0-beta.7
  next: 11.0.1
  webpack: 5
```

## Description

I'm trying to use linaria version 3-beta in next.js, but when starting the development server it's throwing the error `MODULE_NOT_FOUND`, see the screenshot below:

<img width="988" alt="Screen Shot 2021-07-11 at 20 07 31" src="https://user-images.githubusercontent.com/45778229/125196316-a57da480-e283-11eb-97dd-dddcc01c5d7e.png">

## Reproducible Demo

I'm using [next-lerna@1.0.0-beta](https://github.com/Mistereo/next-linaria)

Repository for reproduce: [next-linaria-beta-repro](https://github.com/iamyuu/next-linaria-beta-repro)

**Comment by pure-js** [comment]
I solved this problem by installing ```core-js``` manually, but of course this is not a package level solution

**Comment by codejet** [comment]
I'm having the same issue

**Comment by Anber** [comment]
[The provided repo](https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-linaria) works perfectly fine. Could someone please provide a broken one? :)

**Comment by iamyuu** [comment]
Take a look at [here](https://stackblitz.com/github/iamyuu/next-linaria-beta-repro), the difference with the next.js example is the version

next.js example:

``` json
  "dependencies": {
    "linaria": "^2.1.0",
    "next": "latest",
    "next-linaria": "^0.10.0",
  },
```

the broken:

``` json
  "dependencies": {
    "@linaria/babel-preset": "3.0.0-beta.4",
    "@linaria/core": "3.0.0-beta.4",
    "@linaria/react": "3.0.0-beta.7",
    "@linaria/shaker": "3.0.0-beta.7",
    "@linaria/webpack-loader": "3.0.0-beta.7",
    "next": "latest",
    "next-linaria": "1.0.0-beta",
  },
```

**Comment by Anber** [comment]
Oops. I see it now. It appeared, that our core-js detector is broken and `styled` requires a lot of polyfills. Thank you!

**Comment by Anber** [comment]
Two excess symbols require 6 additional polyfills. 🤦

**Comment by pilar1347** [comment]
Was this issue resolved? It looks like the PR was never merged to master.
