### ISSUE TITLE
NextJs - no refresh after style change

### ISSUE THREAD

**Issue by mrKimura** [callstack/linaria#802]
## Environment

- Linaria version: ^3.0.0-beta.4
- Next.js: latest (11)
- Bundler (+ version): webpack5 (by default)

## Description
There is no update after changing the style.
To reproduce the error, change background-color to yellow and then to green. After the first change, the style does not change anymore.

## Reproducible Demo
[Here is my sample code. ](https://codesandbox.io/s/gracious-wildflower-q2cjw?file=/pages/index.tsx)

**Comment by Mavrin** [comment]
I think the problem is that you set `cache Directory: '.nuxt/cache/linaria',`.`linaria cache` should be watched by webpack for correct work.
https://codesandbox.io/s/aged-water-v2muf?file=/pages/index.tsx

**Comment by mrKimura** [comment]
> I think the problem is that you set `cache Directory: '.nuxt/cache/linaria',`.`linaria cache` should be watched by webpack for correct work.

Thank you so much! This seems to have helped solve the problem!
