### ISSUE TITLE
Custom props leaking to DOM element

### ISSUE THREAD

**Issue by iMoses-Apiiro** [callstack/linaria#810]
## Environment

- Linaria version: 3.0.0-beta.4
- Bundler (+ version): webpack 4
- Node.js version: 14.17.2
- OS: ubuntu 21.04

## Description

Custom props aren't filtered and reach DOM elements if using a custom tag

```
Warning: React does not recognize the `riskId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `riskid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

## Reproducible Demo

```
import { styled } from '@linaria/react';

export function MyComponent() {
  return <StyledRow riskId="high" />;
}

const CustomTag = props => <div {...props} />;

const StyledRow = styled(CustomTag)`
  background-color: ${props => props.riskId === 'none' ? 'white' : 'red'};
`;
```

**Comment by geakstr** [comment]
I'm experiencing the same problem. Why it's closed?

**Comment by Anber** [comment]
@geakstr it's a duplicate of https://github.com/callstack/linaria/issues/806
We have to think about trade-offs because such a feature can bring a lot of runtime to our zero-runtime library :)
