### ISSUE TITLE
Styling any component

### ISSUE THREAD

**Issue by pure-js** [callstack/linaria#812]
## Describe the enhancement

It would be great to be able to style any component, as implemented in styled-components [https://styled-components.com/docs/basics#styling-any-component](https://styled-components.com/docs/basics#styling-any-component
)
## Possible implementations

```javascript
import { styled } from '@linaria/react';

const Link = ({ className, children }) => (
  <a className={className}>
    {children}
  </a>
);

const StyledLink = styled(Link)`
  color: palevioletred;
  font-weight: bold;
`;

render(
  <div>
    <Link>Unstyled, boring Link</Link>
    <br />
    <StyledLink>Styled, exciting Link</StyledLink>
  </div>
);
```

**Comment by Anber** [comment]
You can use `styled` for styling any component that accepts `className` (and `style` if you want to you props-based interpolation).
