### ISSUE TITLE
@linaria/babel-preset doesn't have @linaria/shaker as dependency but requires in `loadOptions.js`

### ISSUE THREAD

**Issue by soldonii** [callstack/linaria#813]
## Environment

I'm setting up linaria through babel and rollup.
As docs described, I installed `@linaria/babel-preset` and add it to `.babelrc` file.

![image](https://user-images.githubusercontent.com/49357004/128469740-e6d2fc3b-2280-4c2b-8aaf-d1f04675aef1.png)

and it throws error when bundling via rollup. Below is error message.

![image](https://user-images.githubusercontent.com/49357004/128470766-c50da88a-9554-4b1c-a287-7a123c268986.png)

The problem is, `@linaria/babel-preset` doesn't have `@linaria/shaker` as dependency, but [it requires inside of `loadOptions.js` in `@linarai/babel-preset` package](https://github.com/callstack/linaria/blob/master/packages/babel/src/utils/loadOptions.ts#L25-L27).

Below is installed package when I type `yarn add @linaria/babel-preset`. It doesn't seem to include `@linaria/shaker`.
![image](https://user-images.githubusercontent.com/49357004/128470082-2b8311fb-51c9-4d34-bfff-07c9a88a0461.png)

Is there anything that I've done wrong?

- Linaria version: latest(@linaria/babel-preset: "^3.0.0-beta.4")
- Bundler (+ version): rollup(2.3.0)
- Node.js version: 14.16.0
- OS: mac

**Comment by soldonii** [comment]
it happens whether I install `@linaria/shaker` or not.
I installed every package mentioned in docs(`@linaria/core @linaria/react @linaria/babel-preset @linaria/shaker`)
Also `yarn add --dev rollup-plugin-css-only @linaria/rollup`

**Comment by Anber** [comment]
Hi @soldonii!
Do you use yarn pnp?

**Comment by soldonii** [comment]
> Hi @soldonii!
> Do you use yarn pnp?

yes I do. Is it related to version of yarn? :)
