### ISSUE TITLE
Uncaught Error: Using the "css" tag in runtime is not supported. Made sure Babel plugin setup correctly

### ISSUE THREAD

**Issue by calummackervoy** [callstack/linaria#828]
## Environment

Here is my rollup.config.js

```
import typescript from "@rollup/plugin-typescript";
import babel from '@rollup/plugin-babel';
import commonjs from '@rollup/plugin-commonjs';
import replace from '@rollup/plugin-replace';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import linaria from '@linaria/rollup';
import css from 'rollup-plugin-css-only';
import serve from "rollup-plugin-serve";
import livereload from "rollup-plugin-livereload";

export default {
  input: "./index.tsx",
  plugins: [
    linaria({ sourceMap: process.env.NODE_ENV !== 'production', }),
    css({ output: 'styles.css', }),
    nodeResolve({ 
        extensions: [".js", ".jsx", ".ts", ".tsx"],
        module: true
    }),
    replace({
      'process.env.NODE_ENV': JSON.stringify( 'development' )
    }),
    babel({ presets: [
      ["@babel/preset-env", { targets: { node: "current" } }],
      "@babel/preset-react",
      "@babel/preset-typescript",
      "@linaria"
      ],
      extensions: [".js", ".jsx", ".ts", ".tsx"],
      exclude: /node_modules/
    }),
    commonjs({
        extensions: [".js", ".jsx", ".ts", ".tsx"],
        include: /node_modules/
    }),
    typescript({ tsconfig: "./tsconfig.json" }),
    serve({
        open: true,
        verbose: true,
        contentBase: ["", "public"],
        host: "localhost",
        port: 3000,
    }),
    livereload({ watch: "dist" }),
  ],
  output: {
    file: "dist/index.js",
    format: "iife"
  }
};
```

I've copied my use of the library almost exactly from this code here: https://github.com/sgwilym/windups-docs/blob/master/src/App.tsx#L433

- Linaria version: 3.0.0-beta.4
- Bundler (+ version): Rollup 2.56.3
- Node.js version: 12.22.4
- React version: 17.0.2
- Typescript version: 4.0.2
- OS: Mac Big Sur 11.5.2

## Description

I followed the setup guide and had a look at the other issues, but I'm finding that I receive this error at runtime. I tried changing the plugin configurations in various pseudo-random ways but so far I haven't been successful - I'm fairly new to Rollup and Babel

**Comment by Anber** [comment]
Hi @calummackervoy 

> Linaria version: 2.1.0
Are you sure? Because you use packages from `@linaria` namespace, which was introduced in 3.0

**Comment by calummackervoy** [comment]
@Anber sorry my mistake, updated my comment to reflect that I have `@linaria/core@3.0.0-beta.4`. 

Taken from this part of the output when I run `yarn list`:

```
...

├─ @linaria/babel-preset@3.0.0-beta.12
│  ├─ @babel/generator@>=7
│  ├─ @babel/plugin-syntax-dynamic-import@>=7
│  ├─ @babel/template@>=7
│  ├─ @linaria/core@^3.0.0-beta.4
│  ├─ @linaria/logger@^3.0.0-beta.3
│  ├─ cosmiconfig@^5.1.0
│  ├─ source-map@^0.7.3
│  ├─ source-map@0.7.3
│  └─ stylis@^3.5.4
├─ @linaria/core@3.0.0-beta.4
├─ @linaria/logger@3.0.0-beta.3
│  └─ debug@^4.1.1
├─ @linaria/preeval@3.0.0-beta.12
│  └─ @linaria/babel-preset@^3.0.0-beta.12
├─ @linaria/react@3.0.0-beta.7
│  ├─ @emotion/is-prop-valid@^0.8.8
│  └─ @linaria/core@^3.0.0-beta.4
├─ @linaria/rollup@3.0.0-beta.12
│  ├─ @linaria/babel-preset@^3.0.0-beta.12
│  ├─ @rollup/pluginutils@^4.1.0
│  └─ @rollup/pluginutils@4.1.1
│     ├─ estree-walker@^2.0.1
│     └─ picomatch@^2.2.2
├─ @linaria/shaker@3.0.0-beta.12
│  ├─ @babel/generator@>=7
│  ├─ @babel/plugin-transform-runtime@>=7
│  ├─ @babel/plugin-transform-template-literals@>=7
│  ├─ @babel/preset-env@>=7
│  ├─ @linaria/babel-preset@^3.0.0-beta.12
│  ├─ @linaria/logger@^3.0.0-beta.3
│  ├─ @linaria/preeval@^3.0.0-beta.12
│  ├─ babel-plugin-transform-react-remove-prop-types@^0.4.24
│  └─ ts-invariant@^0.9.0

...
```

**Comment by RossCoeH** [comment]
You are not alone - I have got the same error in using lineria with  create-react-app and adazzle/react-data-grid (Uncaught Error: Using the "css" tag in runtime is not supported. Made sure Babel plugin setup correctly).  My project was working prior to adding "css" tags.
I am assuming something missing from setup instructions (or a bug). Adding .babelrs, and ts-loader to the project as listed in instructions did not fix it.  Perhaps a working example on codepen might be a helpful resolution.
  The  first part of package.json contains:
```
 "dependencies": {
    "@babel/core": "^7.15.5",
    "@babel/preset-typescript": "^7.15.0",
    "@linaria/babel-preset": "^3.0.0-beta.13",
    "@linaria/core": "^3.0.0-beta.13",
    "@linaria/react": "^3.0.0-beta.13",
    "@linaria/shaker": "^3.0.0-beta.13",
```

**Comment by chrischen** [comment]
I also had this issue, and it was caused because I called `css` like a normal function as in `css(someCssString)`.

**Comment by pabo** [comment]
> I also had this issue, and it was caused because I called `css` like a normal function as in `css(someCssString)`.

My god you just saved my life. I was deep in a rabbit hole of babel, tsconfig, viteconfig, etc and had no idea why I was getting this error. It turns out I was doing something similar to what you were doing, but unknowingly.

```
const selected = css`
  background-color: rgb(150, 175, 150);
`;

const Button = ({ text, isSelected, clickHandler }) => {
  return (
    <button
      className={classNames({ selected: isSelected })}
      ...
```

See the problem? I didn't. the problem was fixed with:
```classNames({ [selected]: isSelected }```

D'oh! and thank you.
