### ISSUE TITLE
Regression since v2 (from 1.4)

### ISSUE THREAD

**Issue by JSteunou** [callstack/linaria#829]
## Environment

- Linaria version: v2
- Bundler (+ version): webpack 5 + babel 7.15
- Node.js version: 14
- OS: Ubuntu

## Description

What 1st appears as a babel issue might be a linaria issue. Rolling back linaria to 1.4 from v2 while upgrading babel to 7.15 fixes our issue.

Also, as notice in the babel ticket, the babel.config.js is called when using linaria in webpack babel-loader context, (v1.4 and v2), dont know if it is a clue but I found it weird.

See this ticket https://github.com/babel/babel/issues/13722 for more details but in a nutshell a build with webpack & babel-loader is broken when having decorator if babel is v7.15 & linaria v2

Without a wide babel config, it crashes not on decorator but on TypeScript syntax, as if nothing was transformed, which made me think that linaria does not uses input from previous loader, but run it's own babel process.

## Reproducible Demo

https://github.com/JSteunou/babel-linaria-decorator-issue

**Comment by JSteunou** [comment]
I finally had time to make a repo to reproduce this issue https://github.com/JSteunou/babel-linaria-decorator-issue 

You can play with it and see that rolling back either babel to 7.14 either linaria to 1.4 solve it

**Comment by JSteunou** [comment]
Hi @Anber, if you or another team member has some time, here is the analyse from babel's member nicolo-ribaudo https://github.com/babel/babel/issues/13722#issuecomment-912940846

It's to complex for me to open a PR on this but maybe I could help if someone guide me a little if you do not have the time to fix this and want to focus on v3

**Comment by Anber** [comment]
Hi @JSteunou 

Thank you for the investigation! I'll try to figure out what can be done here.

**Comment by Anber** [comment]
Hi @JSteunou 

In theory, you can use `babelOptions` and pass missed plugins to Linaria's Babel config. However, even in that case, it doesn't work probably because of conflicts in plugins order. Would be cool if you can find out where exactly that conflict is.
