### ISSUE TITLE
Props based object interpolations

### ISSUE THREAD

**Issue by oriooctopus** [callstack/linaria#838]
## Describe the enhancement

Is it possible to have props based object interpolation? Here is an example:

```
function getStylesFromProp(variant) {
  if (variant === 'primary') {
    return {
      color: 'red';
      textTransform: 'uppercase';
    };
  } else {
    return {
      backgroundColor: 'pink',
    };
  }
}

export const BaseText = styled.span`
  margin: 0;

  ${(props) => getStylesFromVariant(props.variant)}
`;
```

## Motivation

Sometimes you don't always know which properties you'll need. Also specifying something like

`backgroundColor: ${props => props.variant === 'primary' ? undefined : 'pink'}`

for each property is really cumbersome

## Possible implementations

My guess is not possible because it's not capable with css variables/static build-time extraction but wanted to double check!

**Comment by Anber** [comment]
Hi @oriooctopus!

It's not possible. However, you can use something like this:
```jsx
import { css, cx } from "@linaria/core";
import { styled } from "@linaria/react";

const variants = {
  primary: css`
      color: red;
      text-transform: uppercase;
  `,
};

const defaultClass = css`
      background-color: pink,
`;

const BaseText = styled(({ className, variant }) => {
  return <span className={cx(className, variants[variant] ?? defaultClass)}>;
})``;
```

In addition, this variant prevents leaking custom props to the resulting DOM.

**Comment by oriooctopus** [comment]
@Anber thank you very much for your response. One question I have for you: Is the above example any better than
```
const variants = {
  '&.primary': {
    color: 'red',
    textTransform: 'uppercase',
  },
  '&.secondary': {
    color: 'pink',
  }
};

const Text = styled.span`
  margin: 5px;
  ${variants}
`;

const Heading = ({variant}) => (
  <Text className={variant}>Some text</Text>
)
```
Also I'm curious, why did you wrap BaseText in a `styled` function? 

thanks again!

**Comment by Anber** [comment]
> Is the above example any better than the below example in terms of performance/bundle size?

I don't think so. I just don't like explicit class names because they can interfere with each other. And as you can see, the variant with object interpolation wasn't tested enough :)

> Also I'm curious, why did you wrap BaseText in a styled function?

It's just a shorter version of your code, when you create `Text` as a `styled.span` and then use it in `Heading`. It can be rewritten to
```jsx
const Heading = styled(({ className, variant}) => (
  <span className={cx(className, variant)}>Some text</span>
))`
  margin: 5px;
  ${variants}
`
``` 
Another point here is that you can use wrapped components as selectors in styles:
```jsx
const Article = styled.div`
  & > ${Heading} {
    // some styles for Heading nested in Article
  }
`
```

**Comment by Anber** [comment]
Also, it can be used for typecheking:
```typescript
type Variant = "primary" | "secondary";

const variants: Record<Variant, LinariaClassName> = {
   primary: css``,
   secondary: css``,
};

interface IBaseTextProps {
  className?: LinariaClassName;
  variant: Variant;
}

const BaseText = styled(({ className, variant }: IBaseTextProps) => {
  return <span className={cx(className, variants[variant] ?? defaultClass)}>;
})``;
```

**Comment by shivamragnar** [comment]
The solution that you have shared @Anber works well, if you already know the value of the props. What if the variant value is dynamic, say some random number for width and height?

**Comment by Anber** [comment]
@shivamragnar, you can use props-based interpolation for that specific dynamic values. The whole props-based interpolation is built around CSS variables. If something is possible to implement with these variables, it is possible to implement with Linaria, but object interpolation is no such thing. Sorry 🤷‍♂️

**Comment by shivamragnar** [comment]
@Anber so how should we write not object interpolation but something like this, wrapping a property in the props and applying that property if that particular prop exists? I hope you get the syntax.
```js
const BaseText = styled.span`
   // Some styles here...
   
   ${(props) => props.width &&`
      width: ${props.width};
   `}
    
   // More generic might look like
   ${(props) => props.something &&`
      width: ${props.width};
      height: ${props.height};
      border-radius: 4px;
   `}
`;
```
