### ISSUE TITLE
Allow re-exporting of templates such as `styled` and `css` from internal files

### ISSUE THREAD

**Issue by jpnelson** [callstack/linaria#851]
## Describe the feature

We'd like to be able to re-export the `css` and `styled` template literals. Currently, the babel plugin will only detect and replace imports from the linaria library. This, for example, would not work:

`./my-folder/linaria`

```js
export { css } from 'linaria';
```

`./index.js`

```js
import { css } from './my-folder/linaria'

const className = css`
  background: red;
`
```

Since `css` is not being imported directly from `linaria`

## Motivation

We have some linaria specific utilities (eg. shared styles and the like) that we house in a separate folder. It's a little cumbersome to also import the public API – if we could, we would re-export it from our internal folder to keep everything in one place.

## Possible implementations

We could implement this either by adding logic to try to resolve the imports (might be tricky with custom configs) or to allow specifying which import paths may contain `styled` and `css` – I'd be happy to take direction on which of these is preferred.

**Comment by Anber** [comment]
Hi @jpnelson 

Just custom import paths will not help because `css` and `styled` can be reexported in different ways and with different names. Probably we need to introduce a new config option for a custom resolve function and completely refactored `hasImport` which will use that option.

**Comment by jpnelson** [comment]
@Anber I had a go at this here: https://github.com/callstack/linaria/pull/882 – it turned out to be not too tricky, let me know what you think! 🙏

**Comment by jpnelson** [comment]
Done in https://github.com/callstack/linaria/pull/882
