### ISSUE TITLE
CSS url is unable to resolve and crashes the entire build

### ISSUE THREAD

**Issue by iMoses-Apiiro** [callstack/linaria#857]
## Environment

- Linaria versions:
```
    "@linaria/core": "^3.0.0-beta.13",
    "@linaria/react": "^3.0.0-beta.13",
    "@linaria/babel-plugin-interop": "^3.0.0-beta.7",
    "@linaria/babel-preset": "^3.0.0-beta.13",
    "@linaria/shaker": "^3.0.0-beta.13",
    "@linaria/webpack-loader": "^3.0.0-beta.13",
```
- Bundler (+ version): Webpack 4.46.0
- Node.js version: 14.18.1
- OS: Ubuntu 21.04

## Description

Can't resolve error when trying to use `url` inside a styled component.

```
import backgroundUrl from '../assets/images/my-background.svg';

const Container = styled.div`
  background-image: url(${backgroundUrl});
`;
```

Will produce this error:
```
./src/.linaria-cache/components/test.linaria.css
Error: Can't resolve '../../../../../assets/images/my-background.svg' in '/home/.../src/.linaria-cache/components'
    at runMicrotasks (<anonymous>)
```

And if I try to use an alias the error changes slightly:
```
import backgroundUrl from '@src/assets/images/my-background.svg';
```
```
./src/.linaria-cache/components/test.linaria.css
Error: Can't resolve '../@src/assets/images/my-background.svg' in '/home/.../src/.linaria-cache/components'
    at runMicrotasks (<anonymous>)
```

Also tried:
```
  background-image: url("${backgroundUrl}");
```
```
  background-image: ${`url(${backgroundUrl})`};
```
Which doesn't work...

BUT this solution does work:
```
  background-image: ${() => `url(${backgroundUrl})`};
```

Not sure what more info I can provide, seems to me like there's an issue with how linaria process `url` in styles.

**Comment by Anber** [comment]
It works fine in my code. Could you please provide a sample repo?

**Comment by Anber** [comment]
Probably was fixed in the last beta.

**Comment by mindyourlifeguide** [comment]
Faced this problem.

version:
  "linaria": "^3.0.0-beta.19",
  "next": "^12.2.0",
  "next-linaria": "^1.0.1-beta",

or
  
  "linaria": "^2.3.1",
  "next": "^12.1.6",
  "next-linaria": "^0.11.0",

**Comment by layershifter** [comment]
> The issue is present in latest versions:
> 
> ```
>     "@linaria/core": "3.0.0-beta.22",
>     "@linaria/shaker": "3.0.0-beta.22",
>     "@linaria/webpack-loader": "3.0.0-beta.22",
> ```
> 
> The repro repository: https://github.com/layershifter/linaria-url-issue
> 
> * clone
> * `yarn`
> * `webpack`
> 
> You will get something like that:
> 
> ![image](https://user-images.githubusercontent.com/14183168/178509038-7a7cfb7a-b402-463a-b06b-90ccaacdc086.png)
> 
> _Notice that `favicon.png` is also in `dist`._
> 
> ![image](https://user-images.githubusercontent.com/14183168/178508983-7f834fe0-da36-4ac5-a9bc-f20756ee98fb.png)
> 
> However, an image is linked to a wrong file.

Oops, my bad.

```diff
const header = css`
  text-transform: uppercase;
- background-image: ${icon};
+ background-image: url(${icon});
`;
```

And it works like a charm 💎
