### ISSUE TITLE
Specificity with `cx` mixins unreliable

### ISSUE THREAD

**Issue by madeleineostoja** [callstack/linaria#868]
## Environment

- Linaria version: 3.0.0-beta.13
- Bundler (+ version): Webpack 5
- Node.js version: 16
- OS: macOs

## Description

Creating reusable chunks of styles with `css` and then composing them with `cx()` results in uncertain specificity, where you can't override styles from any chunk.

## Reproducible Demo

Simplified real life use-case this came from:

**typesets.ts**
```jsx
export const typesets = {
  sm: css`
    font-size: var(--scale-00);
    line-height: var(--line-sm);
  `
}
```

**Button.tsx**
```jsx
	<button className={cx(typsets.sm, css`line-height: 0`)}>Button</button>
```

The typeset mixin is imported after the inline css block, so the line-height override isn't applied. This is also a problem with variants applied with `cx()`, eg: a list of CSS blocks based on props.

Possible solution to this is to just pass everything around as plain strings and inline them in the `css` chunks, but I'm not sure what ramifications that has re: code-splitting and code sharing.

**Comment by madeleineostoja** [comment]
Reading up more on prior discussions with composition and `css`, this seems like it could be a major pain point for Linaria. What's the current recommended solution to this kind of use-case? Will the upcoming atomic package handle it better?

Could be a dealbreaker for us unfortunately, [Compiled](https://compiledcssinjs.com/) does a very seamless job of composition and atomic output, but I imagine that's because they've wedded themselves to React. Would introducing a `css={css''}` prop be a possible solution for Linaria in a React context at least?

**Comment by Anber** [comment]
Since we can't guarantee the order of rules, there are only two ways (as far as I see) to override `line-height` in your example:
1. use `&&` selector: ```cx(typsets.sm, css`&& { line-height: 0 }`)```;
2. override variable: ```cx(typsets.sm, css`--line-sm: 0```;

I personally prefer the second one.

The atomic package is going to be released today but I don't know if it will be better.
