### ISSUE TITLE
Reference on component imported via barell export

### ISSUE THREAD

**Issue by topolanekmartin** [callstack/linaria#869]
## Describe the enhancement

I am used to do barell export for my files with styled components. Few days ago we decided to leave styled components library and add linaria library to our project. I am also used to do references to other styled component often.
It was really confusing for me, when I found out after 4 days fixing bug with option `evaluate: true` that I need to import right the file with the styled component.

So instead having this:
```
import { StyledSelectInput } from '@components/Select/components';
```

I need to do this:
```
import { StyledSelectInput } from '@components/Select/components/Input/styles/Input.style';
```

## Motivation

By fixing this we can have more clearer imports and other developers may not occurs with this type of error which can be confusing.

## Possible implementations

- Add this information to documentation
- Add posibility to do reference on component whis is imported via barell export

**Comment by layershifter** [comment]
Please try latest versions. If the problem still happens, please open a new issue and provide a reproduction case 🙏
