### ISSUE TITLE
Webpack 5 output clean breaks linaria HMR

### ISSUE THREAD

**Issue by dmca-glasgow** [callstack/linaria#880]
## Environment

linaria: ^3.0.0-beta.13
webpack: ^5.64.4
node: v14.17.5
OS: Mac OS 12.0.1 

## Description

Not sure how unusual my config is, but I had started using `output.clean = true` from the [Webpack docs](https://webpack.js.org/configuration/output/#outputclean) instead of separately importing [clean-webpack-plugin](https://github.com/johnagan/clean-webpack-plugin).

After several hours of debugging I found this was the cause of HMR not working with Linaria (`styled` and `@linaria/react`).  

I would receive a 404 from HMR `hot-update.json` in the browser console and a "wait until bundle finished" message in the terminal.  Without diving too deep, I could see that changes to other React code and non-linaria CSS files would generate a hot-update.json file, but styles defined inside `styled` blocks would not.

Switching back to CleanWebpackPlugin solves the problem.

Hopefully this helps someone else in the same position.

Love Linaria, use it in all my projects, cheers!

**Comment by Anber** [comment]
Hi @dmca-glasgow!

Could you please try `@linaria/webpack5-loader@3.0.0-beta.16`? It has some HMR improvements. If it doesn't work, may I ask you to provide a simple repo that reproduces the problem?

**Comment by dmca-glasgow** [comment]
HI @Anber,

I attemped this yesterday, but I think you may need to release `3.0.0-beta.16` to npm?  Yarn will only let me install up to `beta.15`.

Thanks

**Comment by Anber** [comment]
It was released yesterday https://www.npmjs.com/package/@linaria/webpack5-loader
Do you have an npm-proxy or your own npm registry (eg. Nexus)? If so, it may cache packages for a couple of days.
And please note, that only `@linaria/webpack*` packages were released, the rest of the packages are still under beta-15.

**Comment by dmca-glasgow** [comment]
Hi again.

Thank you, I have managed to update to `beta.16`.

This release fixes the issue and I can use `output.clean` from Webpack 5.

The in-memory cache seems like a great simplification too 🎉

**Comment by Anber** [comment]
Hooray! 🎉

**Comment by iMoses-Apiiro** [comment]
Having the same issue, can confirm that the same solution works for me as well..
Can't upgrade to `beta.16` yet because of a separate bug which causes the build to break..

thanks for this report, wish I'd found it 4 hours earlier :sweat_smile:
