### ISSUE TITLE
In-memory cache isn't compatible with thread-loader

### ISSUE THREAD

**Issue by malash** [callstack/linaria#881]
## Environment

- Linaria version: 2.2.0
- Bundler (+ version): Webpack 5.64.4
- Node.js version: 16.3.0
- OS: macOS 12.0.1

## Description

The PR https://github.com/callstack/linaria/pull/879 introduced an in-memory cache to fix rebuild issue and accelerate bundle time. It's awesome, but when I try to integrate the latest version of Linaria in my project, I found some output CSS code is missing.

I deep dived and realize the in-memory cache may not be compatible with [thread-loader](https://webpack.js.org/loaders/thread-loader/). `thread-loader` use a thread poll to execute loaders in non-main threads, which can hugely speed up Webpack's building time in a large project. Since the threads in NodeJS cannot share the same closure context, the [cssLookup](https://github.com/callstack/linaria/pull/879/files#diff-d279ac35f28bc8fef0b98f559d88b3169b2709c3c289b7de384d72f4f73b1dbd) map could be empty when running `outputCssLoader.ts` in a brand new thread.

I'm not sure is this a bug or a feature request? because not all Webpack projects use the `thread-loader`. But in our project, the build time would become non-acceptable if I disabled the `thread-loader`. So I can provide a posable solution if you agree to fix this issue:

## Solution

Add a new options to return the right of choice to Linaria users.

- `cacheType: 'memory' | 'filesystem'` (default: `'memory'`):

This option is inspired from Webpack's [cache.type](https://webpack.js.org/configuration/cache/#cachetype). If set to `memory` the loader works in the same way as 2.2.0, and if set to `filesystem` it works in the same way as 2.1.0.

- `cacheDirectory: string` (default: `'.linaria-cache'`):

Same as previous. Only works when `cacheType: 'filesystem'`

## Reproducible Demo

https://github.com/malash/linaria-issue-881

You can enable/disable [this line](https://github.com/malash/linaria-issue-881/blob/master/webpack.config.js#L26-L29) and run `yarn webpack`, the check the result of `dist/styles.css`.

![image](https://user-images.githubusercontent.com/1812118/144583450-5aaf732b-20a1-44e3-9a8d-29bbc03347f7.png)

**Comment by malash** [comment]
cc @Anber

**Comment by Anber** [comment]
Hmm…
thread-loader docs say, that loaders in threads have some limitations:
- Loaders cannot emit files.
- Loaders cannot use custom loader API (i. e. by plugins).
- Loaders cannot access the webpack options.

I'll try to implement a configurable cache, but it looks like we can face more problems with this plugin.

**Comment by malash** [comment]
Hi @Anber I cost some time to implement this feature in https://github.com/callstack/linaria/pull/884 for Linaria v2. Could you please take a look ?

If it's approved, I can create another PR to cherry pick it into Linaria v3.
