### ISSUE TITLE
Typescript Enums are undefined

### ISSUE THREAD

**Issue by notwillk** [callstack/linaria#923]
## Environment

- Linaria version: 3.0.0-beta.15
- Bundler (+ version): 5.68.0
- Node.js version: v16.13.2
- OS: mac OS 10.15.7

## Description

Using typescript enums does not work in linaria CSS.

## Reproducible Demo

```typescript
enum Something = {
  one: 'one',
  two: 'two`
}

const HEIGHTS: Record<Something, string> = {
  [Something.one]: '1px',
  [Something.two]: '100px',
}

const Fancy = styled.div`
  height: ${HEIGHTS[Something.one]};
`
```

Compiling this results in an error, where `Something` is undefined when trying to evaluate `HEIGHTS[Something.one]`.

**Comment by layershifter** [comment]
If you have proper config for Babel that contains `@babel/preset-typescript`, it should work properly in v5:

<img width="524" alt="image" src="https://github.com/callstack/linaria/assets/14183168/bfc289f7-743d-4383-a19d-c814526a5eb4">

Here is a minimal config needed: https://stackblitz.com/edit/stackblitz-starters-vq7uwk
