### ISSUE TITLE
@linaria/stylelint does not work with stylelint ^14.0.0

### ISSUE THREAD

**Issue by Shmuppel** [callstack/linaria#930]
## Environment
Linaria's website

- Linaria version: 2.3.1
- Bundler (+ version):  webpack 4.46.0
- Node.js version: v14.18.1
- OS: MacOS BigSur v11.6.2

## Description
Stylelint 14 brought breaking changes that remove the `syntax` command in the Stylelint config. 
This should be replaced with the customSyntax option, i'm not sure if such an option is available that would
work with linaria. But currently all linting fails with `Unknown word  CssSyntaxError` errors.

In any case the LINTING documentation does not work out of the box, rolling back to Stylelint 13 fixes the issue. 

https://stylelint.io/migration-guide/to-14/

## Reproducible Demo
```
git clone git@github.com:callstack/linaria.git
cd website/ && npm install
npm install stylelint@14.0.0
npm run-script lint:css
```

Thanks for the amazing lib!

**Comment by mmakarin** [comment]
+1000000

**Comment by hueindahaus** [comment]
+1

**Comment by kutnickclose** [comment]
For stylelint 13, @linaria/stylelint uses a [preprocessor](https://github.com/callstack/linaria/blob/master/packages/stylelint/src/index.ts#L2) to create a [css-ish](https://github.com/callstack/linaria/blob/master/packages/stylelint/src/preprocessor.ts#L88) file before running linting tests on it. 

For stylelint 14, stylelint [discourages using a (pre)preprocessor](https://stylelint.io/developer-guide/processors) in favor of a custom syntax that essentially tells stylelint how to work with a non-css file. 

[postcss-lit ](https://github.com/43081j/postcss-lit)seems to be one of the [more promoted css-in-js](https://stylelint.io/developer-guide/syntaxes) custom syntax packages that's making use of new features in Postcss 8.3 (Document nodes).  After a quick prototype, it doesn't seem to work for linaria completely out of the box but we could likely base a custom syntax off of that package. 

How does a @linaria/postcss-linaria package sound that could be used for stylelint 14? There is also [additional discussion](https://github.com/stylelint/postcss-css-in-js/issues/225) of stylelint deprecating its @stylelint/postcss-css-in-js package in favor of individual css-in-js libraries.
