### ISSUE TITLE
Keyframe names not suffixed with "-<class_name>" when set by function

### ISSUE THREAD

**Issue by Gkjsdll** [callstack/linaria#946]
## Environment

- Linaria version: `2.3.1`
- Bundler (+ version): `webpack 4.22.0`
- Node.js version: `16 (16.12.0)`
- OS: `Windows 10 Pro 21H1 (19043.1586)` locally. Codesandbox.io `uname -a` ->  `Linux sse-sandbox-efr8gl 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 GNU/Linux`

## Description

Keyframe names are not suffixed by `-<class_name>` when they are set by a function / saved in a css variable. Declaring the keyframes in another variable or in the same string doesn't seem to make a difference, though that's not in the demo.

| Keyframe declaration | Output |
| --------------------- | ------- |
| `animation-name: test-frames;` | ![firefox_OqMvO4IXTE](https://user-images.githubusercontent.com/7777305/158035633-59f3c1d8-b563-4872-8f7d-815ced0aae36.png) |
| `animation-name: ${"test-frames"}` | ![firefox_pqtMeR5Nww](https://user-images.githubusercontent.com/7777305/158035634-4bfb25e9-575f-4f60-bfd4-08b14832ca6c.png) |
| `animation-name: ${() => "test-frames"}`; | ![firefox_rtnYDx9bWI](https://user-images.githubusercontent.com/7777305/158035635-1ec49708-d7c8-44c7-81d3-c030c143f134.png) |
| `animation-name: ${({ animate }) => (animate ? "test-frames" : "test-frames")};` | ![firefox_VDAbZgUIt2](https://user-images.githubusercontent.com/7777305/158035636-4dc22c1b-7036-40a6-b44d-fc589c36b376.png) |

## Reproducible Demo
https://codesandbox.io/s/linaria-keyframes-from-functions-efr8gl?file=/src/App.js

**Comment by AndrewVorobev** [comment]
same here

**Comment by Anber** [comment]
The problem here that an animation name cannot be specified with a variable. It's the limitation which seems impossible to address. The only way here is the second point from that comment https://github.com/callstack/linaria/issues/1048#issuecomment-1280704721
