### ISSUE TITLE
_loaderUtils.default.stringifyRequest is not a function

### ISSUE THREAD

**Issue by ntucker** [callstack/linaria#977]
## Environment

- Linaria version: 3 beta.19
- Bundler (+ version): webpack 5.73.0
- Node.js version: 16
- OS: ubuntu

## Description

```bash
TypeError: _loaderUtils.default.stringifyRequest is not a function
    at /home/circleci/project/node_modules/@linaria/webpack5-loader/lib/index.js:166:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 @ ./src/index.tsx 1:76-99 1:228-231
```

loader-utils 3 [removes stringifyRequest](https://github.com/webpack/loader-utils/blob/a282654ddfa0a8c9c770db1adfa064e671bcf471/CHANGELOG.md#300-2021-10-20), yet 3 is the version this library requests (`"loader-utils": "^3.2.0",` from package.json).

"removed stringifyRequest in favor JSON.stringify(loaderContext.utils.contextify(loaderContext.context || loaderContext.rootContext, request)) (loaderContext is this inside loader function), also it will be cachable and faster"

Seems like the easy fix is to simply use the method described in their release notes.

Alternatively you could simply revert the breaking change upgrade from https://github.com/callstack/linaria/pull/974 (not the whole PR just moving from v2 to v3)

## Reproducible Demo

https://github.com/ntucker/anansi/tree/renovate/all-minor-patch

1. git clone https://github.com/ntucker/anansi
2. git checkout renovate/all-minor-patch
3. yarn install
4. yarn build:pkg
5. cd examples/linaria
6. yarn build

Also seen here: https://app.circleci.com/pipelines/github/ntucker/anansi/7208/workflows/d3ed1b79-2ae9-4211-b3dd-8733c2c80d30/jobs/36245

**Comment by Anber** [comment]
Thank you @ntucker!
Fixed.
