### ISSUE TITLE
Error: Cannot find module '@linaria/core/processors/BaseProcessor' when building node version in devmode

### ISSUE THREAD

**Issue by ntucker** [callstack/linaria#984]
## Environment

webpack config has:

```js
    config.externals = [
      nodeExternals({
        additionalModuleDirs: ['../../node_modules'],
        allowlist: [
          /^@anansi\/core\/server/,
          /^path-to-regexp/,
          /\.css$/,
        ],
      }),
    ];
```

Building for server side

- Linaria version: 3.0.0-beta.20
- Bundler (+ version): webpack 5.73.0
- Node.js version: v16.15.0
- OS: ubuntu 20.04

## Description

```bash
ModuleBuildError: Module build failed (from ../../node_modules/@linaria/webpack5-loader/lib/index.js):
Error: Cannot find module '@linaria/core/processors/BaseProcessor'
Require stack:
- /home/ntucker/src/anansi/node_modules/@linaria/babel-preset/lib/utils/getTagProcessor.js
- /home/ntucker/src/anansi/node_modules/@linaria/babel-preset/lib/utils/replaceTagWithValue.js
- /home/ntucker/src/anansi/node_modules/@linaria/babel-preset/lib/index.js
- /home/ntucker/src/anansi/node_modules/@linaria/webpack5-loader/lib/index.js
- /home/ntucker/src/anansi/node_modules/loader-runner/lib/loadLoader.js
- /home/ntucker/src/anansi/node_modules/loader-runner/lib/LoaderRunner.js
- /home/ntucker/src/anansi/packages/core/node_modules/webpack/lib/NormalModuleFactory.js
- /home/ntucker/src/anansi/packages/core/node_modules/webpack/lib/Compiler.js
- /home/ntucker/src/anansi/packages/core/node_modules/webpack/lib/webpack.js
- /home/ntucker/src/anansi/packages/core/node_modules/webpack/lib/index.js
- /home/ntucker/src/anansi/packages/core/lib/scripts/startDevserver.js
- /home/ntucker/src/anansi/packages/core/lib/scripts/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ntucker/src/anansi/node_modules/@linaria/babel-preset/src/utils/getTagProcessor.ts:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (/home/ntucker/src/anansi/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.Module._extensions..js (/home/ntucker/src/anansi/node_modules/fs-monkey/lib/patchRequire.js:141:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

```js
{
    request: '/home/ntucker/src/anansi/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].oneOf[1].use[0]!/home/ntucker/src/anansi/node_modules/@linaria/webpack5-loader/lib/index.js??ruleSet[1].rules[0].oneOf[1].use[1]!/home/ntucker/src/anansi/examples/concurrent/src/index.server.tsx',
    userRequest: '/home/ntucker/src/anansi/examples/concurrent/src/index.server.tsx',
    rawRequest: './src/index.server.tsx',
}
```

Note: yarn build (building client production) and yarn build:server (building server production) both work. It's the webpack-dev-server build for node that doesn't work.

## Reproducible Demo

https://github.com/ntucker/anansi/tree/c85f2c42602fda03594966eb7a2b90d3e45cfd4e

1. git clone https://github.com/ntucker/anansi
2. git checkout c85f2c42602fda03594966eb7a2b90d3e45cfd4e
3. yarn install
4. yarn build:pkg
5. cd examples/concurrent
6. yarn start

**Comment by Anber** [comment]
Something wrong with resolving [conditional exports](https://nodejs.org/api/packages.html#conditional-exports) inside webpack. I'll take a look.

**Comment by Anber** [comment]
Hi @ntucker 
Step 6 says that `@anansi/core must be installed to run this subcommand`. `yarn install` inside `examples/concurrent` doesn't help. 
```
> yarn -v
< 3.2.1
> node -v
< v18.3.0
```

**Comment by ntucker** [comment]
You're supposed to yarn install before you change directory

**Comment by ntucker** [comment]
Yarn v1 should be used...how did you get v3 in a global case I thought yarn 2 was all about per project config

**Comment by Anber** [comment]
https://github.com/ntucker/anansi/blob/c85f2c42602fda03594966eb7a2b90d3e45cfd4e/.yarnrc.yml it's here

**Comment by ntucker** [comment]
You ran yarn build:pkg? That should have built core

**Comment by Anber** [comment]
My bad. Sorry for disturbing you. I was distracted during the setup and missed the step.

**Comment by Anber** [comment]
After two hours in the debugger, I finally have an answer: the killer is `fs-monkey` that doesn't support `exports` in `package.json`. Is it possible for you to replace it with something that supports node 12+?

**Comment by ntucker** [comment]
Wow, thanks. I'll look into this

**Comment by Anber** [comment]
I will try to add aliases for backward compatibility.

**Comment by ntucker** [comment]
Oh nice - that's probably great to making everyone's upgrade path smoother. Thanks @Anber ! <3

**Comment by ntucker** [comment]
Hmm, I still get Error: Cannot find module '@linaria/core/processors/BaseProcessor' when using fs-monkey. I'll try to figure out another thing to use. The production builds now work so that's definitely the only problem for me.

**Comment by Anber** [comment]
Hm. For some reasons, processes folder hasn't been published to npm. I'll fix it tomorrow.

**Comment by Anber** [comment]
I forgot to add it to the list of published files in package.json. 🤦‍♂️

**Comment by ntucker** [comment]
For anyone stumbling on this thread, I was able to solve require() compat by switching to fs-require from fs-monkey. https://github.com/ntucker/anansi/pull/1538
