### ISSUE TITLE
import in esbuild appears to be completely broken (reproducible)

### ISSUE THREAD

**Issue by silviogutierrez** [callstack/linaria#986]
## Environment

Appears to be related to https://github.com/callstack/linaria/pull/955 and https://github.com/callstack/linaria/issues/954

Here's a repro: https://github.com/silviogutierrez/linaria-esbuild-bug

- Linaria version: beta20
- Bundler (+ version): esbuild 0.14
- Node.js version: v14

## Description

It seems all external imports are broken.

## Reproducible Demo

1. Clone https://github.com/silviogutierrez/linaria-esbuild-bug
2. Run `yarn` or `npm install`
3. Run `node build.js`.

Let me know if you need more information. Maybe I'm missing something or an additional required step.

**Comment by Anber** [comment]
Thank you, @silviogutierrez!
Fixed and will be released soon.

**Comment by silviogutierrez** [comment]
@Anber : thanks for the super quick turnaround!

Quick question: is esbuild such a rarely used plugin that it wasn't caught earlier? Afaik, it broke all builds, especially with semver. Or was there some specific condition in my setup? This is *very* popular library, so I'm curious.

And for another esbuild issue, check out this other issue I filed a while back: https://github.com/callstack/linaria/issues/898

Thanks again for this fix and for this incredible library.

**Comment by Anber** [comment]
`@linaria/esbuild` has ≈60 times fewer downloads than webpack-plugins, so yes it is pretty rarely used. I'm surprised that it worked for @aiji42, so maybe there are some specific conditions.

> And for another esbuild issue, check out this other issue I filed a while back: https://github.com/callstack/linaria/issues/898
I'll take a look. Source maps and esbuild are a dark forest for me, and I hoped that maybe someone who knows it better would come and fix it :)

**Comment by silviogutierrez** [comment]
@Anber : thanks, I looked into it a bit and have some findings. I'll post on that thread.
