### ISSUE TITLE
Website seems to be down down

### ISSUE THREAD

**Issue by IgnusG** [callstack/linaria#998]
## Description
https://linaria.dev/ displays a blank screen with the error React is not defined.

## Reproducible Demo

![image](https://user-images.githubusercontent.com/6438760/176021079-ca74ae6a-6ab3-4fcc-b2e2-bf942c6821ac.png)

![image](https://user-images.githubusercontent.com/6438760/176021628-d4940899-bcef-4271-9f5f-87d3013619ee.png)

I've tried latest Edge and Firefox

**Comment by Anber** [comment]
Thank you! Fixed.
